### DISCUSSION TITLE
How to show the number of subordinate UIDs for a user?

### DISCUSSION THREAD

**Discussion by eriksjolund** [containers/podman#12080] [Q&A] [answered]
Is there an easy way to show the number of subordinate UIDs for a user?
(I'm looking for a command-line tool)

I see there is uidmap information in the output from `podman info`:
```
$ podman info | grep -A 6 uidmap
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
$ 
```

Is it maybe possible by using `podman info --format` with a clever format string?

(I haven't learned that syntax yet)

Note also:
"_Multiple ranges may be specified per user._"
a quote from:
https://man7.org/linux/man-pages/man5/subuid.5.html

#### An example of what I'm looking for

For example, this configuration

```
[testpodman@localhost ~]$ grep -r $USER /etc/subuid
testpodman:362144:65536
[testpodman@localhost ~]$
```

would yield this result

```
[testpodman@localhost ~]$ num_subuids $USER
65536
[testpodman@localhost ~]$
```
(The command `num_subuids` does not yet exist).

Just being able to detect the number of subordinate UIDs for the current user would also be fine.

**Comment by vrothberg** [comment]
Thanks for reaching out, @eriksjolund!

The format string you're looking for is: `podman info --format "{{ (index .Host.IDMappings.UIDMap 1).Size}}"`

**Reply by Luap99** [reply]
AFAIK This will panic when the user has no subordinate IDs.
This should work better and print 0 when there are no extra IDs :
`podman info --format "{{if eq (len .Host.IDMappings.UIDMap) 1}}0{{else}}{{ (index .Host.IDMappings.UIDMap 1).Size}}{{end}}"`

**Reply by vrothberg** [reply]
That looks even better, thanks @Luap99 !

**Reply by eriksjolund** [reply]
Thanks @vrothberg @Luap99 for the suggestions!
It works for a single range but not for multiple ranges:

```
[testuser@localhost ~]$ podman info | grep -A9 uidmap
    uidmap:
    - container_id: 0
      host_id: 1006
      size: 1
    - container_id: 1
      host_id: 493216
      size: 65536
    - container_id: 65537
      host_id: 593216
      size: 65536
[testuser@localhost ~]$ 
```


```
[testuser@localhost ~]$ grep testuser /etc/subuid
testuser:493216:65536
testuser:593216:65536
[testuser@localhost ~]$  podman info --format "{{if eq (len .Host.IDMappings.UIDMap) 1}}0{{else}}{{ (index .Host.IDMappings.UIDMap 1).Size}}{{end}}"
65536
[testuser@localhost ~]$ 
```

I would have expected to see:
131072

(65536 + 65536)
