### DISCUSSION TITLE
Not sure if it's podman related, but when I pull my ghcr package, it grabs the Dockerfile of the wrong architecture. Armv7 instead of Aarch64.

### DISCUSSION THREAD

**Discussion by Folaht** [containers/podman#13386] [Q&A] [answered]
So I have created a github package containing Alpine Linux and a networking app, which is all fun and nice.  
This networking app is gaining a lot of side apps and one of them runs on Rust, so I added rust on the container.
However, since some people don't like raspberri Pi and some of the competition is still at armv7, and Alpine Linux doesn't have a rustup package for armv7 yet, I had to spilt the Dockerfile in two, one for amd64 and arm64 and one separate for the older armv7 architecture.  

Thus my github ghcr packaging file looks like this:

`publish-rf-rootnode-ipv4.yml`
```
     ...
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/rf-rootnode-ipv4/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker arm v7 image with Buildx
      # Necessary because Alpine linux does not support rust with arm v7
      - name: Build and push Docker arm v7 image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/rf-rootnode-ipv4/Dockerfile_v7
          platforms: linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    ...
```

`publish-rf-rootnode-ipv4.yml`
https://raw.githubusercontent.com/safenetwork-community/safenetwork-dockerfiles/latest/.github/workflows/publish-rf-rootnode-ipv4.yml

`Dockerfile`
https://raw.githubusercontent.com/safenetwork-community/safenetwork-dockerfiles/latest/src/rf-rootnode-ipv4/Dockerfile

`Dockerfile_v7`
https://raw.githubusercontent.com/safenetwork-community/safenetwork-dockerfiles/latest/src/rf-rootnode-ipv4/Dockerfile_v7

So then I pull it on a aarch64 machine (Rpi4).
```
sudo podman pull ghcr.io/safenetwork-community/rf-rootnode-ipv4
```

I expect it to pull the aarch64 version, 
but whatever reason, the pull loads the Dockerfile_v7 instead.

```
bash-5.1# uname -m
aarch64
bash-5.1# apk --print-arch
armv7
bash-5.1# gcc -dumpmachine
armv7-alpine-linux-musleabihf
bash-5.1# file cargo
cargo: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

[update]

This seems more and more a github action issue.
