### DISCUSSION TITLE
Specify network in kube file

### DISCUSSION THREAD

**Discussion by imperialguy** [containers/podman#13854] [General]
Say I do the following:

`podman network create sample`
`podman pod create --name p1`
`podman run -d --rm -it --name c1 --pod p1 --network sample docker.io/alpine:latest`
`podman run -d --rm -it --name c2 --pod p1 --network sample docker.io/alpine:latest`
`podman generate kube p1`

Here's the yaml file it generates.

```
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-04-13T12:05:19Z"
  labels:
    app: p1
  name: p1
spec:
  containers:
  - image: docker.io/library/alpine:latest
    name: c1
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
  - image: docker.io/library/alpine:latest
    name: c2
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
  restartPolicy: Never
status: {}
```

The problem is the generated yaml file does not include the network name. How do I add the network name to the generated kube yaml file?
