### DISCUSSION TITLE
Should podman machine init create aarch64 VMs that cannot upgrade with rpm-ostree?

### DISCUSSION THREAD

**Discussion by UniversalSuperBox** [containers/podman#14875] [Q&A]
I'm running Podman on macOS aarch64. I have a project that can only be run on amd64 hosts, but I'd like to build images for it on my Mac.

Reading https://github.com/containers/podman/discussions/12899, I found that a new version of Fedora Core has qemu-user-static installed. Excited, I tried to use `podman machine init --image-path next` to try it out. Unfortunately, I still received an image from May:

```
[core@localhost ~]$ rpm-ostree status
State: idle
Deployments:
  fedora:fedora/aarch64/coreos/next-devel
                   Version: 36.20220511.dev.0 (2022-05-11T18:11:54Z)
                BaseCommit: c00f75f2a800ab3e83beff6b263e6a5474b5632de495e56ad22f22bf780ce588
                    Commit: 4a5bc6525935165c3cc08cf6d2eead98d3801642783623860cfec284bf934a08
              GPGSignature: (unsigned)
                      Diff: 1 removed
       RemovedBasePackages: moby-engine 20.10.14-1.fc36
```

(This is also the live commit)

It doesn't appear that this image can upgrade itself, either. I've tried running `sudo rpm-ostree update` but received an error:

```
[core@localhost ~]$ sudo rpm-ostree update
error: While pulling fedora/aarch64/coreos/next-devel: No such branch 'fedora/aarch64/coreos/next-devel' in repository summary
```

Checking out the Fedora CoreOS repository at https://d2uk5hbyrobdzx.cloudfront.net/refs/heads/fedora/aarch64/coreos/, this appears correct. `next-devel` does not appear in the heads listing. However, `next-devel` *does* appear at https://kojipkgs.fedoraproject.org/compose/ostree/repo/refs/heads/fedora/aarch64/coreos/.

I can get the image to update by running `sudo rpm-ostree rebase fedora:fedora/aarch64/coreos/next`, but I'm not sure if this is the correct way to perform this task.

It appears that using `podman machine init --image-path next` and `podman machine init --image-path testing` both have a similar effect, but they list a different Commit in their path. It's worth noting that neither of these options list an `AutomaticUpdateDriver` of Zincati in `rpm-ostree status` unlike the documentation at https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-updates/.

Finally, Zincati reports the following when it starts:

```
[WARN  zincati::update_agent::actor] initialization complete, auto-updates logic disabled by configuration
```

The VM doesn't appear to upgrade itself, even after a few hours of waiting. Should I be using something other than rpm-ostree to get the VM to upgrade?
