### DISCUSSION TITLE
How to include multiple hostAliases in yml file?

### DISCUSSION THREAD

**Discussion by NeilDavisNPS** [containers/podman#15386] [Q&A]
Hello,

I have the following snippet in a yml file:
```
hostAliases:
  - ip: "10.0.1.74"
    hostnames:
    - "mysql"
  - ip: "10.0.1.150"
    hostames:
    - "my.server.com"
```
When I run 
```
podman play kube compose.yml
```
the resulting container's host file is populated with only the first alias (mysql).
Is this expected?

Here's the podman version info
```podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.12
Built:        Thu Aug  4 00:36:19 2022
OS/Arch:      linux/amd64```

Cheers.
