### DISCUSSION TITLE
NPM, host and bridged network and real visitor IP

### DISCUSSION THREAD

**Discussion by Extarys** [containers/podman#15710] [Q&A]
Still trying to get real visitor IP from proxied container through NPM :/

**Original**
I'm trying to set up podman with NPM and Nextcloud. I'm having a hard time with podman or containers complaining about permissions but in the end it's a good thing... 

With nextcloud, when I get a 500 error the IP shown is the IP of a container (quite hard to find which IP belongs to which container without inspecting each one of them):
```
Technical details

    Remote Address: 10.89.1.26
```

One suggestion that came up online was to use NPM with `network_mode: host`, but podman complains because there is multiple networks in the compose file.

Am I trying to set this up wrong? I want the ease of using `container_name:port` inside NPM and not have to worry about internal IPs.

I already have to expose all the ports I want, I thought at first I could just to `ncweb:80` without exposing any ports to the host machine, but I guess this is a tradeoff of rootless and the ports need to be exposed.

```
version: "3.7"
services:
  npm:
    container_name: npm
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data:Z
      - /opt/secrets/letsencrypt:/etc/letsencrypt:Z
    network_mode: host

  # Based on https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm
  ncapp:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./nextcloud/html:/var/www/html:z
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    networks:
      - pod-local

  ncweb:
    build: ./nextcloud/web
    restart: always
    volumes:
      - ./nextcloud/html:/var/www/html:ro
    environment:
      #- VIRTUAL_HOST=
    networks:
      - pod-local

networks:
  pod-local:
    external: true
  pod-public:
    external: true
```

Error is `Error: cannot set multiple networks without bridge network mode, selected mode host: invalid argument`

I'm new to podman and I know it isn't a drop in replacement for docker, although it could be true if I'd run it 100% rootfull. The docs and people's suggestion for an issue are often times for a different version or with using a whole stack of softwares.

I'm thinking about running Yacht rootfull and simply give this a try, but that's the easy way out :joy: 

Thanks for your time.
