### DISCUSSION TITLE
What's alternative in pod .yaml to :z flag on directory?

### DISCUSSION THREAD

**Discussion by simonf-dev** [containers/podman#16196] [Q&A]
Hello, I want to bind the directory inside podman pod containers. When I try to bind it like this:

```
    - name: project-root
      hostPath:
        path: ../.
        type: Directory
...
      volumeMounts:
        - name: project-root
          mountPath: /project
```
I can't access it in the container. It doesn't work also with root privileges. When I turn off selinux on the system, then it works properly. With normal container command I can use ...:Z flag to get rid of this error, but I don't know how to handle it in the pod file.

**Comment by Luap99** [comment]
If I generate a yaml with podman generate kube I get:
```
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /path/on/host:Z
...
```
So I assume this also works with play kube.
