### DISCUSSION TITLE
Unable to pull large image after increasing `sub*ids`

### DISCUSSION THREAD

**Discussion by anthr76** [containers/podman#16335] [Q&A] [answered]
I am trying to simply to:

`podman pull gcr.io/cloud-foundation-cicd/cft/developer-tools:1.5`

A very large container image used for CI tooling and what not.

Though I receive the error:

```
Error: writing blob: adding layer with blob "sha256:6f50033c3110510b6743d82973822c39301376da074aaa9545960fd9064bcf97": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 806984:89939 for /build/terraform-validator): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /build/terraform-validator: invalid argument): exit status 1
```

So I increased my uids:

```
cat /etc/sub*id
user:300000:365536
user:300000:365536
```

That seems to have worked/take effect:

```
podman unshare cat /proc/self/uid_map
         0       1000          1
         1     300000     365536
podman unshare cat /proc/self/gid_map
         0       1000          1
         1     300000     365536

  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 300000
      size: 365536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 300000
      size: 365536
```

Though I'm still seeing this error. Any ideas?

I'm on `podman-4.2.1-2.fc37.x86_64`
