### DISCUSSION TITLE
How do I manually set the proxy on podman windows?

### DISCUSSION THREAD

**Discussion by tjaart** [containers/podman#16359] [Q&A]
The problem I am facing is that I use a proxy that runs locally on my machine, but when the proxy variables are passed into podman, the proxy host is seen as: 127.0.0.1 which is the wsl VM localhost and not my windows host.

- I have tried setting it via podman desktop, but this had no effect.
- I have tried setting it by changing the proxy env vars in the podman wsl machine, but this is overridden
- I tried setting up /etc/containers/containers.conf as follows and restarting with `podman machine stop` and then `podman machine start`:

```toml
[containers]
http_proxy=false

[engine]
cgroup_manager = "cgroupfs"
env = [ "http_proxy=http://host.docker.internal:3128", "https_proxy=http://host.docker.internal:3128"]
```

But nothing works.

When I call set in the wsl container I still get the same stuff back:
```
http_proxy=http://127.0.0.1:3128/
https_proxy=http://127.0.0.1:3128/
```

`podman.exe version 4.3.0`
