### DISCUSSION TITLE
Run as non-root user with CAP_CHOWN on bind mount directories

### DISCUSSION THREAD

**Discussion by wilee8** [containers/podman#16905] [Q&A] [answered]
We have a web interface that allows users to schedule batch jobs on a server, and it will chown files created so they are owned by the user that submitted the batch job. Right now it runs as a systemd service, and we have it set to run as a non-root user with CAP_CHOWN added to AmbientCapabilities so the service user can chown the files. 

We're trying to containerize all the services in the interface so it stops breaking when the admin updates the system, and I have the chown working fine in a container created as root and ran in Podman by root. However, I'm trying to set it to run as a non-root user (usually with the -u flag in podman run, although I've tried other things as well) with CAP_CHOWN capabilities to modify the owner of files in a bind mounted directory, but it always fails at the chown command with an "Operation not permitted" error. Tried running setcap commands when building the container in Buildah, tried --cap-add and --privileged flags when running in Podman, can't get it to work any time I try to make the user someone other than root. 

Is it possible to run the container as a non-root and give it CAP_CHOWN on bind-mounted directories? How would I need to configure this, both when building the container and when running it?

**Comment by rhatdan** [comment]
Can you give us a simple repeater to play with?

**Reply by rhatdan** [reply]
Also can you give us the exact podman command you are running?  Are you running the podman command as root with a --user XYZ option?  Or attempting to run a rootless container?

Finally give output of `podman info`

**Reply by wilee8** [reply]
- Uh, I don't know what you mean by a simple repeater, sorry. 
- Current command, but I've changed it around many times without anything working:
```
podman run -d -v /opt/web-server:/ws_mount/:Z \
  --security-opt label=disable -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro --name django --pod ws --cap-add=cap_chown \
  --user=apache:apache localhost/django 8001
```
- I'm running the podman command as root. I started trying with the --user flag, but I've also tried running it without the --user flag and changing the user in the entrypoint - that doesn't work either. 
- Podman info:
```
# podman info
host:
  BuildahVersion: 1.11.7
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.el7_8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 372b4a12f1c2df4f70c280d41173b60acd3f1260'
  Distribution:
    distribution: '"rhel"'
    version: "7.9"
  MemFree: 965128192
  MemTotal: 16655740928
  OCIRuntime:
    name: runc
    package: runc-1.0.0-69.rc10.el7_9.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 7423127552
  SwapTotal: 8455712768
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: dev02.myhost.com
  kernel: 3.10.0-1160.49.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 7848h 15m 39.67s (Approximately 327.00 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 8
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 7
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```
