### DISCUSSION TITLE
Use yaml file's parent  as the working directory for `podman kube play`

### DISCUSSION THREAD

**Discussion by abalmos** [containers/podman#17177] [General]
I was hoping to use `podman kube play` and the systemd `podman-kube@.service` to replace existing docker-compose setups. Generally, we put all needed resources (config files, data volume mounts, etc.) into one folder. Then, with compose, one can refer to them using relative paths from the YAML file. As a result, the parent folder is somewhat portable--in the sense that one can move it and `docker-compose up` still does the right thing.

With `podman kube play` relative paths work, but they are relative to `podman`'s current working directory, not the location of the yaml file being played. This renders `podman-kube@.service` hard to use because the current working directory is not the parent folder of the yaml file being started. Therefore, all paths need to made absolute and now the "service folder" must know about where it lives on a particular machine.

Is it currently possible to make `podman` use the parent directory of the yaml as the current working directory? If not, perhaps that could at least be a cli flag, if not the default behavior?

**Comment by rhatdan** [comment]
@ygalblum @umohnani8 @haircommander WDYT?

**Reply by haircommander** [reply]
a flag makes sense to me

**Reply by ygalblum** [reply]
The request makes a lot of sense. In Quadlet for example, all relative paths are relative to the location of the `.container` or `.kube` files in order to allow the same portability that @abalmos referred to.
As for the CLI flag, just to make sure I understand, `podman-kube@.service` will set this flag by default?

**Reply by umohnani8** [reply]
A flag makes sense to me as well - we will default to the current working directory of podman if this flag is not set. I will work on this next week.

**Reply by abalmos** [reply]
I suppose setting the flag in `podman-kube@.service` is a breaking change, but one I personally feel would be worth it.

I'm not sure how podman handles breaking changes in terms of release cycle, but I hate to see the flag delayed because of `podman-kube@.service`. In the meantime, the flag is enough to manually override `podman-kube@.service`.

**Comment by abalmos** [comment]
I feel like this should also apply to the `Volume=` directive of Quadlet too. Similar to `EnvironmentFile=`, `Yaml=`, and `ConfigMap=`'s treatment.

**Reply by ygalblum** [reply]
I've opened a separate ticket #17418 to discuss this further

**Comment by Epokhe** [comment]
Any updates on this? I am using a custom .service file with `WorkingDirectory` set to yaml's parent folder to work around this. I would rather be able to use podman's systemd generator or quadlet.

**Comment by ygalblum** [comment]
@Epokhe While my name does appear in this discussion, I'm not sure why I separated parts of it to #17418 which was resolved already.

So, currently, Qualdet does support relative paths (relative to the location of the quadlet unit file). In addition, once #18830 is merged, you will be able to put the files of each unit in a separate directory.

Will this fulfill your requirements, or do you see further needs?

**Reply by Epokhe** [reply]
From my testing, I think quadlet supports relative locations for the configuration options it itself accepts, but it doesn't have an effect on the fields inside the kube yaml. Correct me if I'm wrong. In this case, it's a different thing than what I'm asking for. 

File structure I and OP are talking about
```
project_folder
    kube.yaml
    app1_folder
        app1.conf
```

Inside kube.yaml, I want to be able to do
```
volumes:
    - hostPath:
        path: ./app1_folder/app1.conf
        type: File
      name: app1-config
```

and `./app1_folder/app1.conf` gets resolved relative to `kube.yaml`.

**Reply by ygalblum** [reply]
Yes you are correct with your analysis. But, I don't think that this is a Quadlet specific issue, but a `podman kube play` one. IIUC Podman resolves the path relative to ${PWD}. For example, I ran `podman kube play` with the following YAML file:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: ./data
      # this field is optional
      type: DirectoryOrCreate
```
The directory `data` was created inside the directory I was, regardless to where the YAML file was.

So, in order to address this, I think we'll need a new flag to `podman kube play` overriding the base path it used to resolve relative paths.

@rhatdan @umohnani8 WDYT?
