### DISCUSSION TITLE
Store and run containers and VM from an external drive

### DISCUSSION THREAD

**Discussion by anarchy89** [containers/podman#18186] [General]
### Feature request description

Is it possible to store and run podman containers and VM from an external drive on mac m1? I only have 256gb of storage and use an external APFS SSD.

### Suggest potential solution

Either to be able to create a symlink to a folder in an external drive, or change a variable in the program to do it.

### Have you considered any alternatives?

Just symlinking but not sure what or if it's possible.

**Comment by github-actions** [comment]
A friendly reminder that this issue had no activity for 30 days.

**Comment by rhatdan** [comment]
You should be able to configure containers.conf to setup the storage drive to be volume mounted into the container.
@baude @ashley-cui Please confirm

**Comment by anarchy89** [comment]
@rhatdan any updates?

**Comment by rhatdan** [comment]
In containers.conf on the MAC, you should see


# Host directories to be mounted as volumes into the VM by default.
# Environment variables like $HOME as well as complete paths are supported for
# the source and destination. An optional third field `:ro` can be used to
# tell the container engines to mount the volume readonly.
#
#volumes = [
#  "$HOME:$HOME",
#]

You can extend this file to modify the volumes line to include volumes outside of $HOME into the VM, and then these could be used by the container.

**Comment by anarchy89** [comment]
i cant find the storage.conf file in macos.

https://github.com/containers/podman/blob/main/vendor/github.com/containers/storage/storage.conf

the containers.conf file has no volumes section. not sure what you mean.

**Reply by kolonelkrazy** [reply]
###### rootless (running under specific file)
run `podman info`, under storage section you'll see the needed information including the storage.conf file

###### rootfull
same deal, but it will show you the info for the root account

```yaml
store:
  configFile: /home/kolonelkrazy/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/kolonelkrazy/.local/share/containers/storage
  graphRootAllocated: 
  graphRootUsed: 
  graphStatus:
    Backing Filesystem: 
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 236
  runRoot: /run/user/3056/containers
  transientStore: false
  volumePath: /home/kolonelkrazy/.local/share/containers/storage/volumes
```
