### DISCUSSION TITLE
Why am I getting `Error: invalid reference format` when running `podman kube play` on my YAML file?

### DISCUSSION THREAD

**Discussion by poperigby** [containers/podman#18594] [Q&A] [answered]
I've got this Kubernetes YAML file:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nextcloud-pod
  name: nextcloud-pod
spec:
  hostname: nextcloud-pod
  securityContext:
    seLinuxOptions:
      type: spc_t
  containers:
  - name: nextcloud
    image: docker.io/_/nextcloud:fpm
    volumeMounts:
      - name: "nextcloud-data"
        mountPath: "/var/www/html"
    environment:
    - name: NEXTCLOUD_ADMIN_USER
      value: admin
    - name: NEXTCLOUD_ADMIN_PASSWORD
      value: REDACTED
    - name: NEXTCLOUD_TRUSTED_DOMAINS
      value: REDACTED
    - name: TRUSTED_PROXIES
      value: caddy 172.18.0.4
    - name: OVERWRITEPROTOCOL
      value: https
    - name: PHP_MEMORY_LIMIT
      value: 512M
    - name: PHP_UPLOAD_LIMIT
      value: 4048M
    - name: SMTP_HOST
      value: smtp.sendgrid.net
    - name: SMTP_SECURE
      value: tls
    - name: SMTP_PORT
      value: "587"
    - name: SMTP_NAME
      value: apikey
    - name: SMTP_PASSWORD
      value: "REDACTED"
    - name: MYSQL_DATABASE
      value: nextcloud
    - name: MYSQL_USER
      value: nextcloud
    - name: MYSQL_PASSWORD
      value: REDACTED
    - name: MYSQL_HOST
      value: db
    - name: REDIS_HOST
      value: redis
  - name: db
    image: docker.io/_/mariadb:10.6
    args: [
      "--transaction-isolation=READ-COMMITTED",
      "--log-bin=binlog",
      "--binlog-format=ROW" ]
    volumeMounts:
      - name: "nextcloud-db"
        mountPath: "/var/lib/mysql"
    environment:
      - name: MYSQL_DATABASE
        value: nextcloud
      - name: MYSQL_USER
        value: nextcloud
      - name: MYSQL_PASSWORD
        value: REDACTED
      - name: MYSQL_ROOT_PASSWORD
        value: REDACTED
  - name: redis
    image: docker.io/_/redis:alpine
    volumeMounts:
      - name: "nextcloud-redis"
        mountPath: "/data"
  - name: cron
    image: nextcloud:apache
    command: [/cron.sh]
    volumeMounts:
      - name: "nextcloud-data"
        mountPath: "/var/www/html"
  volumes:
  - name: "nextcloud-data"
    persistentVolumeClaim:
      claimName: "nextcloud-data"
  - name: "nextcloud-db"
    persistentVolumeClaim:
      claimName: "nextcloud-db"
  - name: "nextcloud-redis"
    persistentVolumeClaim:
      claimName: "nextcloud-redis"
```

Every time I try to run `podman kube play service.yaml` it says:

```
Error: invalid reference format
```

That's not a particularly helpful error message. I looked it up, and couldn't find anything relevant. I was assuming it meant there's something up with my YAML file, but I ran it through a linter, and it had no complaints.
