### DISCUSSION TITLE
Trouble with `podman kube play` and `ConfigMap`

### DISCUSSION THREAD

**Discussion by poperigby** [containers/podman#18967] [Q&A] [answered]
I'm trying to get Inadyn (dynamic DNS client) setup with `podman kube play`. This is my YAML file:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: indadyn-pod
spec:
  hostname: inadyn-pod
  securityContext:
    seLinuxOptions:
      type: spc_t
  containers:
    - name: inadyn
      image: docker.io/troglobit/inadyn:latest
      volumeMounts:
        - name: inadyn-config
          mountPath: /etc
  volumes:
    - name: inadyn-config
      configMap:
        name: inadyn-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inadyn-config
  data:
    inadyn.conf: |
      period          = 300
      user-agent      = Mozilla/5.0

      provider cloudflare.com {
          username = zone.name
          password = REDACTED
          hostname = hostname.zone.name
          ttl      = 1
          proxied  = false
      }
```

My problem is, it's saying that the config file can't be found.

```
inadyn[1]: Cannot read configuration file /etc/inadyn.conf

inadyn[1]: Error code 74: Missing .conf file
```

I looked in the `inadyn-config` volume, and `inadyn.conf` indeed isn't in there. I think it was working before, but then I deleted the `inadyn-config` volume for some troubleshooting reason that I can't remember now.

**Comment by rhatdan** [comment]
Can you remove the inadyn-config volume and start again?

**Reply by poperigby** [reply]
I tried doing that, but it unfortunately didn't fix it.

**Comment by rhatdan** [comment]
@Luap99 @umohnani8 PTAL

**Comment by poperigby** [comment]
@Luap99 @umohnani8 Sorry to bother you, but I was still having this issue. I'm pretty stumped at this point.

**Comment by dfr** [comment]
I think you might need to use subPath - change the mountPath to /etc/inadyn.conf and add 'subPath: inadyn.conf'. Here is an example I've been using for testing kube play on FreeBSD - adjust the paths and image name to try it on Linux.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-data
  labels:
    app: hello-world
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Hello World!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Hello World!</h1>
    <p>If you see this page, the hello world service is working.</p>
    </body>
    </html>
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      server {
        listen       80;
        server_name  localhost;
        root /hello/html;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-24T07:51:37Z"
  labels:
    app: hello-world-pod
  name: hello-world-pod
spec:
  containers:
  - image: quay.io/dougrabson/nginx:latest
    name: hello-world
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - name: config
      mountPath: /usr/local/etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: data
      mountPath: /hello/html/index.html
      subPath: index.html
  restartPolicy: Always
  volumes:
  - name: data
    configMap:
      name: hello-data
  - name: config
    configMap:
      name: hello-data
      defaultMode: 0644
```

**Reply by poperigby** [reply]
Thank you for your help. I tried using `subPath`, but now I'm getting this confusing error:

```
[starting container aabac1bc2209b852f8bd1de24c1a5b8351256f53997ef33949e466a5d91d19d0: no such file or directory]
Pod:
25336882dc8adb0a3feb2fee09b760d0db8da3ff44f11003873630404620fb01
Container:
aabac1bc2209b852f8bd1de24c1a5b8351256f53997ef33949e466a5d91d19d0

starting container aabac1bc2209b852f8bd1de24c1a5b8351256f53997ef33949e466a5d91d19d0: no such file or directory

Error: failed to start 1 containers
```

This is my updated YAML:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: indadyn-pod
spec:
  hostname: inadyn-pod
  securityContext:
    seLinuxOptions:
      type: spc_t
  containers:
    - name: inadyn
      image: docker.io/troglobit/inadyn:latest
      volumeMounts:
        - name: inadyn-config
          mountPath: /etc/inadyn.conf
          subPath: inadyn.conf
  volumes:
    - name: inadyn-config
      configMap:
        name: inadyn-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inadyn-config
  data:
    inadyn.conf: |
      period          = 300
      user-agent      = Mozilla/5.0

      provider cloudflare.com {
          username = REDACTED
          password = REDACTED
          hostname = REDACTED
          ttl      = 1
          proxied  = false
      }
```

**Comment by dfr** [comment]
The data section of the ConfigMap should not be indented - it should be at
the same level as the metadata section.

**Reply by poperigby** [reply]
Thank you. Now it's saying this:

```
[starting container 83fcc3758eaa07b24e7f849218f150e3c249c007dc66424725e23cf950b502c2: subpath "inadyn.conf" is outside of the volume "/home/cassidy/.local/share/containers/storage/volumes/inadyn-config/_data"]
Pod:
adc385b751500742f9564a4223b44ea80e07d23a50759130d545d0ba7fec0ae6
Container:
83fcc3758eaa07b24e7f849218f150e3c249c007dc66424725e23cf950b502c2

starting container 83fcc3758eaa07b24e7f849218f150e3c249c007dc66424725e23cf950b502c2: subpath "inadyn.conf" is outside of the volume "/home/cassidy/.local/share/containers/storage/volumes/inadyn-config/_data"

Error: failed to start 1 containers
```

Updated YAML again:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: indadyn-pod
spec:
  hostname: inadyn-pod
  securityContext:
    seLinuxOptions:
      type: spc_t
  containers:
    - name: inadyn
      image: docker.io/troglobit/inadyn:latest
      volumeMounts:
        - name: inadyn-config
          mountPath: /etc/inadyn.conf
          subPath: inadyn.conf
  volumes:
    - name: inadyn-config
      configMap:
        name: inadyn-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inadyn-config
data:
  inadyn.conf: |
    period          = 300
    user-agent      = Mozilla/5.0

    provider cloudflare.com {
        username = haddock.cc
        password = REDACTED
        hostname = haddock.cc
        ttl        = 1
        proxied  = false
    }
```
