### DISCUSSION TITLE
Wordking container not working with quadlet

### DISCUSSION THREAD

**Discussion by mvuidev** [containers/podman#19157] [Q&A]
Hello,

I'm running a container based on https://github.com/TrafeX/docker-php-nginx and all is working fine with "podman play kube".
But when using quadlet, the container remains unhealthy and i can't reach nginx.

My test.yaml file : 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: OnFailure
  containers:
    - name: container
      image: trafex/php-nginx
      livenessProbe:
        httpGet:
          port: 8080
          path: /fpm-ping
        initialDelaySeconds: 5
        periodSeconds: 5
      ports:
        - name: test
          hostPort: 8001
          containerPort: 8080
          protocol: TCP
```

My test.kube file : 

```
[Install]
WantedBy=default.target

[Unit]

[Kube]
Yaml=test.yaml
```

Files are placed in ~/.config/containers/systemd
Then : 

```bash
systemctl --user daemon-reload
systemctl --user start test
```

Did i forget something ? Any idea ?

Podman version : 4.4.1
OS : Rocky Linux 9
