### DISCUSSION TITLE
Issues with Podman reporting about ports being bound when they aren't?

### DISCUSSION THREAD

**Discussion by telometto** [containers/podman#19519] [Q&A]
I've been having major issues trying to run AdGuard Home on my home server (Ubuntu 23.04 Server). Specifically, I've been going nuts trying to get the `docker-compose.yml` I've created to work.

After installing everything related to Podman from the official Ubuntu repos (`podman`, `podman-compose`, and `podman-docker`), and trying to spin up the container using `sudo podman-compose up -d`, it has been complaining about various ports all the time... port 53, 67, 68. Even after [following the instructions from their official Docker Hub](https://hub.docker.com/r/adguard/adguardhome#resolved-daemon) and checking that the port is available using `sudo lsof -i :53`, it _still_ told me that port 53 is bound.  I've basically crossed Heaven to Hell these last few days before it occurred to me that it might be a bug or something within `podman` itself - can someone confirm this? Running the _**exact same script using**_ `docker-compose` _**worked just fine**_.

Here's the script:
```yml
version: "3.4"
services:
  adguardhome:
    image: "adguard/adguardhome"
    container_name: "adguardhome"
    restart: "unless-stopped" # podman-compose ignores this, but I removed it when I ran it using podman-compose
    cap_add:
      - "NET_ADMIN"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      #- "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "784:784/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - "./work:/opt/adguardhome/work"
      - "./conf:/opt/adguardhome/conf"
```
