### DISCUSSION TITLE
nginx as proxy

### DISCUSSION THREAD

**Discussion by yosiasz** [containers/podman#19569] [General]
greetings 

With the following compose file
```
# Use root/example as user/password credentials
version: "3.1"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    ports:
      - 8080:80
    volumes:
      - "./conf_nginx/default.conf:/etc/nginx/nginx.conf"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    volumes:
      - ./conf_grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
    ports:
      - 5000:3000
```

and this nginx conf
```
events {
    worker_connections 1024;
}

http {
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }
    upstream grafana {
        server DYNAMIC_IP_ADDRESS_OF_GRAFANA:3000;
    }
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html index.htm;
        location / {
            proxy_set_header Host $http_host;
            proxy_pass http://grafana;

        }
    }
}
```
What do I need to do so that ngnix sees/knows DYNAMIC_IP_ADDRESS_OF_GRAFANA? All works when I update it manually by seeing what the ip address of grafana is in `etc/hosts` but need to make it dynamic?

Thanks!
