### DISCUSSION TITLE
Help setting up In-a-dyn with ConfigMap

### DISCUSSION THREAD

**Discussion by poperigby** [containers/podman#19786] [Q&A]
I've been trying to setup [In-a-dyn](https://github.com/troglobit/inadyn) (dynamic DNS client), using a ConfigMap for it's configuration file. 

So far, I've run into an issue where In-a-dyn spits out this error `input in flex scanner failed`. This is what the maintainer said about it:

> That's very odd. The error comes from flex, which is the LALR parser used in libConfuse, which In-a-Dyn in turn use to parse configuration files. I have never seen this before.

So, I'm guessing something weird is going on with my ConfigMap setup.

This is my YAML file:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: indadyn-pod
spec:
  hostname: inadyn-pod
  securityContext:
    seLinuxOptions:
      type: spc_t
  containers:
    - name: inadyn
      image: docker.io/troglobit/inadyn:latest
      volumeMounts:
        - name: inadyn-config
          mountPath: /etc/inadyn.conf
  volumes:
    - name: inadyn-config
      configMap:
        name: inadyn-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inadyn-config
data:
  inadyn.conf: |
    period          = 300
    user-agent      = Mozilla/5.0

    provider cloudflare.com {
        username = REDACTED
        password = REDACTED
        hostname = REDACTED
        ttl        = 1
        proxied  = false
    }
```

I'm using Podman 4.6.0.
