### DISCUSSION TITLE
Wrong permissions when using rootless

### DISCUSSION THREAD

**Discussion by francoism90** [containers/podman#20097] [Q&A]
After upgrading to Fedora 39 RC, I'm getting wrong permissions on directories:
```
drwxr-xr-x. 1   100999   100999   82 20 aug 16:22 data
```
1000999 should be my username.

Is this a known issue?

I'm using this inside `docker-compose.yml`:
```
app:
    build:
      context: ./build/app
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./src:/src:rw,z,U
      - ./data:/data:rw,z,U
    x-podman:
      uidmaps:
        - "0:1:1"
        - "${UID:-1000}:0:1"
      gidmaps:
        - "0:1:1"
        - "${GID:-1000}:0:1"
 ```
Thanks
