### DISCUSSION TITLE
How can I stop podman from passing proxy envs to containers?

### DISCUSSION THREAD

**Discussion by ChuJiani** [containers/podman#20118] [Q&A] [answered]
I got to know that podman will automatically pass the proxy variables (like `http_proxy`) to containers when they are created and started, but this caused some problems.

For example, I have proxy server run at port `1234` on my host machine, and exported the variables on my host machine as `http_proxy=http://127.0.0.1:1234` and `https_proxy=http://127.0.0.1:1234`, then I ran one simple image (not in `--net host` mode), and podman will also set the proxy variables as above in the container. However, the programs in the container(like wget) would fail when request some resources from the internet, because it will try to connect the proxy first but find no proxy at port `1234` in the container.

**Comment by ChuJiani** [comment]
I found that I can do this by adding `--http-proxy=false` when starting a container, but `podman-compose` still misses this feature, maybe I should talk about this under `podman-compose`'s repo, not here.

**Reply by rhatdan** [reply, marked as answer]
You can set this in containers.conf file to not do it for all containers.

**Reply by ChuJiani** [reply]
ok, thanks! :)

**Reply by Gr3at** [reply]
Just to add a bit more clarity (+ context) to the answer.
Herre is an example [containers.conf](https://github.com/containers/common/blob/main/pkg/config/containers.conf) file for reference.
And [here ](https://podman-desktop.io/docs/proxy#using-a-proxy) you can see how to set env vars in the file.

Following a configuration i use for podman behind a company proxy.
```toml
[containers]
# container level configuration
env = [
'http_proxy=<company.proxy.url:port>',
'https_proxy=<company.proxy.url:port>',
'no_proxy=localhost,127.0.0.1,.<your-company.internal.network>',
]

[engine]
# podman level configuration
env = [
'http_proxy=<company.proxy.url:port>',
'https_proxy=<company.proxy.url:port>',
'no_proxy=localhost,127.0.0.1,.<your-company.internal.network>',
]

[machine]

[network]

[secrets]

[configmaps]

```
