### DISCUSSION TITLE
.kube does not shutdown PostgreSQL gracefully

### DISCUSSION THREAD

**Discussion by ChristophHannappel** [containers/podman#21389] [Q&A]
Hello,

i configured a Pod to user Paperless NGX which uses the postgreSQL Container, than created a Kube.yaml and setup a systemd.kube file to run it.
When stopping with `systemctl --user restart PaperlessNGX.service` the postgreSQL Container gets shutdown to soon and on the next start it reports
```
2024-01-26 19:21:28.819 UTC [23] LOG:  database system was interrupted; last known up at 2024-01-26 19:19:39 UTC
2024-01-26 19:21:29.015 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
```

When stopping the pod with `podman pod stop PaperlessNgx` it reports a happy shutdown.
Does anyone have an idea how to make it stop gracefully :)
I'm running podman 4.8.2 on Fedore Core OS.

My PaperlessNGX.kube
```
[Unit]
Description=PaperlessNGX

[Kube]
AutoUpdate=registry
PublishPort=8080:80
Yaml=/var/home/core/PaperlessNgx.yaml


[Service]
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target default.target
``` 
My PaperlessNgx.yaml
```yaml
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-13T15:24:31Z"
  labels:
    app: PaperlessNgx
  name: PaperlessNgx
spec:
  containers:
  - args:
    - redis-server
    image: docker.io/library/redis:7
    name: PaperlessNgx-redis
    ports:
    - containerPort: 2022
      hostPort: 2022
    - containerPort: 8000
      hostPort: 8000
    - containerPort: 8022
      hostPort: 8022
    volumeMounts:
    - mountPath: /data
      name: PaperlessNgx-redis-data-pvc
  - args:
    - postgres
    env:
    - name: POSTGRES_DB
      value: paperless
    - name: POSTGRES_PASSWORD
      value: PostgresPassword
    - name: POSTGRES_USER
      value: paperless
    image: docker.io/library/postgres:15
    name: PaperlessNgx-postgres
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: PaperlessNgx-postgres-data-pvc
  - args:
    - gotenberg
    - --chromium-disable-javascript=true
    - --chromium-allow-list=file:///tmp/.*
    image: docker.io/gotenberg/gotenberg:7.10
    name: PaperlessNgx-gotenberg
    securityContext: {}
  - image: ghcr.io/paperless-ngx/tika:latest
    name: PaperlessNgx-tika
    securityContext: {}
  - args:
    - /usr/local/bin/paperless_cmd.sh
    env:
    - name: PAPERLESS_SECRET_KEY
      value: SueprSecretPassword
    - name: PAPERLESS_TIME_ZONE
      value: Europe/Berlin
    - name: PAPERLESS_TIKA_ENABLED
      value: "1"
    - name: PAPERLESS_REDIS
      value: redis://127.0.0.1:6379
    - name: PAPERLESS_OCR_LANGUAGES
      value: deu eng
    - name: PAPERLESS_DBHOST
      value: 127.0.0.1
    - name: PAPERLESS_URL
      value: https://paperless.domain.test
    - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
      value: http:127.0.0.1:3000
    - name: PAPERLESS_TIKA_ENDPOINT
      value: http://127.0.0.1:9998
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    name: PaperlessNgx-webserver
    volumeMounts:
    - mountPath: /usr/src/paperless/data
      name: PaperlessNgx-webserver-data-pvc
    - mountPath: /usr/src/paperless/export
      name: PaperlessNgx-webserver-export-pvc
    - mountPath: /usr/src/paperless/media
      name: PaperlessNgx-webserver-media-pvc
    - mountPath: /usr/src/paperless/consume
      name: PaperlessNgx-webserver-consume-pvc
  - env:
    - name: SFTPGO_DEFAULT_ADMIN_USERNAME
      value: sftpadmin
    - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
      value: GreatPassword
    - name: SFTPGO_HTTPD__BINDINGS__0__PORT
      value: "8022"
    - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
      value: "1"
    image: ghcr.io/drakkan/sftpgo:latest
    name: PaperlessNgx-sftpgo
    securityContext: {}
    volumeMounts:
    - mountPath: /var/lib/sftpgo
      name: PaperlessNgx-sftpgo-pvc
    - mountPath: /opt/paperless/consume
      name: PaperlessNgx-webserver-consume-pvc
  terminationGracePeriodSeconds: 120
  volumes:
  - name: PaperlessNgx-webserver-consume-pvc
    persistentVolumeClaim:
      claimName: PaperlessNgx-webserver-consume
  - name: PaperlessNgx-sftpgo-pvc
    persistentVolumeClaim:
      claimName: PaperlessNgx-sftpgo
  - name: PaperlessNgx-redis-data-pvc
    persistentVolumeClaim:
      claimName: PaperlessNgx-redis-data
  - name: PaperlessNgx-postgres-data-pvc
    persistentVolumeClaim:
      claimName: PaperlessNgx-postgres-data
  - name: PaperlessNgx-webserver-data-pvc
    persistentVolumeClaim:
      claimName: PaperlessNgx-webserver-data
  - name: PaperlessNgx-webserver-export-pvc
    persistentVolumeClaim:
      claimName: PaperlessNgx-webserver-export
  - name: PaperlessNgx-webserver-media-pvc
    persistentVolumeClaim:
      claimName: PaperlessNgx-webserver-media

```
