### DISCUSSION TITLE
Programatically creating a Quadlet and activating it with systemctl daemon-reload / start?

### DISCUSSION THREAD

**Discussion by torntrousers** [containers/podman#21435] [Q&A]
Hello, how could i go about creating a Quadlet and activating it by calling ```systemctl --user daemon-reload``` and ```systemctl --user start``` programtically, and ideally having that code running in a container? Easy enough to mount a ```~/.config/containers/systemd/``` volume to the container to write the .container file to, but how could i call ```systemctl``` and get it to apply to the host not the container?

**Comment by eriksjolund** [comment]
__Disclaimer:__ Untested idea. 

Maybe combining

* systemd user path unit with `DirectoryNotEmpty=` ([man page](https://www.freedesktop.org/software/systemd/man/latest/systemd.path.html#PathExists=))
* systemd user service (`Type=oneshot`)

 could work? 

On the host set up a systemd user path unit with

`DirectoryNotEmpty=/home/test/.config/containers/foobar.watch`

Let the path unit trigger a systemd user service (`Type=oneshot`) that 
moves the new file to _/home/test/containers/systemd/_ and then runs
`systemctl --user daemon-reload`

Podman command to run the quadlet creator container
```
podman run --rm --security-opt label=disable -v ~/.config/containers:/containers IMG
```
The container writes a quadlet file to


_/containers/foobar.tmp/my.container_

and then renames the file

```
mv /containers/foobar.tmp/my.container /containers/foobar.watch/my.container
```
(I guess it's good practice to use `mv` so that the file is added to the directory _foobar.watch_ with an automatic operation)

Maybe `--security-opt label=disable`  is not needed. If possible remove that option and add the volume option `:Z`

**Reply by torntrousers** [reply]
Thanks @eriksjolund might give that approach a try

**Comment by ygalblum** [comment]
I usually use Ansible for this. For example, the demo described in this [blog post](https://www.redhat.com/sysadmin/multi-container-application-podman-quadlet) can be provisioned using this [playbook.yml](https://github.com/ygalblum/quadlet-demo/blob/main/playbook.yml)

**Reply by torntrousers** [reply]
Thanks @ygalblum . I had seen that blog post. Its a lot though to understand all properly. How would something simpler work, like the single container from here https://github.com/containers/podman/discussions/21401#discussioncomment-8302650?

**Reply by ygalblum** [reply]
The Ansible Playbook should be something like this:
```
- name: Setup Quadlet
  hosts: all
  vars: 
    quadlet_dir: "{{ ansible_user_dir }}/.config/containers/systemd/"
    container_file_path: "< Path to rpiblink.container >"
    service_name: rpiblink
  tasks:
  - name: Install packages
    become: true
    ansible.builtin.package:
      name:
      - podman

  - name: Create the Quadlet directory
    ansible.builtin.file:
      path: "{{ quadlet_dir }}"
      state: directory
      mode: '0755'
      recurse: true

  - name: Copy the Quadlet files
    ansible.builtin.copy:
      src: "{{ container_file_path }}"
      dest: "{{ quadlet_dir }}"
      owner: root
      group: root
      mode: '0644'

  - name: Run daemon reload to make Quadlet create the service files
    ansible.builtin.systemd:
      daemon_reload: true
      scope: user

  - name: "Starting the service"
    ansible.builtin.systemd_service:
      state: started
      scope: user
      name: "{{ service_name }}.service"
    async: 1800
    poll: 60
```
