### DISCUSSION TITLE
Podman play kube  envFrom doesn't seem to work

### DISCUSSION THREAD

**Discussion by afro-coder** [containers/podman#21503] [General]
Hey folks has anyone recently tried loading from configmaps or secrets.

I've been trying it by creating a configMap or a secret but none of those loaded the secrets inside the container.

I'm probably doing something wrong but what's the correct way to load 20 env vars at once?
https://docs.podman.io/en/v4.2/markdown/podman-play-kube.1.html

```
apiVersion: v1
data:
  .env: |
    # Database / Postgres service configuration
    POSTGRES_USER=peertube
    POSTGRES_PASSWORD="peer"
    # Postgres database name "peertube"
    POSTGRES_DB=peertube_db
    #--- trimmed--#
kind: ConfigMap
metadata:
  name: envars
---
apiVersion: v1
kind: Pod
metadata:
  name: peertube-compose
  labels:
    purpose: streaming.
spec:
  containers:
  - name: redis
    image: docker.io/redis:6-alpine
    volumeMounts:
    - name: redis-storage
      mountPath: /data/
    envFrom:
    - configMapRef:
      name: envars
      key: .env
      optional: false
  volumes:
    - name: redis-storage
      hostPath:
        path: /tmp/docker-volume/redis/
        type: Directory
```

```
podman exec -it 5fbf4e8f36e3 ash
/data # ls
/data # env
SHLVL=1
REDIS_DOWNLOAD_SHA=34e74856cbd66fdb3a684fb349d93961d8c7aa668b06f81fd93ff267d09bc277
HOME=/root
container=podman
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-6.2.14.tar.gz
REDIS_VERSION=6.2.14
GOSU_VERSION=1.17
PWD=/data
/data #
```
