### DISCUSSION TITLE
Why do I get `failed: open /etc/containers/seccomp.json` ? [rootless podman with Gitlab runner]

### DISCUSSION THREAD

**Discussion by gabyx** [containers/podman#21733] [Q&A]
I am using the following https://gitlab.com/qontainers/pipglr
image to have a Gitlab runner which uses podman. I instructed the Gitlab runner to always mount the `/home/runner/podman.sock:/var/run/docker.sock:rw` to all job containers such that I can use `podman --remote`.

In my CI so far I have a Job:

```yaml
podman-remote-run&build:
  image: quay.io/podman/stable:latest
  variables:
    CONTAINER_HOST: unix://var/run/docker.sock
  script:
    - podman info
    - podman run alpine:latest cat /etc/os-release
    - cd tests && podman build -t test:test -f Dockerfile .
```
**which builds and runs images remotely** (it works) due to using `CONTAINER_HOST` (over container `pipglr` which is running on my NixOS host system (also with podman))

I dont understand what happens when I switch to my own alpine image with the following slight modification (I basically want to build my own container with podman in it):

```yaml
podman-remote-alpine-run&build:
  image: alpine:latest
  variables:
    CONTAINER_HOST: unix://var/run/docker.sock
  script:
    - apk add podman
    - podman info
    - podman run alpine:latest cat /etc/os-release
    - cd tests && podman build -t test:test -f Dockerfile .
```

The Dockerfile can be as simple as:

```dockerfile
FROM alpine:latest
RUN apk add git 
```

Now I get the error:

```shell
$ cd tests && podman build --no-cache -t test:test -f Dockerfile2 .
STEP 1/12: FROM alpine:3.18 AS githooks-docs-base
STEP 2/12: LABEL name=githooks-docs
--> 45e54b034c7b
STEP 3/12: RUN apk add git
Error: building at STEP "RUN apk add git": opening seccomp profile failed: open /etc/containers/seccomp.json: no such file or directory
```

I really dont understand where this error comes from and how to resolve it. Does it come from my host `pipglr` or is this error due to some missing files when building the image (I need to install some more stuff?).

Thanks a lot for all hints and explanations whats happening.
