### DISCUSSION TITLE
Using inline docker file with podman compose

### DISCUSSION THREAD

**Discussion by kameshsampath** [containers/podman#22223] [Q&A]
When I use a inline Dockerfile with a sample compose file, I see the they are not recogonised.  The podman is using a Dockerfile from the same directory if-any and builds it. Is the intentional or bug ? If a bug happy to raise an issue for the same.

```yaml
version: "3.7"
name: example
networks:
    _network:
        driver: bridge
volumes:
    mongodb-data-cni: null
    mongodb-data-containers: null 
services:
    mongo:
        build:
            dockerfile_inline: |
                FROM mongodb/atlas
                COPY ./bin/mongo_entrypoint.sh /entrypoint.sh
        # image: mongodb/atlas
        privileged: true
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        env_file:
            - .env
        command: /entrypoint.sh
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - mongodb-data-cni:/etc/cni
            - mongodb-data-containers:/var/lib/containers
        ports:
            - ${ATLAS_PORT}:${ATLAS_PORT}
        networks:
            - _network
```
