### DISCUSSION TITLE
`IPAM error: failed to find free IP in range`

### DISCUSSION THREAD

**Discussion by scy** [containers/podman#22440] [Q&A]
I got into a situation that sounds a lot like #18615. For some reason, maybe because of a continuously restarting container, I seem to have run out of IP addresses:

```
podman start -a paperless_webserver_1
Error: unable to start container 3f218956718559c4626e6426b41025cd40953b5fb12915932c9e9b4af8bf9c07: IPAM error: failed to find free IP in range: 10.89.0.1 - 10.89.0.254
exit code: 125
```

(I'm using podman-compose to start paperless-ngx.)

`ls -l /run/user/1000/netns/netns-*` shows 257 empty files named like `netns-ff176f26-1f2e-edc4-3417-2425046f394c` with different IDs.

Now, the GitHub issue I've linked above mentions that this has been fixed in Podman 4.8, but **is there a way for me to fix this manually without rebooting the machine?** I can't really update to 4.8 right now.

`podman network rm paperless_default` returns successfully, removes the network, but the `netns` files remain, and so does the `failed to find free IP` error.

`ip netns list` produces no output.

How do I fix this? Any help greatly appreciated.

**Comment by Luap99** [comment]
Reboot would be easiest, if not stop all containers, then remove the stale netns-* files and remove the ipam.db from `/run/user/1000/containers/networks/ipam.db`

**Comment by scy** [comment]
A workaround that I've been able to use successfully: Create a dummy network that uses the exhausted IP range and let your containers create a new one.

1. Delete the exhausted network (`podman network rm the_exhausted_one`).
2. Create a new network manually (`podman network create whatever`). It should reuse the IP range of the exhausted network. We won't be able to claim IP addresses in it, but that's not an issue.
3. Start the container(s) you wanted to start in the first place. They will create a new network that's using a fresh, non-exhausted IP range.

**Comment by robfuscator** [comment]
Since a month or two I'm also facing this issue on one of my servers. I'm unable to track the source down. Did you find out what was triggering it for you?

For me it happens on one of my Fedora CoreOS servers, but not on the other one. All few weeks all my services fail to start (I guess after an update or so), forcing me to manually restart the server.

**Reply by Luap99** [reply]
What is your podman version? If you have a reproducer I am happy to take a look, how are the container configured?

**Reply by robfuscator** [reply]
Thanks for your reply! I'm on podman 5.1.2. I run my containers using `podman kube play` in a systemd unit:

```
[Unit]
After=network-online.target
Wants=network-online.target

[Service]
Restart=on-failure
TimeoutStopSec=70
StartLimitBurst=0
ExecStart=/usr/bin/podman kube play --replace --network path_to_def/definition.yml
ExecStop=/usr/bin/podman kube down path_to_def/definition.yml
Type=forking

[Install]
WantedBy=default.target
```

The definition files look like that:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: edge_proxy

spec:
  containers:
    - name: caddy
      image: public.ecr.aws/docker/library/caddy:2
      imagePullPolicy: Always
      volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/Caddyfile:z
        - name: caddyfile_d
          mountPath: /etc/caddy/Caddyfile.d:z
        - name: caddy-data
          mountPath: /data
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443

  volumes:
    - name: caddyfile
      hostPath:
        path: /path_to_vol1
        type: FileOrCreate
    - name: caddyfile_d
      hostPath:
        path: /path_to_vol2
        type: DirectoryOrCreate
    - name: caddy-data
      hostPath:
        path: /path_to_vol3
        type: DirectoryOrCreate
```

I use the exact same structure on all of my servers, but only on one of them this problem occurs. It's a VPS running Fedora CoreOS. Yesterday was the last time it happened. I don't really understand what the `netns-` files do, but as of now, there are only 4 of them, which is as many pods as I run right now.

Many thanks for your help, tell me if you need anything else.

Edit: I run the services root- and daemonless.
