### DISCUSSION TITLE
How do I increase the pull timeout in a Kube Quadlet?

### DISCUSSION THREAD

**Discussion by p5** [containers/podman#22604] [Q&A]
I am running some services inside Quadlets defined with `.kube` and YAML files, but am running into issues where startup times out before the images are pulled from their registries.  

Even after setting `TimeoutStartSec` inside the Kube's service definition, Podman is still only allowing 5 minutes to pull the images, which isn't always enough.

Is there some way I am missing to extend this timeout to something like 15m?  

Log entry:

```
 Pulling image //ghcr.io/open-webui/open-webui:latest inside systemd: setting pull timeout to 5m0s
```

Kube definition:

```
[Unit]
Description=An Ollama V2 deployment

[Kube]
Yaml=./kube/ollama.yaml

[Service]
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target
```

Kube YAML:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ollama
  name: ollama
spec:
  containers:
  - api:
    name: ollama-api
    image: docker.io/ollama/ollama:latest
    volumeMounts:
    - name: ollama-models
      mountPath: /root/.ollama
    ports:
    - containerPort: 11434
      hostPort: 11434
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
  - web:
    name: ollama-web
    image: ghcr.io/open-webui/open-webui:latest
    ports:
    - containerPort: 8080
      hostPort: 8080
  volumes:
  - name: ollama-models
    emptyDir: {}
```

I appreciate your assistance, and look forward to playing with this some more!
