### DISCUSSION TITLE
Understanding `pasta`s `-i` option and implications for network isolation

### DISCUSSION THREAD

**Discussion by har7an** [containers/podman#22737] [Q&A]
After upgrading to Fedora Silverblue 40, I am currently using podman 5.0.2 and had to notice that the change to `pasta` as default network driver/mode unfortunately breaks my workflows. In particular, I often find myself working on the road, *without any networking whatsoever*. With slirp4netns this worked fine, with pasta this breaks by default as has apparently been discussed at length.

I saw the [following comment][1] which describes a way around this problem. This is only a partial solution though, as pasta still needs the `-i` argument to know which host interface to derive addresses and routes from. Given this and the [Podman 5.0 release announcement][2], my `containers.conf` now looks like this:

```toml
[network]
pasta_options = [
    # Use IPv4 networking
    "-4", "-n", "24", "-a", "10.0.2.100", "-g", "10.0.2.2", "--dns-forward", "10.0.2.3",
    # Configure network interfaces
    "-I", "tap0", "-i", "lo"
]
```

The interesting bit here is the `-i` option. First I tried filling in my network interface, but of course my interfaces are named differently across machines and, for example on my laptop, I usually have different interfaces connected depending on where I am. So I decided to just try out whether `lo` would work (as that's universally available) and apparently it does. With this setup I can ping from inside the container and reach e.g. websites with `curl` (so it also resolves DNS), provided **any** of my interfaces has a proper route set up.

Is this intended behavior? Can I safely do that, or does that somehow expose other things and services also running on localhost to my container? What exactly does `pasta -i` do in this case and why does the interface matter?

Thanks in advance!

[1]: https://github.com/containers/podman/issues/21896#issuecomment-1972628380
[2]: https://blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail/
