### DISCUSSION TITLE
Seriously now, why am I not able to access my app from another computer?

### DISCUSSION THREAD

**Discussion by anoduck** [containers/podman#22928] [Q&A]
Seriously, not for play-play.
I am running a container on a computer on the local LAN. I am on a different computer on my local LAN, AND I cannot access the app running on the container. The app can contact the outside world and interact with it, but regardless of having the firewall ports open, my attempt to contact the app just times out. WTF?

Spent a few hours going in circles with this last weekend, and quite confused. Not to sound like a broken clock, but when I had docker installed, it worked without a hitch. I have to run podman with su privileges, so I am reasonable sure podman is rootful. Below is the podman-compose configuration exported with `podman-compose config`.

```yaml
networks:
  seonet:
    ipam:
      config:
      - gateway: 10.89.0.1
        iprange: 10.89.0.0/28
        subnet: 10.89.0.0/24
      driver: default
services:
  app:
    build: .
    command: sh -c "/bin/wait && /app/seonaut"
    container_name: seonaut
    depends_on:
    - db
    dns: 10.89.0.1
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOST_CONNECT_TIMEOUT: '30'
      WAIT_SLEEP_INTERVAL: '30'
      WAIT_TIMEOUT: '300'
    expose:
    - 9000
    extra_hosts:
    - db:10.89.0.3
    hostname: app
    image: localhost/seonaut_app:latest
    networks:
      seonet:
        aliases:
        - app
        ipv4_address: 10.89.0.2
    ports:
    - 9000:9000
  db:
    container_name: seonautdb
    dns: 10.89.0.1
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_HOST: db_host
      MYSQL_PASSWORD: another_password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
    extra_hosts:
    - app:10.89.0.2
    hostname: db
    image: docker.io/mariadb:latestdocker-compose
    networks:
      seonet:
        aliases:
        - db
        ipv4_address: 10.89.0.3
    ports:
    - 3306:3306
    volumes:
    - ./my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf:ro
version: '3.8'
```

I can connect to it using an ssh tunnel, but this should not be a required step.
