### DISCUSSION TITLE
这东西不能修改默认的各种配置路径吗？

### DISCUSSION THREAD

**Discussion by ddki** [containers/podman#22930] [Q&A]
````
❯ podman machine info
host:
    arch: amd64
    currentmachine: ""
    defaultmachine: ""
    eventsdir: C:\Users\admin\.local\share\containers\podman\podman
    machineconfigdir: C:\Users\admin\.config\containers\podman\machine\wsl
    machineimagedir: C:\Users\admin\.local\share\containers\podman\machine\wsl
    machinestate: ""
    numberofmachines: 0
    os: windows
    vmtype: wsl
version:
    apiversion: 5.1.1
    version: 5.1.1
    goversion: go1.22.3
    gitcommit: bda6eb03dcbcf12a5b7ae004c1240e38dd056d24
    builttime: Wed Jun  5 05:40:05 2024
    built: 1717537205
    osarch: windows/amd64
    os: windows


````

如何修改：eventsdir、machineconfigdir、machineimagedir 三个配置？
如何通过 `podman machine init` 创建的machine存储路径？
如何修改 images 的存储路径？

全部放在C盘吗？C盘空间根本不够，几个images就十几GB了。
看官方文档没看懂，根本找不到内容在哪里，文档不太友好
