### DISCUSSION TITLE
Podman requesting Rosetta

### DISCUSSION THREAD

**Discussion by OlegPQ** [containers/podman#23084] [General]
hello everyone!

PC:
Chip: Apple M3 Max
macOS: 14.3

I installed Podman and QEMU as follows:

```
brew install podman
brew install qemu
```

>  podman info

              
```
OS: darwin/arm64
provider: applehv
version: 5.1.1

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:64104->127.0.0.1:64051: read: connection reset by peer
```

> podman machine init

```
Looking up Podman Machine image at quay.io/podman/machine-os:5.1 to create VM
Extracting compressed file: podman-machine-default-arm64.raw: done  
Machine init complete
To start your machine run:

podman machine start
```

> podman machine info
```
host:
    arch: arm64
    currentmachine: ""
    defaultmachine: ""
    eventsdir: /var/folders/3w/63jp66s968v73g7y3xny3srr0000gn/T/storage-run-501/podman
    machineconfigdir: /Users/oleg/.config/containers/podman/machine/applehv
    machineimagedir: /Users/oleg/.local/share/containers/podman/machine/applehv
    machinestate: ""
    numberofmachines: 0
    os: darwin
    vmtype: applehv
version:
    apiversion: 5.1.1
    version: 5.1.1
    goversion: go1.22.3
    gitcommit: bda6eb03dcbcf12a5b7ae004c1240e38dd056d24
    builttime: Tue Jun  4 21:54:07 2024
    built: 1717530847
    osarch: darwin/arm64
    os: darwin
```

> podman system connection list
```
Name                         URI                                                         Identity                                                    Default     ReadWrite
podman-machine-default       ssh://core@127.0.0.1:64454/run/user/501/podman/podman.sock  /Users/oleg/.local/share/containers/podman/machine/machine  true        true
podman-machine-default-root  ssh://root@127.0.0.1:64454/run/podman/podman.sock           /Users/oleg/.local/share/containers/podman/machine/machine  false       true
```

Now if running `podman machine start` I am asked for permission to install Rosetta. I am a bit confused and don't understand since QEMU is native for this architecture.
Or is Podman using some other version? Or is there something wrong with my configuration? Can anyone explain why this is happening. Thx!
