### DISCUSSION TITLE
Can't seem to figure out `podman kube play` rootless containers on SELinux (migrating from Ubuntu22.04 to Fedora40)

### DISCUSSION THREAD

**Discussion by josh-hemphill** [containers/podman#23660] [Q&A]
This is the `kube.yaml` I'm working with, I had it working just fine on Ubuntu, and tried following the instructions for rootless podman with SELinux (ran `podman unshare chown -R 1000:1000 ./services/data`)
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-06-10T05:34:32Z"
  labels:
    app: podgitea
  name: podgitea
spec:
  restartPolicy: Never
  containers:
    - env:
        - name: GITEA__server__DOMAIN
          value: "{{=env.DOMAIN}}"
        - name: GITEA__server__ROOT_URL
          value: "https://{{=env.DOMAIN}}"
      image: docker.io/gitea/gitea:latest-rootless
      name: gitea
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        allowPrivilegeEscalation: true
        privileged: false
        readOnlyRootFilesystem: false
      ports:
        - containerPort: 3000
          hostPort: 3000
      volumeMounts:
        - mountPath: /etc/gitea:Z
          name: gitea-config-host-0
        - mountPath: /var/lib/gitea:Z
          name: gitea-data-host-2
        - mountPath: /etc/localtime
          name: gitea-localtime-host-0
          readOnly: true
        - mountPath: /etc/timezone
          name: gitea-timezone-host-3
          readOnly: true
  volumes:
    - hostPath:
        path: "{{=env.SERVICE_DIR}}/config"
        type: Directory
      name: gitea-config-host-0
    - hostPath:
        path: "{{=env.SERVICE_DIR}}/data"
        type: Directory
      name: gitea-data-host-2
    - hostPath:
        path: "/etc/localtime"
        type: File
      name: gitea-localtime-host-0
    - hostPath:
        path: "/etc/timezone"
        type: File
      name: gitea-timezone-host-3
```
And I get this in the log after trying to run:
```
podgitea-gitea chmod: /var/lib/gitea/git: Operation not permitted
podgitea-gitea /var/lib/gitea/git is not writable
podgitea-gitea docker setup failed
```
my other pod I have running grist also fails, just without helpful stuff in the log.

I've got a fresh install of Fedora 40 I've been trying to migrate to, but I can't seem to get this working no matter which instructions I follow.
Any help would be appreciated, thank you.
