### DISCUSSION TITLE
Hardware not being passed to container

### DISCUSSION THREAD

**Discussion by twinoijsdrfg** [containers/podman#24075] [General]
Sorry, I don't know the proper terms but I'm trying to set up Frigate using Podman. It needs me to pass both my GPU (Intel onboard thing) and my Google Coral TPU to it. I've been over this a bunch of times and read every setup guide I can find, but the Frigate logs just keep saying that they can't detect either my GPU or my TPU.

Here's my machine details:
```
System:
  Host: my-server Kernel: 6.1.0-25-amd64 arch: x86_64 bits: 64 Console: pty pts/1
    Distro: Debian GNU/Linux 12 (bookworm)
Machine:
  Type: Desktop System: Dell product: PowerEdge T20 v: 01 
  Mobo: Dell model: 0VD5HY v: A07 BIOS: Dell v: A06
    date: 01/27/2015
CPU:
  Info: quad core model: Intel Xeon E3-1225 v3 bits: 64 type: MCP cache: L2: 1024 KiB
Graphics:
  Device-1: Intel Xeon E3-1200 v3 Processor Integrated Graphics driver: i915
```

Here's my compose file:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: no
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256m"  # Set shared memory size
    volumes:
      - ./config:/config
      - ./storage:/mnt/CCTV/storage
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      #- "8554:8554" # RTSP feeds

    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
      - /dev/dri/renderD128:/dev/dri/renderD128  # For GPU acceleration

    privileged: true
```
I'd really appreciate any help here. I've checked permissions and the user running the container has permissions set up properly and I've spent ages making sure all the drivers are set up and everything seems to be working fine outside of the container.
