### DISCUSSION TITLE
podman compose secrets support on Windows

### DISCUSSION THREAD

**Discussion by domsew** [containers/podman#24084] [Q&A]
Hello, I was playing with Podman Desktop on my Windows 10 device, to see if it can be a replacement for Docker Desktop. I encountered a problem with compose [secrets](https://github.com/compose-spec/compose-spec/blob/main/09-secrets.md)
The following `compose.yaml` file works with Docker Desktop, but does not with Podman Desktop:
```yaml
services:
  postgres:
    image: postgres:16.4-bookworm
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-pass
    secrets:
      - db-pass

secrets:
  db-pass:
    environment: TEST_PASSWORD
```
Error log says: "/usr/local/bin/docker-entrypoint.sh: line 21: /run/secrets/db-pass: No such file or directory", which means, that my secret file is not mounted at all. Do you guys know, if it is possible to use secrets with `podman compose`?

Btw, [here](https://docs.podman.io/en/latest/markdown/podman-compose.1.html) is information, that I can disable compose warning by setting `compose_warning_logs` option. Where should I put `containers.conf` file on Windows 10? I tried `%APPDATA%\containers\containers.conf` according to [docs](https://docs.podman.io/en/v4.6.1/markdown/podman-remote.1.html), but it doesn't work.
