### DISCUSSION TITLE
Can someone explain me how relative idmaps work?

### DISCUSSION THREAD

**Discussion by PieterHagedoorn** [containers/podman#24158] [Q&A]
So, I have a pod with nextcloud and syncthing. I want syncthing and nextcloud to both have read and write access to a shared volume, where my data lives. I thus want to use idmapping to make the primary user inside each container have the same read and write rights on the host. Syncthing runs as uid=1000 and nextcloud as uid=82. The uid of the host user is 1000. I am running in rootless mode. This is the kube file that I came up with (simplified):

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nextcloud
  name: nextcloud

spec:
  hostname: nextcloud
  restartPolicy: OnFailure

  containers:
    - name: nextcloud
      image: docker.io/library/nextcloud:fpm-alpine
      volumeMounts:
        - mountPath: /var/www/html/:z,idmap=uids=@1000-82-1;gids=@1000-82-1
          name: nextcloud_html
        - mountPath: /var/www/html/data:z,idmap=uids=@1000-82-1;gids=@1000-82-1
          name: nextcloud_data

    - name: syncthing
      image: docker.io/syncthing/syncthing:latest
      volumeMounts:
        - mountPath: /var/syncthing/Sync:z,idmap=uids=@1000-1000-1;gids=@1000-1000-1
          name: syncthing_data
        - mountPath: /var/syncthing:Z
          name: syncthing_config

  volumes:
    - hostPath:
        path: html
        type: Directory
      name: nextcloud_html
    - hostPath:
        path: /mnt/nextcloud_data
        type: Directory
      name: nextcloud_data
    - hostPath:
        path: /mnt/nextcloud_data/j.p.hagedoorn/files
        type: Directory
      name: syncthing_data
    - hostPath:
        path: syncthing_config
        type: Directory
      name: syncthing_config
status: {}
```

When I try to run this, I get the following error:
```
starting container (id of syncthing container): could not find a user namespace mapping for the relative mapping "@1000-1000-1"
starting container (id of nextcloud container): could not find a user namespace mapping for the relative mapping "@1000-82-1"
```

What does this mean? Am I doing something wrong or is this a bug?
