### DISCUSSION TITLE
Issues running containers with podman-compose

### DISCUSSION THREAD

**Discussion by itsCheithanya** [containers/podman#24320] [Q&A]
Running this compose file with `sudo podman-compose <file> up `file gives permisson denied errors while with `sudo docker-compose <file> up` it works fine
Here are the logs of the containers
![image](https://github.com/user-attachments/assets/a8cee6df-0ef3-447f-bfd8-6f827b0e64a7)
![image](https://github.com/user-attachments/assets/c4f893cd-437b-4374-8f37-0d325e4f8194)

docker-compose.yaml
```
volumes:
  kubearmor-init-vol:
    name: kubearmor-init-vol


services:
  kubearmor-init:
    container_name: kubearmor-init
    image: docker.io/cheithanya/kubearmor-init:latest
    pull_policy: "always"
    # user: root
    labels:
      app: kubearmor-init
    volumes:
      - "/tmp:/opt/kubearmor/BPF:rw"
      - "/lib/modules:/lib/modules:ro"
      - "/sys/fs/bpf:/sys/fs/bpf:ro"
      - "/sys/kernel/security:/sys/kernel/security:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:ro"
      - "/usr/src:/usr/src"
      - "/media/root/etc/os-release:/media/root/etc/os-release:ro"
      - "/etc/containers/oci/hooks.d/:/etc/containers/oci/hooks.d/:rw"
      - "/usr/share/kubearmor:/usr/share/kubearmor:rw"
    restart: on-failure
    privileged: true
    cap_add:
      - SETUID
      - SETGID
      - SETPCAP
      - SYS_ADMIN
      - SYS_PTRACE
      - MAC_ADMIN
      - SYS_RESOURCE
      - IPC_LOCK
      - DAC_OVERRIDE
      - DAC_READ_SEARCH

  kubearmor:
    depends_on:
      kubearmor-init:
        condition: service_completed_successfully
    hostname: cheithanya
    container_name: kubearmor
    image: "docker.io/cheithanya/kubearmor:latest"
    pull_policy: "always"
    # user: root
    command:
      - "-k8s=false"
      - "-enableKubeArmorPolicy"
      - "-enableKubeArmorHostPolicy"
      - "-visibility=process,network"
      - "-hostVisibility=process,network"
      - "-criSocket=unix:///run/podman/podman.sock"
      - "-defaultFilePosture=audit"
      - "-defaultNetworkPosture=audit"
      - "-defaultCapabilitiesPosture=audit"
      - "-hostDefaultFilePosture=audit"
      - "-hostDefaultNetworkPosture=audit"
      - "-hostDefaultCapabilitiesPosture=audit"
    labels:
      app: kubearmor
    volumes:
      - "/tmp:/opt/kubearmor/BPF"
      - "/sys/fs/bpf:/sys/fs/bpf"
      - "/sys/kernel/security:/sys/kernel/security"
      - "/sys/kernel/debug:/sys/kernel/debug"
      - "/etc/apparmor.d:/etc/apparmor.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/run/docker:/run/docker"
      - "/var/lib/docker:/var/lib/docker"
      - "/etc/containers/oci/hooks.d/:/etc/containers/oci/hooks.d/:rw"
      - "/usr/share/kubearmor:/usr/share/kubearmor:rw"
      - "/var/run/kubearmor:/var/run/kubearmor:rw"
    restart: always
    # ports:
    #   - "32767:32767"
    network: host
    pid: "host"
    privileged: true
    cap_add:
      - SETUID
      - SETGID
      - SETPCAP
      - SYS_ADMIN
      - SYS_PTRACE
      - MAC_ADMIN
      - SYS_RESOURCE
      - IPC_LOCK
      - DAC_OVERRIDE
      - DAC_READ_SEARCH



```
