### DISCUSSION TITLE
Container DNS resolution not possible, default internet not working

### DISCUSSION THREAD

**Discussion by Anachron** [containers/podman#24666] [Q&A] [answered]
Hey,

so I'm running `podman` on `Void Linux` and only use `rootless` for now. 

Currently I have the issue that I cannot communicate with the same containers in a pod via hostname. Also the default /etc/resolv.conf from the containers has no internet access, but if I modify the nameserver (like to 1.1.1.1) the container can communicate outside.

Now I need to figure out how to have a container that both can communicate with another one in the same pod but also has internet access.

Please see the attached files and let me know if something is missing. 

Network:
- 10.200.200.0/24: `VPN` Network
- 192.168.178.0/24: `LAN` Network

Specialities:
I use a NAT for DNS resolution on this machine. The DNS-Server (adguardhome) runs itself on podman (rootless) on port 5353, so I remap the 53 destination port in nftables to the correct local 5353 port. 

Edit:
I've uploaded the files [here](https://gist.github.com/Anachron/3131a37bfc7f53442284af3511ef3e8a).

**Comment by Anachron** [comment]
Of course I've read https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md, https://blog.podman.io/2024/10/podman-5-3-changes-for-improved-networking-experience-with-pasta/ and https://blog.podman.io/2024/03/podman-5-0-has-been-released/.

But even uncommenting the `#pasta_options = ["-a", "10.0.2.0", "-n", "24", "-g", "10.0.2.2", "--dns-forward", "10.0.2.3"]` line and removing the pod + network and creating it again there is no change.

**Comment by Anachron** [comment, marked as answer]
Closing as I switched to `pasta` and the following `docker-compose.yml` file works now:

```yml
version: '3.1'

services:

  proxy:
    image: docker.io/alpine
    command: sleep inf
    network_mode: 'pasta'
    ports:
      - 8082:80

  application:
    image: docker.io/wordpress:6.7
    volumes:
      - /data/cnt/appdata/wordpress/site:/var/www/html
    env_file: environment.env
    network_mode: 'service:proxy'

  database:
    image: docker.io/mysql:8.0
    volumes:
      - /data/cnt/appdata/wordpress/database:/var/lib/mysql
    env_file: environment.env
    network_mode: 'service:proxy'
```
