### DISCUSSION TITLE
using generic image as podman "machine"

### DISCUSSION THREAD

**Discussion by mvcorrea-ufc** [containers/podman#25499] [General]
Hi there,
I know its a redhat project! but the image is getting big and I am working in a limited env.
so I tried :)

`podman machine init --image-path https://cloud.debian.org/images/cloud/trixie/daily/20250305-2042/debian-13-genericcloud-amd64-daily-20250305-2042.qcow2 debian-machine`

later when

`podman machine start debian-machine --log-level=debug`

got stucked on a login shell. then tried...

`podman machine init --image-path=https://cloud.debian.org/images/cloud/trixie/daily/20250305-2042/debian-13-genericcloud-amd64-daily-20250305-2042.qcow2 --cpus=2 --memory=2048 --disk-size=20 --ignition-path=cloud-init.yaml debian-machine`

using cloud-init.yaml

```
#cloud-config
users:
  - name: core
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa PLACEHOLDER_KEY  # This will be replaced by Podman

hostname: debian-machine
```
then

`Error: dial unix /var/folders/k5/nkc5mpcn7936lzyngljrhhnr0000gn/T/podman/qmp_debian-machine.sock: connect: no such file or directory`

then stopped :(
Any documentation on building a proper qcow2 to work with podman?
Any List of images (exept fedora-coreos) to use with it?
