### DISCUSSION TITLE
Everything required to use Podman error-free with Dev Containers on WSL2

### DISCUSSION THREAD

**Discussion by worldofgeese** [containers/podman#25607] [Show and tell]
This guide is intended to spark a discussion about the many papercuts Windows developers will face when configuring Podman with Dev Containers on WSL2. The steps below capture tested workarounds; some are conditional, and notes call out behavior that is unsupported or not persistent across WSL restarts.

Is there any appetite from Podman devs to do a virtual "[empathy session](https://thagomizer.com/blog/2024/09/11/advanced-friction-logs-empathy.html)" where we all sit down and attempt to run the example Dev Container on WSL2, starting from zero? I think it could be fun!

cc @n1hility @rhatdan who I've had fruitful discussions with in the past when I first created https://github.com/containers/podman/issues/15338.

> **Update (May 2026):** Do **not** enable `systemd=true` inside `podman-machine-default`. A Podman maintainer states in https://github.com/containers/podman/issues/28341 that systemd in WSL is unsupported for Podman and says: "Podman doesn't work with systemd enabled in WSL. Please disable it." Step 6 has been updated accordingly. Also note that Step 3's shared-mount remount is session-scoped and does not persist after `wsl --shutdown`.

---

## Step 1: Initialize a Podman machine

```bash
podman machine init -m 16384 --now
```

---

## Step 2: Resolve broken `podman stats`

```text
Error: stats is not supported in rootless mode without cgroups v2
```

Follow these steps:

1. Open your WSL2 configuration file at `%UserProfile%\.wslconfig`.
2. Add or update the following configuration:

   ```ini
   [wsl2]
   kernelCommandLine = cgroup_no_v1=all
   ```

3. Save the file.

This configuration disables cgroups v1, enabling cgroups v2, and resolves https://github.com/microsoft/WSL/issues/10050.

---

## Step 3: Resolve shared mount warning

If you receive this warning:

```text
"/" is not a shared mount, this could cause issues or missing mounts with rootless containers
```

Run these commands:

```bash
sudo mount -o remount,shared /
podman system reset
```

This resolves https://github.com/microsoft/vscode-remote-release/issues/9303 for the current WSL session.

> **Note:** this remount does not persist across `wsl --shutdown` in current testing. Treat it as a session-scoped workaround and re-run it when needed. Do not use `systemd=true` in the Podman machine as a persistence workaround; see Step 6.

---

## Step 4: Resolve rootless Podman issues

To work around issues with rootless Podman (such as permissions issues creating and manipulating directories and files), set the following in `devcontainer.json`:

```json
"runArgs": [
  "--userns=keep-id"
],
```

## Step 5: Allow locally built images to be pulled

For error, `Pinging container registry localhost connection refused`, create a custom Podman configuration file:

```bash
mkdir -p ~/.config/containers && cat > ~/.config/containers/containers.conf << 'EOF'
[engine]
compat_api_enforce_docker_hub=false
EOF
```

This resolves https://github.com/containers/podman/issues/19856

---

## Step 6: Do not enable systemd inside the Podman machine

Do **not** add `[boot] systemd=true` to `/etc/wsl.conf` inside `podman-machine-default` as a general fix for socket or Dev Containers issues.

A Podman maintainer states in https://github.com/containers/podman/issues/28341 that enabling systemd in WSL is unsupported for Podman, and clarifies: "Podman doesn't work with systemd enabled in WSL. Please disable it."

With `systemd=true` enabled, `podman machine start` can fail with:

```text
Error: machine did not transition into running state: ssh error: machine not in running state
```

The supported baseline inside the Podman machine is:

```ini
[user]
default=user
```

If you previously enabled systemd in the Podman machine, remove the `[boot] systemd=true` section, then restart WSL:

```powershell
wsl --shutdown
podman machine start
```

For cross-WSL / VS Code Dev Containers setups, use the documented Podman remote/socket approach and make sure VS Code points to the correct Podman binary path rather than enabling systemd in `podman-machine-default`.

---

## Step 7: Restart WSL2

```bash
wsl --shutdown
```

---

## Example configuration files

Utilize these configuration examples for your Dev Container setup:

### `docker-compose.yml`

```yaml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/opt/app-root/src
    command: sleep infinity
    init: true
    user: 1001:0
    tmpfs:
      - /opt/app-root/src/backstage/node_modules:mode=777
      - /opt/app-root/src/packages/app/node_modules:mode=777
      - /opt/app-root/src/packages/backend/node_modules:mode=777
    depends_on:
      - db
    userns_mode: "keep-id"
    env_file:
      - path: ./.env

  db:
    image: postgres:14.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    shm_size: '128mb'

volumes:
  postgres_data:
```

### `Dockerfile`

```dockerfile
# syntax=docker/dockerfile:1
ARG UV_VERSION=0.6.3
ARG NODEJS_VERSION=22
ARG HADOLINT_VERSION=2.12.1-beta

FROM ghcr.io/astral-sh/uv:$UV_VERSION AS uv
FROM ghcr.io/hadolint/hadolint:$HADOLINT_VERSION AS hadolint
FROM quay.io/fedora/nodejs-$NODEJS_VERSION AS base

FROM base
COPY --from=uv --chown=1001:0 /uv /uvx /bin/
COPY --from=hadolint /bin/hadolint /bin/

ENV PATH="$HOME/.local/bin/:$PATH"

USER 0
RUN chown -R 1001:0 /opt/app-root/src && chmod -R g=u /opt/app-root/src
RUN uv pip install --system --break-system-packages \
  mkdocs-techdocs-core mkdocs-git-revision-date-localized-plugin \
  mkdocs-include-markdown-plugin mkdocs-mermaid2-plugin
USER 1001
```

### `devcontainer.json`

```json
{
  "name": "Baseplate",
  "dockerComposeFile": "docker-compose.yml",
  "service": "app",
  "workspaceFolder": "/opt/app-root/src/${localWorkspaceFolderBasename}",
  "forwardPorts": [3000,3001,3007,5432,5433,7000,7007,4000],
  "containerEnv": {
    "HOST_HOME": "${localEnv:HOME}",
    "DEVCONTAINER": "true"
  },
  "postStartCommand": "npm install -g corepack; corepack enable; yarn",
  "customizations": {
    "vscode": {
      "extensions": ["esbenp.prettier-vscode","dbaeumer.vscode-eslint","Orta.vscode-jest","eamodio.gitlens"]
    }
  },
  "remoteUser": "default"
}
```
