### DISCUSSION TITLE
Entries in /etc/hosts not working when Podman running on WLS2

### DISCUSSION THREAD

**Discussion by rgaiacs** [containers/podman#25710] [Q&A] [answered]
I'm trying to replace Docker with Podman. My working machine is Windows 10 Enterprise (version `22H2`, build `19045.5608`) with WSL2. I have entries in `C:\Windows\System32\drivers\etc\hosts` like

```
127.0.0.1 lorem.ipsum
```

that WSL2 propagates to `/etc/hosts`.

Given the minimal example of NGINX container in a pod, i.e.

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-mwe
spec:
  containers:
    - name: nginx
      image: docker.io/nginx:1.25.4-alpine-slim
      ports:
        - containerPort: 80
          hostIP: 0.0.0.0
          hostPort: 80
```

and the equivalente Docker Compose, i.e.

```yaml
services:
  nginx:
    image: docker.io/nginx:1.25.4-alpine-slim
    ports:
      - 80:80
```

I'm observing

| `curl` command | WSL2 connecting to Podman | Windows host connecting to Podman | WSL2 connecting to Docker | Windows host connecting to Docker |
| --- | --- | --- |---|---|
| `curl http://localhost` | ✔️  | ✔️ | ✔️  | ✔️ |
| `curl http://lorem.ipsum` | ✔️ | ❌ | ✔️  | ✔️ |

Can I have some help to have the `curl` request from the Windows host to reach Podman running on WSL2?

## Podman Information

```bash
podman --version
```

```
podman version 5.4.1
```

I'm **NOT** running the `podman-machine`.

## WSL2 Information

```cmd
wsl.exe --version
```

```
WSL version: 2.4.11.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5716
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.5608
```
