### DISCUSSION TITLE
containers cannot communiate if one is in host network

### DISCUSSION THREAD

**Discussion by What-a-mess** [containers/podman#26246] [Q&A]
I was deplying a homelab and trying to get things work with qbittorrent using host network and sonarr using container network (both runs in podman's container). It was working when all containers just started, but then it won't work most of time. Sonarr gives me the error that it cannot connect to qbittorrent. 

I tried to run `curl -v host.containers.internal:8989` (that's the host and port in sonarr's setting for qbittorrent), sometimes it works, but most of time it will just timeout, and tcpdump shows that the eth0 in sonarr did sent the packet, but the lo in host never received (ping works btw).

I want to know if this is because of my wrong configurations? Or is this just works as intended?

Here are the compose.yaml I'm using for these two services.

```yaml
version: "2"
services:
  qbittorrent:
    image: superng6/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8989
      - TL=https://cf.trackerslist.com/best.txt
    volumes:
      - ./config:/config
      - /mnt/allin1/qb-download:/downloads
      - /mnt/allin1/share-data:/share

    network_mode: host
    http_proxy: false
    restart: unless-stopped
```

```yaml
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ./sonarr/config:/config
    ports:
      - 9001:8989
    networks:
      brlan0:
    http_proxy: false
    restart: unless-stopped

networks:
  brlan0:
    external: true
```
