### ISSUE TITLE
Support Kubernetnes secrets 

### ISSUE THREAD

**Issue by ashley-cui** [containers/podman#10105]
/kind feature

**Description**

We want to be able to support kubernetes secrets so we can use podman secrets with generate and play kube

https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by mheon** [comment]
Is this just for `generate kube` / `play kube` or do you see this as a separate backend for secrets?

**Comment by ashley-cui** [comment]
Not sure yet, haven't gotten to look too deep into it

**Comment by rhatdan** [comment]
This is just generate/play.
Basically translate from podman secrets and kube secrets back and forth.

**Comment by larsks** [comment]
I was interesting in running a pod locally that consumes secrets, so @ashley-cui  pointed me at this issue. I'm not clear on what the scope of this feature is supposed to be, so I thought we should make explicit what secret support looks like in kubernetes.

Unlike the current podman secrets implementation, Kubernetes secrets must be `Secret` resources, which have the following structure:

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
type: Opaque
stringData:
  my_first_secret: supersecret
  my_second_secret: anothersecret
```

Critical is the fact that a single resource may contain multiple key/value pairs in the `data` section (these values are base64 encoded; you can use `stringData` instead for simple text secrets).

Secrets can be exposed as either environment variables or as files on the filesystem via volume mounts.

## As environment variables

Environment variable access looks like this to expose a single
key/value pair:

```
env:
  - name: MY_FIRST_SECRET
    valueFrom:
      secretKeyRef:
        name: secret-sample
        key: my_first_secret
```

Or like this to expose all key/value pairs from a `Secret` resource:

```
envFrom:
  - secretRef:
      name: secret-sample
```

## As volume mounts

Access via volume mounts looks like this:

```
[...]
spec:
  containers:
    - name: mycontainer
      volumeMounts:
        - name: mysecret
          mountPath: /etc/mysecret
  [...]
  volumes:
    - name: mysecret
      secret:
        secretName: secret-sample
```

The above would expose all the key/value pairs from the referenced `Secret` resource as files inside the `/etc/mysecret` directory.  You can expose a single key/value pair using a `subPath` argument:

```
[...]
spec:
  containers:
    - name: mycontainer
      volumeMounts:
        - name: mysecret
          mountPath: /etc/my_first_secret
          subPath: my_first_secret
  [...]
  volumes:
    - name: mysecret
      secret:
        secretName: secret-sample
```

---

All of the above examples rely on the fact that secrets are structured
documents. For podman to offer a meaningful analogue of this behavior,
it seems as if podman's secrets support must also support something
very much like the k8s `Secret` resource.
