### ISSUE TITLE
podman in openshift pod

### ISSUE THREAD

**Issue by tomassatka** [containers/podman#10380]
**Description**

Can a user define a podman running as a pod in Openshift?
referenced: [redhat dev portal: podman in openshift pod](https://access.redhat.com/discussions/6028811)

I took the podman modified here: https://hub.docker.com/r/mgoltzsche/podman for rootless podman where user can run the docker container with --privileged mode and -u 1000 then the container runs fine and podman inside has access to uidmap.

However when i try this on openshift i get:
`error from newuidmap: newuidmap: write to uid_map failed: Operation not permitted`

full log:
```
/ $ podman -v
podman version 3.1.2

/ $ podman --log-level debug ps
INFO[0000] podman filtering at log level debug
DEBU[0000] Called ps.PersistentPreRunE(podman --log-level debug ps)
DEBU[0000] Reading configuration file "/etc/containers/containers.conf"
DEBU[0000] Merged system config "/etc/containers/containers.conf": &{Containers:{Devices:[] Volumes:[] ApparmorProfile:containers-default-0.36.0 Annotations:[] CgroupNS:host Cgroups:enabled DefaultCapabilities:[CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] DefaultSysctls:[] DefaultUlimits:[nproc=4194304:4194304] DefaultMountsFile: DNSServers:[] DNSOptions:[] DNSSearches:[] EnableKeyring:true EnableLabeling:false Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm] EnvHost:false HTTPProxy:true Init:false InitPath: IPCNS:private LogDriver:k8s-file LogSizeMax:-1 NetNS:slirp4netns NoHosts:false PidsLimit:2048 PidNS:private SeccompProfile:/usr/share/containers/seccomp.json ShmSize:65536k TZ: Umask:0022 UTSNS:private UserNS:host UserNSSize:65536} Engine:{CgroupCheck:false CgroupManager:cgroupfs ConmonEnvVars:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] ConmonPath:[/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] DetachKeys:ctrl-p,ctrl-q EnablePortReservation:true Env:[] EventsLogFilePath:/tmp/run-1000/libpod/tmp/events/events.log EventsLogger:file HooksDir:[/usr/share/containers/oci/hooks.d] ImageBuildFormat:oci ImageDefaultTransport:docker:// ImageParallelCopies:0 ImageDefaultFormat: InfraCommand: InfraImage:k8s.gcr.io/pause:3.5 InitPath:/usr/libexec/podman/catatonit LockType:shm MultiImageArchive:false Namespace: NetworkCmdPath: NetworkCmdOptions:[] NoPivotRoot:false NumLocks:2048 OCIRuntime:runc OCIRuntimes:map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] PullPolicy:missing Remote:false RemoteURI: RemoteIdentity: ActiveService: ServiceDestinations:map[] RuntimePath:[] RuntimeSupportsJSON:[crun runc] RuntimeSupportsNoCgroups:[crun] RuntimeSupportsKVM:[kata kata-runtime kata-qemu kata-fc] SetOptions:{StorageConfigRunRootSet:false StorageConfigGraphRootSet:false StorageConfigGraphDriverNameSet:false StaticDirSet:false VolumePathSet:false TmpDirSet:false} SignaturePolicyPath:/etc/containers/policy.json SDNotify:false StateType:3 StaticDir:/podman/.local/share/containers/storage/libpod StopTimeout:10 TmpDir:/tmp/run-1000/libpod/tmp VolumePath:/podman/.local/share/containers/storage/volumes VolumePlugins:map[]} Network:{CNIPluginDirs:[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] DefaultNetwork:podman NetworkConfigDir:/podman/.config/cni/net.d}}
DEBU[0000] Using conmon: "/usr/libexec/podman/conmon"
DEBU[0000] Initializing boltdb state at /podman/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /podman/.local/share/containers/storage
DEBU[0000] Using run root /tmp/podman-run-1000/containers
DEBU[0000] Using static dir /podman/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /tmp/run-1000/libpod/tmp
DEBU[0000] Using volume path /podman/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] Not configuring container store
DEBU[0000] Initializing event backend file
DEBU[0000] configured OCI runtime crun initialization failed: no valid executable found for OCI runtime crun: invalid argument
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] Using OCI runtime "/usr/local/bin/runc"
DEBU[0000] error from newuidmap: newuidmap: write to uid_map failed: Operation not permitted
Error: cannot setup namespace using newuidmap: exit status 1
```

I have tried it with such deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podman
  template:
    metadata:
      labels:
        app: podman
    spec:
      serviceAccount: sa-privileged
      serviceAccountName: sa-privileged
      securityContext:
        runAsUser: 1000
      containers:
        - name: podman
        command: [ "tail" ]
        args: [ "-f", "/dev/null" ]
        image: "mgoltzsche/podman"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
          containerPort: 80
          protocol: TCP
       securityContext:
         capabilities:
           add: [ "SETUID", "FSETID", "SYS_RESOURCE" ]
```

and service account sa-privileged has been added
`oc adm policy add-scc-to-user privileged sa-privileged`

just dont know if it is pointless or there is already a way how to achieve podman to run as a pod.

Thx for advice
Tomas

**Comment by mheon** [comment]
@rhatdan @umohnani8 Got a podman-in-podman issue for y'all

**Comment by umohnani8** [comment]
@tomassatka can you please try this with our stable podman image `quay.io/podman/stable`.

Here is a simple pod yaml that I have used to have podman working inside a k8s pod:
```
apiVersion: v1
kind: Pod
metadata:
 name: podman-rootless
spec:
 containers:
   - name: rootless
     image: quay.io/podman/stable
     args:
       - sleep
       - "1000000"
     securityContext:
       privileged: true
       runAsUser: 1000
```

**Comment by tomassatka** [comment]
Hi @umohnani8 thanks for suggestion but do you have also an example for openshift?

When i try the proposed solution that is made for k8s i get:
`Error: pods "podman-rootless" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000620000, 1000629999] spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]`

And that is for clear reason. However before i start to play around with SCC maybe you already have something specific setup that could try.

**Comment by tomassatka** [comment]
Basically i tried it with previous sa that had privileged rights

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podman-rootless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podman
  template:
    metadata:
      labels:
        app: podman
    spec:
      serviceAccount: sa-privileged
      serviceAccountName: sa-privileged
      containers:
        - name: rootless
          image: quay.io/podman/stable
          args:
            - sleep
            - "1000000"
          securityContext:
            privileged: true
            runAsUser: 1000
```

and got pretty interesting outcome:
```
WARN[0000] Failed to detect the owner for the current cgroup: stat /sys/fs/cgroup/systemd/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-poda2916c53_afaa_4f8f_8db0_40089880ba0b.slice/crio-31ef03a827466d26e33d9c237b56ff0cebe2532e755e006b55dbf1ce4eaf11cd.scope: no such file or directory 
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Wed May 12 19:27:59 2021
OS/Arch:      linux/amd64
sh-5.1$ podman ps
WARN[0000] Failed to detect the owner for the current cgroup: stat /sys/fs/cgroup/systemd/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-poda2916c53_afaa_4f8f_8db0_40089880ba0b.slice/crio-31ef03a827466d26e33d9c237b56ff0cebe2532e755e006b55dbf1ce4eaf11cd.scope: no such file or directory 
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES
sh-5.1$ podman images
WARN[0000] Failed to detect the owner for the current cgroup: stat /sys/fs/cgroup/systemd/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-poda2916c53_afaa_4f8f_8db0_40089880ba0b.slice/crio-31ef03a827466d26e33d9c237b56ff0cebe2532e755e006b55dbf1ce4eaf11cd.scope: no such file or directory 
REPOSITORY  TAG     IMAGE ID  CREATED  SIZE
```
commands are working just not sure if i can ignore the failed owner for current cgroup info
