### ISSUE TITLE
MacOS remotely start container, it auto exit after a while

### ISSUE THREAD

**Issue by gth7754125** [containers/podman#10554]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
 **Environment**
Open a VM on my macbook pro, and use podman to control the container inside VM.
VM: ubuntu 20.10 built by multipass
podman: latest version

**Problem**
run command below on my mac 
```bash
 podman container start redis
```
redis start on my Virtual Machine Ubuntu built by multipass.
 Without visit this container, after a while, it exits automatically.
However, **if i type the command on ubuntu(VM) inside directly, container won't exit even i don't access it.**

**Describe the results you expected:**
use podman remotely on macOS , even i don't access container, it won't exit automatically.

**VM cloud-init.yaml**
```yaml
---
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-rsa xxxx

manage_resolv_conf: true
resolv_conf:
  nameservers: ['223.5.5.5', '119.29.29.29']

apt_sources:
  - source: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.10/ /"
    key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1.4.5 (GNU/Linux)

      mQENBFtkV0cBCADStSTCG5qgYtzmWfymHZqxxhfwfS6fdHJcbGUeXsI5dxjeCWhs
      XarZm6rWZOd5WfSmpXhbKOyM6Ll+6bpSl5ICHLa6fcpizYWEPa8fpg9EGl0cF12G
      GgVLnnOZ6NIbsoW0LHt2YN0jn8xKVwyPp7KLHB2paZh+KuURERG406GXY/DgCxUx
      Ffgdelym/gfmt3DSq6GAQRRGHyucMvPYm53r+jVcKsf2Bp6E1XAfqBrD5r0maaCU
      Wvd7bi0B2Q0hIX0rfDCBpl4rFqvyaMPgn+Bkl6IW37zCkWIXqf1E5eDm/XzP881s
      +yAvi+JfDwt7AE+Hd2dSf273o3WUdYJGRwyZABEBAAG0OGRldmVsOmt1YmljIE9C
      UyBQcm9qZWN0IDxkZXZlbDprdWJpY0BidWlsZC5vcGVuc3VzZS5vcmc+iQE+BBMB
      CAAoBQJfcJJOAhsDBQkIKusHBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBN
      ZDkDdQYKpB0xCACmtCT6ruPiQa4l0DEptZ+u3NNbZfSVGH4fE4hyTjLbzrCxqcoh
      xJvDKxspuJ85wWFWMtl57+lFFE1KP0AX2XTT+/v2vN1PIfwgOSw3yp2sgWuIXFAi
      89YSjSh8G0SGAH90A9YFMnTbllzGoGURjSX03iasW3A408ljbDehA6rpS3t3FD7P
      PnUF6204orYu00Qvc54an/xVJzxupb69MKW5EeK7x8MJnIToT8hIdOdGVD6axsis
      x+1U71oMK1gBke7p4QPUdhJFpSUd6kT8bcO+7rYouoljFNYkUfwnqtUn7525fkfg
      uDqqXvOJMpJ/sK1ajHOeehp5T4Q45L/qUCb3iEYEExECAAYFAltkV0cACgkQOzAR
      t2udZSOoswCdF44NTN09DwhPFbNYhEMb9juP5ykAn0bcELvuKmgDwEwZMrPQkG8t
      Pu9n
      =42uC
      -----END PGP PUBLIC KEY BLOCK-----

package_update: true
package_upgrade: true
packages:
  - podman
  - containerd

runcmd:
  - systemctl --user enable podman.socket
  - systemctl --user start podman 
  - sudo systemctl enable -s HUP ssh
```
