### ISSUE TITLE
Fail to get a runnanble gitlab container with rootless user

### ISSUE THREAD

**Issue by bioinfornatics** [containers/podman#11108]
Dear,

Firstly thanks for your amazing works on `podman`. Currently I encounter some problem while orchestration container deployment  through Ansible .

I create a `gitlab` user to run container in rootless env:

```yaml
- name: Create gitlab user
  user:
    name: "gitlab"
    state: present
    createhome: yes
    home:  /srv/gitlab
    uid: "30004"
    shell: /bin/bash
```

And I would like to use this user to run a `gitlab` container such as:

```yaml
- name: Create GitLab container
  become_user: gitlab
  containers.podman.podman_container:
    detach: yes
    hostname: gitlab.foo.org
    ports: 
      - "3443:443"
      - "3080:80"
      - "3022:22"
    name: gitlab
    restart_policy: always
    state: started
    volume:
      - /srv/gitlab/config:/etc/gitlab:Z
      - /srv/gitlab/logs:/var/log/gitlab:Z
      - /srv/gitlab/data:/var/opt/gitlab:Z
    image: gitlab/{{ gitlab_edition }}:{{ gitlab_version }}
``` 

But I encounter 2 problems once logged as `gitlab` user:

1.  Shell env has wrong value
```
$ podman ps -a
ERRO[0000] XDG_RUNTIME_DIR directory "/run/user/0" is not owned by the current user
``` 

So I have to set to empty this value like this:

```
export XDG_RUNTIME_DIR=''
```

2. Once I do this the container fail to stay up with the following error:
``` 
$ podman logs gitlab
....
/opt/gitlab/embedded/bin/runsvdir-start: line 24: ulimit: pending signals: cannot modify limit: Operation not permitted
/opt/gitlab/embedded/bin/runsvdir-start: line 34: ulimit: max user processes: cannot modify limit: Operation not permitted
/opt/gitlab/embedded/bin/runsvdir-start: line 37: /proc/sys/fs/file-max: Read-only file system
```

So did you know a workaround for the second problem? 

Thanks for your help
