### ISSUE TITLE
podman generate kube emits redundant command: and invents a TERM variable

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11672]
I create an OCI image, stored in locals’ containers-storage, which image does not have `TERM` variable.  I start it with

$ podman run --read-only=true --mount type=bind,src=data,dst=/data,relabel=private --read-only-tmpfs=false -dt -p=3890:3890 localhost/openldap:2021-09-21

The container is called `cranky_goldstine`.  It executes the default entry point.

Calling `podman generate kube cranky_goldstine` prints:
```yaml
spec:       
  containers:
  - command: 
    - /libexec/slapd 
    - -d0
    - -h
    - ldap://:3890/
    env:
    - name: PATH                   
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
```

* Since the environment variable TERM was never ever set, it shall not be in the output of `podman generate kube`.

According to https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container if a `command` is not specified for a container, the default entry point is used.  To be precise, the documentation says “ The docker image's ENTRYPOINT is used if this is not provided.”, I use an OCI image and I guess that the default entry point for OCI images is also applied.

* Since the default command is used to run the image, the container’s command shall not be emitted by `podman generate kube`.

```
$ podman version 
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Mon Aug 30 23:46:36 2021
OS/Arch:      linux/amd64
```

**Comment by dilyanpalauzov** [comment]
Concerning the kubernetes documentation, whether the entry point from OCI images is honoured, if command is missing, as it is done for Docker images, I opened https://github.com/kubernetes/website/issues/29765.

**Comment by mheon** [comment]
@rhatdan Are you fixing the environment variable bits?

**Comment by rhatdan** [comment]
Yes
/assign

**Comment by rhatdan** [comment]
https://github.com/containers/podman/pull/11676 Should remove the extra environment variables.
As far as the other issue, do you beleive that if the cmd comes from the image, then we should not add it to the kube.yaml correct?

**Comment by dilyanpalauzov** [comment]
Yes, if the command comes from the image, ot shall not be in the yaml output.

**Comment by dilyanpalauzov** [comment]
I compiled the latest podman - commit 3d34d3a186a782e48bdbd1 .  Then I do:
```
export tag=2021-09-21
wget https://mail.aegee.org/oci-images/ldap-$tag.tar
mkdir -p data/aegee data/config
podman unshare chown -R 2000.2000 data
podman pull oci-archive:ldap-$tag.tar
podman run --read-only=true --mount type=bind,src=data,dst=/data,relabel=private --rm=true --entrypoint='["/sbin/slapadd", "-n0", "-l/etc/init0.ldif", "-F/data/config"]' localhost/openldap:$tag
podman run --read-only=true --mount type=bind,src=data,dst=/data,relabel=private --rm=true --entrypoint='["/sbin/slapadd", "-n1", "-l/etc/init1.ldif"]' localhost/openldap:$tag

podman run --read-only=true --mount type=bind,src=data,dst=/data,relabel=private --read-only-tmpfs=false --detach=true -p 3890:3890 localhost/openldap:$tag 
# the above line prints 56f0c53ca33e37a59148a1752b29c37a5b988dea564b446168c15661073a72ba
podman generate kube 56f0c53ca33e37a59148a1752b29c37a5b988dea564b446168c15661073a72ba


apiVersion: v1
kind: Pod    
metadata:                 
  creationTimestamp: "2021-09-23T12:38:33Z"
  labels:                     
    app: modestvisvesvaraya
  name: modestvisvesvaraya
spec:    
  containers:
  - command:
    - /libexec/slapd
    - -d0
    - -h
    - ldap://:3890/
    image: localhost/openldap:2021-09-21
    name: modestvisvesvaraya
    ports:
    - containerPort: 3890
      hostPort: 3890
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 2000
      runAsUser: 2000
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /data
      name: home-d-U-data-host-0
    workingDir: /
  dnsConfig: {}
  volumes:
  - hostPath:
      path: /home/d/U/data
      type: Directory
    name: home-d-U-data-host-0
status: {}
```

The OCI image contains in the blobs/sha254/-schemaVersion:2 file :  "Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"] .  The PATH variable is implicitly included by buildah bud, but this variable is explicitly presented in the OCI image.  Unless there are defaults for PATH in Kubernetes, when PATH is missing, PATH must be exported by `podman generate kube`.

The containers.command is still emitted explicitly, even if it is the default command in the image.
