### ISSUE TITLE
Podman cannot update the manifest schema v1 to v2 automatically

### ISSUE THREAD

**Issue by jianzhangbjz** [containers/podman#11729]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
There is an image with schema v1: `"ManifestType": "application/vnd.docker.distribution.manifest.v1+prettyjws"`. But, after the image mirroring, the digest of this image will be changed, so I want to update the schema version to `v2`.
I follow this [Update to image manifest version 2, schema 2](https://docs.docker.com/registry/spec/deprecated-schema-v1/#update-to-image-manifest-version-2-schema-2).

**Steps to reproduce the issue:**

1, podman `pull/push` this scehma v1 image.
```yaml
[cloud-user@preserve-olm-env jian]$ podman push quay.io/openshifttest/etcd-operator:v0.9.4
Getting image source signatures
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob 6716b5119fb8 skipped: already exists  
Copying blob 9634398ecc32 skipped: already exists  
Copying blob 96b4c9fdee15 skipped: already exists  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob b9a4a96cf659 skipped: already exists  
Copying blob e79522dce35e skipped: already exists  
Copying blob e7028e7164e7 [--------------------------------------] 0.0b / 0.0b
Writing manifest to image destination
Storing signatures

[cloud-user@preserve-olm-env jian]$ podman pull quay.io/openshifttest/etcd-operator:v0.9.4
Trying to pull quay.io/openshifttest/etcd-operator:v0.9.4...
Getting image source signatures
Copying blob 80b1b554e5b4 skipped: already exists  
Copying blob 59265c40e257 skipped: already exists  
Copying blob 678f2cfebea6 skipped: already exists  
Copying blob 6d4b4c91b3ff skipped: already exists  
Copying blob e05d0d7eb99a skipped: already exists  
Copying blob 8ea0315241b4 skipped: already exists  
Copying blob a3ed95caeb02 done  
Copying blob a3ed95caeb02 done  
Writing manifest to image destination
Storing signatures
9d5c51d92fbddcda022478def5889a9ceb074305d83f2336cfc228827a03d5d5
```

**Describe the results you received:**
Check the schema version. But, the `ManifestType` still is `v1`.
```yaml
[cloud-user@preserve-olm-env jian]$ podman inspect quay.io/openshifttest/etcd-operator:v0.9.4
[
    {
...
        "Annotations": {},
        "ManifestType": "application/vnd.docker.distribution.manifest.v1+prettyjws",
        "User": "etcd-operator",
        "History": [
...
```

**Describe the results you expected:**
It should be changed to `"ManifestType": "application/vnd.docker.distribution.manifest.v2+json"` automatically.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried the `pull/push` with `docker` command, it works as expected: the schema v1 was changed to v2 automatically.
```
[jzhang@dhcp-140-36 ~]$ docker version
Client: Docker Engine - Community
 Version:           19.03.0-rc3
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        27fcb77
 Built:             Thu Jun 20 02:02:49 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       27fcb77
  Built:            Thu Jun 20 02:01:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
1, pull this image with docker 
```yaml
[jzhang@dhcp-140-36 ~]$ docker pull quay.io/openshifttest/etcd-operator:v0.9.4
v0.9.4: Pulling from openshifttest/etcd-operator
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption.
59265c40e257: Already exists 
8ea0315241b4: Already exists 
678f2cfebea6: Already exists 
e05d0d7eb99a: Already exists 
80b1b554e5b4: Already exists 
6d4b4c91b3ff: Already exists 
Digest: sha256:b062d1729b9d99cbda3c2f1d8dd58b54b1ee9df3f02b3410bcb3e5379f1a489b
Status: Downloaded newer image for quay.io/openshifttest/etcd-operator:v0.9.4
quay.io/openshifttest/etcd-operator:v0.9.4
```
2, push this image with docker.
```yaml
[jzhang@dhcp-140-36 ~]$ docker push quay.io/openshifttest/etcd-operator:v0.9.4
The push refers to repository [quay.io/openshifttest/etcd-operator]
b9a4a96cf659: Layer already exists 
6716b5119fb8: Layer already exists 
e7028e7164e7: Layer already exists 
96b4c9fdee15: Layer already exists 
9634398ecc32: Layer already exists 
e79522dce35e: Layer already exists 
v0.9.4: digest: sha256:2cce9f8e95c9b4ce19b9ffbb95298b9ba3c4960dc962030d8bce655f3811adb0 size: 1582
```
3, check the manifest type of this image. The schema v1 was changed to v2 successfully.
```yaml
[cloud-user@preserve-olm-env jian]$ podman pull quay.io/openshifttest/etcd-operator:v0.9.4
Trying to pull quay.io/openshifttest/etcd-operator:v0.9.4...
...
[cloud-user@preserve-olm-env jian]$ podman inspect quay.io/openshifttest/etcd-operator:v0.9.4
[
    {
        "Id": "9d5c51d92fbddcda022478def5889a9ceb074305d83f2336cfc228827a03d5d5",
...
"ManifestType": "application/vnd.docker.distribution.manifest.v2+json",
....
```

**Output of `podman version`:**

```
[cloud-user@preserve-olm-env jian]$ podman version
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 03:52:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
