### ISSUE TITLE
kube generate: `privileged: false` is not correct 

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11916]
I run podman in rooltess mode and kubernetes in rootful mode. To start podman I use the instructions at https://mail.aegee.org/cgit/aegee-ldap/tree/readme.md#n13 . Then I call `podman generate kube`.  The output contains:
```
apiVersion: v1        
kind: Pod            
spec:     
  containers:
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: true 
      runAsGroup: 2000
      runAsUser: 2000
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /data
      name: home-d-data-host-0
  volumes:
  - hostPath:
      path: /home/d/data
      type: Directory
    name: home-d-data-host-0
```
When I give /home/, /home/d and /home/d/data mode 777, and insert this into kubernetes, it does not work, since the privileges to access the volume are not sufficient.  I have to change `privileged: false` to `privileged: true`.

Perhaps `podman generate kube` shall accept more command line opitons to know how to emit yaml.
