### ISSUE TITLE
podman generate kube emits reduntant runAsGroup/runAsUser entries

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11914]
I build my image with `USER 2000:2000` and this information is contained in the oci-image.  `podman generate kube CONTAINERNAME` prints:
```
apiVersion: v1
kind: Pod
spec:
  containers:
    securityContext:
      …
      runAsGroup: 2000
      runAsUser: 2000
```
SInce the group and user UID are inherited from the container description, `podman generate kube` shall not print them, as long as the caller of podman has not passed `--ueser` parameter.  Kubernetes will anyway apply 2000:2000 when executing the container.
```
$ podman version
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 21:40:21 2021
OS/Arch:      linux/amd64
```
