### ISSUE TITLE
generate kube -s: do not insert annotations for the bind in the service yaml

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11929]
I run a podman container as described at https://mail.aegee.org/cgit/aegee-ldap/tree/readme.md#n13 .  Then call `podman generate kube -s busy_mclaren`.  The output is:

```
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.0
apiVersion: v1
kind: Service
metadata:
  annotations:
    bind-mount-options:/home/d/data: Z
  creationTimestamp: "2021-10-12T05:51:48Z"
  labels:
    app: busymclaren
  name: busymclaren
spec:
  ports:
  - name: "3890"
    nodePort: 31091
    port: 3890
    protocol: TCP
    targetPort: 0
  selector:
    app: busymclaren
  type: NodePort
status:
  loadBalancer: {}
```

Apart from the fact, that the annotation is syntactically not accepted by `kubelet apply -f`, such annotations have nothing to do with the Service and therefore shall not be emitted.
