### ISSUE TITLE
genetare kube -s: `targetPort: 0` is not valid

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11930]
I run a container as described at https://mail.aegee.org/cgit/aegee-ldap/tree/readme.md#n13, then call `podman generate kube -s busy_mclaren`.  The Service without the bind-annotation is:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    bind-mount-options:/home/d/data: Z
  creationTimestamp: "2021-10-12T06:04:20Z"
  labels:
    app: busymclaren
  name: busymclaren
spec:
  ports:
  - name: "3890"
    nodePort: 30831
    port: 3890
    protocol: TCP
    targetPort: 0
  selector:
    app: busymclaren
  type: NodePort
status:
  loadBalancer: {}
```
It says targetPort:0 , but according to https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/ the targetPort number must be between 1 and 65535.

I insert the file and kubernetes and then get it with `kubeclt describe it with
```
$ kubectl describe svc busymclaren 
Name:                     busymclaren
Namespace:                default
Labels:                   app=busymclaren
Annotations:              <none>
Selector:                 app=busymclaren
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.106.200.22
IPs:                      10.106.200.22
Port:                     3890  3890/TCP
TargetPort:               3890/TCP
NodePort:                 3890  30572/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

As can be seen, `targetPort:0` from the input is ignored.
