### ISSUE TITLE
generate kube -s: do not print entries with value `{}`

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11998]
I run a container as described at https://mail.aegee.org/cgit/aegee-ldap/tree/readme.md#n13.  Then I call `podman generate kube -s <ID>`:
```
apiVersion: v1                                                      
kind: Service             
status:                       
  loadBalancer: {}
---
apiVersion: v1
kind: Pod    
spec:
  containers:
  - resources: {}
    securityContext:
      seLinuxOptions: {}
  dnsConfig: {}
status: {}
```
As these `{}` lines have no added value, they shall not be emitted.

**Comment by rhatdan** [comment]
https://github.com/containers/podman/pull/12021 Should get rid of
      seLinuxOptions: {}
  dnsConfig: {}

**Comment by dilyanpalauzov** [comment]
podman generate kube -s still prints:
```
apiVersion: v1                                                      
kind: Service             
status:      
  loadBalancer: {}      

apiVersion: v1              
kind: Pod 
spec:
  containers:
  - resources: {}
status: {}
```
