### ISSUE TITLE
play kube: missing documentation for what is supported and what is not

### ISSUE THREAD

**Issue by ydayagi** [containers/podman#12756]
/kind bug

**Description**

I am trying to use podman play kube. It seems that there are some features that are not supported. I could not find documentation that explained the supported sections for pod kind.
Specifically, I am trying to use environment variables with a value from fieldRef.
Pod spec example:
```yml
spec:
  containers:
  - name: dummypod
    image: quay.io/fedora/fedora:34
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 3600; done;" ]
    env:
      - name: fieldRefVar
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
```
