### ISSUE TITLE
podman generate kube does not generate `env:` variable

### ISSUE THREAD

**Issue by Taymindis** [containers/podman#12781]
/kind bug

Description

## Steps to reproduce the issue:
```
podman run --name simple-nginx -e ABCUSER="xxx" --pod service-lab -d nginx
podman generate kube service-lab

```

### output

```yml
 Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-01-09T15:48:20Z"
  labels:
    app: service-lab
  name: service-lab
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:latest
    name: simple-nginx
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  restartPolicy: Never
status: {}

```

env `ABCUSER` variable not found

```
podman --version
podman version 3.4.4

```
