### ISSUE TITLE
podman generate kube not respect container HOSTNAME and port

### ISSUE THREAD

**Issue by Taymindis** [containers/podman#13030]
I intended to create a pod with no host and no network sharing.

```
podman pod create --name cassandra-pod --share cgroup,ipc

```

Now trying to attach the container to the pod with hostname ss_02
```
podman run --name ss_02  --pod cassandra-pod --hostname ss_02  -p 9043:9042 -p 8000:7000  -d cassandra:4.0.1

podman generate kube cassandra-pod
```
(derived from partial), no port mapping, no hostname mapping (instead, it put as Env HOSTNAME????)
```
 - args:
    - cassandra
    - -f
    env:
    - name: HOSTNAME
      value: ss02
    image: cassandra:4.0.1
    name: ss02
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE

```

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by rhatdan** [comment]
@umohnani8 Any progress?

**Comment by umohnani8** [comment]
@Taymindis I tried this out and the port mappings are being set correctly in the generated yaml for me, here is a snippet 
```
...
containers:
  - command:
    - sleep
    - "1000"
    image: registry.fedoraproject.org/fedora:latest
    name: namess02
    ports:
    - containerPort: 7000
      hostPort: 8000
    - containerPort: 9042
      hostPort: 9043
    resources: {}
...
```

Can you try the latest podman and see if that works for you?

I am also not seeing the hostname being set as an ENV, but will open a PR to set it correctly to the pod spec's hostname.
