### ISSUE TITLE
play kube: name collisions for containers within the same pod spec

### ISSUE THREAD

**Issue by arielireni** [containers/podman#13332]
/kind bug

**Description**

play kube API does not handle name collisions for containers within the same pod spec.

While trying to deploy a pod that contains two containers with the same name:
```
  pod:
    spec:
      containers:
        - name: test1
          image: quay.io/aireni/my-image:latest
        - name: test1
          image: quay.io/aireni/my-image:latest
```

I didn't receive an error and only one container was created:
```
     "Containers": [
          {
               "Id": "3395bd092a62813c10bc29f4333ec8e177ac4b761638c5fbf0197d42b8291d66",
               "Name": "podman-test-test1",
               "State": "running"
          }
       ]
```

When I tried to create the same pod without kube play, k8s validated this rule and I received an error:
```
→ oc apply -f /tmp/workload.yaml
The Pod "test" is invalid: spec.containers[1].name: Duplicate value: "test1" 
```

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 23:45:07 2021
OS/Arch:      linux/amd64
```
