### ISSUE TITLE
Cannot determine if a container was unable to start

### ISSUE THREAD

**Issue by paralin** [containers/podman#13729]
/kind feature

**Description**

Say I execute a pod with the following pod spec:

```yaml
        restartPolicy: OnFailure
        containers:
        - image: docker.io/library/alpine:edge
          name: hello
          args:
          - efcho
          - Hello world
          tty: true
```

The resulting container, of course, cannot start:

```
podman start container-id
Error: unable to start container "container-id": crun: executable file `efcho` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

... due to command not found.

However, this error does not appear anywhere in the "podman inspect" output:

```json
[
     {
          "State": {
               "OciVersion": "1.0.2-dev",
               "Status": "created",
               "Running": false,
               "Paused": false,
               "Restarting": false,
               "OOMKilled": false,
               "Dead": false,
               "Pid": 0,
               "ExitCode": 0,
               "Error": "",
               "StartedAt": "0001-01-01T00:00:00Z",
               "FinishedAt": "0001-01-01T00:00:00Z",
               "Health": {
                    "Status": "",
                    "FailingStreak": 0,
                    "Log": null
               },
               "CheckpointedAt": "0001-01-01T00:00:00Z",
               "RestoredAt": "0001-01-01T00:00:00Z"
          }
     }
]

```

... the container just appears as "created" and there's no way to distinguish why it failed.

**Describe the results you received:**

What is the correct way to check if a container is in this kind of failed state via the API, and how to get the error message?

Is the best way to just check if the container is in "created" state, try to start it via api, and check for an error?

**Describe the results you expected:**

This seems like a bit of a hack/workaround, it'd be best if the error was in the container status somewhere.
