### ISSUE TITLE
Podman v3.4.2 compose networks block does not update MTU size

### ISSUE THREAD

**Issue by rskntroot** [containers/podman#14471]
The following command works fine:

`podman network create test_default --opt mtu=9000` 
as referenced by:
_Originally posted by @afbjorklund in https://github.com/containers/podman/issues/8454#issuecomment-733172431_

However the expected compose.yml variation:

```
..
networks:
  default:
    driver: bridge
    driver_opts:
      mtu: 9000
```
Does not work as expected.  The mtu is not set for the network that is created.

I have also attempted to use the docker string..

```
..
    driver_opts:                         
      com.docker.network.driver.mtu: 9000
```

Which also fails.  The mtu is not set for the network that is created.
