### ISSUE TITLE
Container restart issue post rebooting the server

### ISSUE THREAD

**Issue by jainamtrivedi-crest** [containers/podman#14714]
/kind bug

I have created services from: https://github.com/docker/awesome-compose/tree/master/nginx-flask-mongo. 
![image](https://user-images.githubusercontent.com/77317274/175343978-4a0068db-7516-49c0-b39d-f8f600fe409e.png)
I have changed the yml file a bit so that all the container start automatically on their own after rebooting the VM.  Added 
`restart: always` policy to reflect it.

compose.yml file: 
``` 
version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: flask
    restart: always
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo
  mongo:
    image: mongo
    restart: always
```

All  the containers are running smoothly and I was able to curl the nginx service.
![image](https://user-images.githubusercontent.com/77317274/175344595-cd6cd103-5d70-43e2-96e2-d4871dee41a8.png)

For restart policy, podman is already providing `podman-restart` systemd file which will automatically start all the exited containers which have restart policy `restart: always`. I have enable that systemd file and it is successfully loaded. 
podman-restart.service:
```
[Unit]
Description=Podman Start All Containers With Restart Policy Set To Always
Documentation=man:podman-start(1)
StartLimitIntervalSec=0

[Service]
Type=oneshot
RemainAfterExit=true
Environment=LOGGING="--log-level=debug"
ExecStart=/usr/bin/podman $LOGGING start --all --filter restart-policy=always

[Install]
WantedBy=default.target
```

After rebooting the server I am able to see all the pods up and running but they are not able to communicate with each other. I suspect it is due to networking. curl command is showing timeout error.

Podman verison: `4.0.2`
podman-compose version: `1.0.3`

I have installed podman-plugins for networking. So that, pods can communicate via CNI.
