### ISSUE TITLE
deadlock(?) in podman rm(?)

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14929]
Sorry, I really don't know what happened nor how to even report it. While testing #14772 my podman got stuck, and remains stuck. It looks like a deadlock. I don't actually know where it stuck in `apiv2` tests, but _think_ it's in a DELETE. I was able to run a `ps`:
```console
$ bin/podman --root /dev/shm/test-apiv2.tmp.ZK2Ovh/server_root --runroot /run/user/14904/containers ps -a
CONTAINER ID  IMAGE                                        COMMAND     CREATED        STATUS                      PORTS       NAMES
ef964cc9f594  localhost/podman-pause:4.2.0-dev-1657739704              6 minutes ago  Exited (137) 6 minutes ago              dbdb45542af1-infra
36f1f1caf0d2  quay.io/libpod/alpine_labels:latest                      6 minutes ago  Stopping                                gallantmahavira-pod-gallantmahavira
```
...but `rm` has hung for at least ten minutes:
```console
$ bin/podman --root /dev/shm/test-apiv2.tmp.ZK2Ovh/server_root --runroot /run/user/14904/containers rm -f -a
```
`lsof` pointed me at `/dev/shm/libpod_rootless_lock_MYUID`, which surprised me because I would expect all the `--root/--runroot` args to use a different lockfile. The four processes shown by lsof are (edited for clarity):
```
    podman system service    <---- this is apiv2 tests
    podman [lots of args I never added] container cleanup ef9... [SHA of the podman-pause container above]
    podman [lots of args I never added] container cleanup 36f... [SHA of the alpine_labels container above]
    podman rm -f -a        <--- this is the "rm" that I ran on the command line
```
Couldn't think of anything else to check, so I `kill`ed (TERM) all the processes, and have my system back now.

**Comment by vrothberg** [comment]
I try to take a look today.

@edsantiago, `kill -SIGABRT` will let go print a stack trace which can be extremely useful for such deadlocks.

**Comment by vrothberg** [comment]
Also happens locally.  An easy reproducer:
`./bin/podman kube play ~/kube.yaml && ./bin/podman kube play --down ~/kube.yaml`

With `~/kube.yaml`:
```
apiVersion: v1                                                
kind: Pod                                                     
metadata:                                                     
  annotations:                                                
    io.kubernetes.cri-o.TTY/gallantmahavira: "false"          
    io.podman.annotations.autoremove/gallantmahavira: "FALSE" 
    io.podman.annotations.init/gallantmahavira: "FALSE"       
    io.podman.annotations.privileged/gallantmahavira: "FALSE" 
    io.podman.annotations.publish-all/gallantmahavira: "FALSE"
  creationTimestamp: "2022-07-13T11:35:48Z"                   
  labels:                                                     
    app: gallantmahavira-pod                                  
  name: gallantmahavira-pod                                   
spec:                                                         
  containers:                                                 
  - image: docker.io/library/alpine:latest                    
    name: gallantmahavira                                     
    securityContext:                                          
      capabilities:                                           
        drop:                                                 
        - CAP_MKNOD                                           
        - CAP_NET_RAW                                         
        - CAP_AUDIT_WRITE                                     
```

It smells like another exit-code issue.
