### ISSUE TITLE
play kube: invalid character 'N' looking for beginning of value

### ISSUE THREAD

**Issue by 1player** [containers/podman#15071]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`play kube` error in latest HEAD

**Steps to reproduce the issue:**

```
cat <<EOF >manifest.yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
EOF
```

1. `podman play kube ./manifest.yml`

**Describe the results you received:**

```
Error: ./manifest.yml: invalid character 'N' looking for beginning of value
```

**Additional information you deem important (e.g. issue happens only occasionally):**

On stable version (tested tag `v4.1.1`) I get this error instead: 

```
Error: ./manifest.yml: error playing YAML file: short-name resolution enforced but cannot prompt without a TTY
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.18.4
Git Commit:   a298909decc9091da8cc134e6eb2f38a70635a30
Built:        Tue Jul 26 12:08:11 2022
OS/Arch:      linux/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 17:17:44 2022
OS/Arch:      linux/amd64
```
