### ISSUE TITLE
How to include multiple hostAliases in yml file?

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#15418]
### Discussed in https://github.com/containers/podman/discussions/15386

<div type='discussions-op-text'>

<sup>Originally posted by **NeilDavisNPS** August 19, 2022</sup>
Hello,

I have the following snippet in a yml file:
```
hostAliases:
  - ip: "10.0.1.74"
    hostnames:
    - "mysql"
  - ip: "10.0.1.150"
    hostames:
    - "my.server.com"
```
When I run 
```
podman play kube compose.yml
```
the resulting container's host file is populated with only the first alias (mysql).
Is this expected?

Here's the podman version info
```podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.12
Built:        Thu Aug  4 00:36:19 2022
OS/Arch:      linux/amd64```

Cheers.</div>

**Comment by rhatdan** [comment]
This looks like a bug.
@umohnani8 PTAL

**Comment by umohnani8** [comment]
I tested this on podman v4.2 + upstream podman and the issue has been fixed in the latest version.

Here is the yaml I tested with 
```
apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
    - "bar.local"
  - ip: "10.1.2.3"
    hostnames:
    - "foo.remote"
    - "bar.remote"
  containers:
  - name: cat-hosts
    image: alpine
    command:
    - sleep
    - "1000"
```

With podman play kube, the /etc/hosts file in the container has both hostAlias entries from the kube yaml

```
➜  podman git:(4.2) ✗ ./bin/podman play kube host-alias.yaml 
Pod:
72eec3da4558b26b120a31c970b3552122b0d18341c4e2590e1cef2f5988c352
Container:
d8ccd6780774823a02b5c595c77884c885e1b1aff7ace736e41006d3dd2d7a8e

➜  podman git:(4.2) ✗ podman ps
CONTAINER ID  IMAGE                                    COMMAND     CREATED        STATUS            PORTS       NAMES
2f8074e0f4c9  localhost/podman-pause:4.2.0-1661397588              4 seconds ago  Up 4 seconds ago              72eec3da4558-infra
d8ccd6780774  docker.io/library/alpine:latest                      3 seconds ago  Up 4 seconds ago              hostaliases-pod-cat-hosts
➜  podman git:(4.2) ✗ ./bin/podman exec -it d8cc sh
/ # cat /etc/hosts
127.0.0.1       foo.local
127.0.0.1       bar.local
10.1.2.3        foo.remote
10.1.2.3        bar.remote
...

✗ ./bin/podman version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.16.15
Git Commit:   7fe5a419cfd2880df2028ad3d7fd9378a88a04f4
Built:        Wed Aug 24 23:19:48 2022
OS/Arch:      linux/amd64
```

Are there any other entries that are expected?
