### ISSUE TITLE
Support `kind: List`

### ISSUE THREAD

**Issue by jelly** [containers/podman#15694]
/kind feature

**Description**

Currently `kind: List` is not supported. It can be worked around by putting a separator between `kind: Pod` using `---` in yaml but it would still be nice to support it.
```
---
apiVersion: v1
kind: List
items:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ws-config
  data:
    cockpit.conf: |
      [Webservice]
      UrlRoot=/wss/cockpit-9090/
      Origins = https://test.cloud.redhat.com
      AuthorizationHeader = X-Cockpit-Authorization

      [Basic]
      command = /usr/local/bin/nc-authsock-session.sh

      [Negotiate]
      action = none

- kind: Pod
  apiVersion: v1
  metadata:
    name: cockpit-cloud-pod
    labels:
      infra: cockpit-cloud
  spec:
    restartPolicy: Never
    containers:
      - name: cockpit-cloud
        image: quay.io/rhn_engineering_mpitt/ws
        ports:
          - name: session
            containerPort: 8080
          - name: cockpit
            containerPort: 9090
        volumeMounts:
          - name: ws-config
            mountPath: /etc/cockpit/
            readOnly: true
        command: [ "sh", "-ec", "websocat -b ws-listen:0.0.0.0:8080 unix-listen:/tmp/authsock & /usr/libexec/cockpit-ws --for-tls-proxy" ]
        # start ws or other debugging tools by hand:
        # command: [ "sleep", "infinity" ]
    volumes:
      - name: ws-config
        configMap:
          name: ws-config

- kind: Service
  apiVersion: v1
  metadata:
    name: cockpit-cloud-service
  spec:
    ports:
    - name: session
      targetPort: 8080
      port: 8080
      protocol: TCP
    - name: cockpit
      targetPort: 9090
      port: 9090
      protocol: TCP
    selector:
      infra: cockpit-cloud
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Alternatively use `---` like in here https://github.com/jelly/console.dot/pull/3/files#diff-91a3da0d72969813731500687228a911c62a6782178003ae17730be6a2fd63fd

**Output of `podman version`:**

```
podman version 4.2.0
```
