### ISSUE TITLE
Map host user to rootless container socket

### ISSUE THREAD

**Issue by eliteaz** [containers/podman#16181]
Have a simple podman container running php-fpm
with such a compose yaml
```
services:
  php-fpm:
    build: .
    volumes:
        - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        - ./phpsocket:/var/run/php
```
after successfully container setup has such a socket file with those permissions:
```
[user@localhost]$ ls -la phpsocket/
total 8
drwxr-xr-x. 2 cogen cogen 4096 Oct 14 08:29 .
drwxr-xr-x. 3 cogen cogen 4096 Oct 14 07:53 ..
srw-rw----. 1           100999           100999    0 Oct 14 08:29 www-fpm.sock
```
inside container socket owns seprately created **nginx** user
```
root@765d98a6f78a:/var/www/html# grep nginx /etc/passwd
nginx:x:1000:1000:nginx user,,,:/nonexistent:/bin/false

root@765d98a6f78a:/var/www/html# ls -la /run/php/www-fpm.sock 
srw-rw----. 1 nginx nginx 0 Oct 14 12:10 /run/php/www-fpm.sock
```

Is there any possibility to map my host's nginx user into container's socket ?
now nginx get socket permission denied during http requests
host's nginx user id 
```
[root@localhost]# grep nginx /etc/passwd
nginx:x:987:987:Nginx web server:/var/lib/nginx:/sbin/nologin
[root@localhost]# grep nginx /etc/group
nginx:x:987:
```

Even I change socket permissions to `srw-rw-rw-. 1 100999 100999 0 Oct 14 12:10 /run/php/www-fpm.sock`
nginx get permission denied.
selinux also disabled
Maybe there is some capabilities sharing socket ?
