### ISSUE TITLE
[Bug]: Disable automatic publishing of all ports for kube play

### ISSUE THREAD

**Issue by Syquel** [containers/podman#17028]
### Feature request description

Currently `podman kube play` automatically publishes all ports which are defined in Kubernetes YAMLs as `containerPort`.

Kubernetes YAML example:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: all-ports-published-reproducer
spec:
  containers:
    - name: all-ports-published-reproducer-nginx
      image: "docker.io/bitnami/nginx:1.23"
      env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8082"
      ports:
        - name: http
          containerPort: 8082
```

Podman command: `podman kube play all-ports-published-reproducer.yaml`

Output of `podman port --latest`: `8082/tcp -> 0.0.0.0:8082`

Users should be able to disable this behavior to prevent accidentally publishing ports to the outside world.  

### Suggest potential solution

Similiarly to #16880 a new flag `--publish-all` like the one in [podman run](https://docs.podman.io/en/latest/markdown/podman-run.1.html#publish-all-p) should be added to `podman kube play`.  
This flag should accept a boolean parameter which is `true` by default to preserve the current behavior.

If `--publish-all=false` is set ports should not be automatically published and only be published if the Kubernetes YAML explicitly defines the `hostPort` field.

Kubernetes YAML example with explicit `hostPort` set.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: all-ports-published-reproducer
spec:
  containers:
    - name: all-ports-published-reproducer-nginx
      image: "docker.io/bitnami/nginx:1.23"
      env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8082"
      ports:
        - name: http
          containerPort: 8082
          hostPort: 80
```

### Have you considered any alternatives?

Podman Quadlets would be an alternative but would prevent users from using already existing Kubernetes YAMLs / Helm charts.

### Additional context

#16766 introduces a change to publish ports on a random port instead of reusing the `containerPort` field of the Kubernetes YAML if `hostPort` is not set.  
If the new flag `--publish-all` is set to `false` and the `hostPort` field is explicitly set to `0` the port should be published on a random port.

Even if firewalld is active on the server netavark currently allows these automatically published ports to be reachable from the outside world, which might be a security concern.

**Comment by Syquel** [comment]
Any thoughts on my proposal?

**Comment by rhatdan** [comment]
@ygalblum @vrothberg @umohnani8 @haircommander @saschagrunert PTAL

**Comment by ygalblum** [comment]
SGTM
In K8S listing the ports is only informative and as a result, users tend to list them even if they are not meant to be exposed. Furthermore, while the example provided here uses 8082 as the `containerPort`, the issue becomes even more required when the `containerPort` is a privileged one. Not being able to not publish the port forces the user to explicitly set a different port when running as rootless.
So, a port should be published if:
- The YAML file includes a `hostPort`
- The port is published via `--publish`
- `publish-all` is true (default behavior to maintain the current behavior)
As a result, the user will be able to block the publishing of a port listed in the YAML file by not setting `hostPort`, not publishing via `--publish` and setting `--publish-all=false`

**Comment by haircommander** [comment]
this SGTM too

**Comment by saschagrunert** [comment]
Agreed, SGTM

**Comment by rhatdan** [comment]
@ygalblum @umohnani8 care to work on this?

**Comment by MarkoH17** [comment]
Just checking whether this feature will allow k8s deployments where containers expose the same `containerPort`? 

Sample `kube.yaml`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  template:
    metadata:
      name: test-app
      labels:
        &a1
        app: test-app
    spec:
      containers:
        - name: nginx-web
          image: docker.io/library/nginx
          ports:
            - containerPort: 80
              hostPort: 8080
        - name: httpd-web
          image: docker.io/library/httpd
          ports:
            - containerPort: 80
              hostPort: 8081
  selector:
    matchLabels: *a1
```

Running `podman kube play kube.yaml` results in the creation of the pods, but since podman tries to bind both `containerPort`'s to the host, one of the pods ends up throwing an `Address already in use` error.
