### ISSUE TITLE
[Bug]: podman kube play does not list secrets

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#17071]
### Issue Description

Running `podman kube play` on a K8s YAML with a secret will create the secret but not print anything on the terminal.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run the following YAML:
```YAML
apiVersion: v1              
kind: Secret                
metadata:                   
  name: newsecret           
type: Opaque                
data:                       
  username: dXNlcg==        
  password: NTRmNDFkMTJlOGZh
```

### Describe the results you received

No output.

### Describe the results you expected

The ID of the created secret.

### podman info output

```shell
Latest HEAD and 4.3.1.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
