### ISSUE TITLE
`kube generate` emits warnings and uses CRI-O-specific annotations

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#17105]
While working a tutorial for `kube generate` I noticed a number of annoying warnings caused mostly by the use of CRI-O-specific annotations which is not a nice user experience.

Easily reproducible with the following patch:
```diff
diff --git a/test/system/710-kube.bats b/test/system/710-kube.bats                            
index 945d8d735c47..eb6bd6909a8b 100644                                                       
--- a/test/system/710-kube.bats                                                               
+++ b/test/system/710-kube.bats                                                               
@@ -33,6 +33,7 @@ json.dump(yaml.safe_load(sys.stdin), sys.stdout)'                           
     cname=c$(random_string 15)                                                               
     run_podman container create --cap-drop fowner --cap-drop setfcap --name $cname $IMAGE top
     run_podman kube generate $cname                                                          
+    assert "$output" !~ "Kubernetes only allows 63 characters"                               
                                                                                              
     # Convert yaml to json, and dump to stdout (to help in case of errors)                   
     json=$(yaml2json <<<"$output")                                                           
```

Running the test you will get a number of warnings on truncating the annotations and that `Kubernetes only allows 63 characters`.

This bears the question: Why use these annotations if they are truncated and hence lose meaning?

The upper tests will generate the following annotations:
```YAML
annotations:                                                                                                             
  io.kubernetes.cri-o.ContainerType/c2SoHwlDTDZLZDXJm: container                                                         
  io.kubernetes.cri-o.ContainerType/c16p9MF2WI27Wqa9P: container                                                         
  io.kubernetes.cri-o.SandboxID/c2SoHwlDTDZLZDXJm: 60c71cb07d3290eefc976f2b1a04f2ff27d17a7ae897451d4f2ac1dc23b13cd       
  io.kubernetes.cri-o.SandboxID/c16p9MF2WI27Wqa9P: 60c71cb07d3290eefc976f2b1a04f2ff27d17a7ae897451d4f2ac1dc23b13cd       
  io.kubernetes.cri-o.TTY/c2SoHwlDTDZLZDXJm: "false"                                                                     
  io.kubernetes.cri-o.TTY/c16p9MF2WI27Wqa9P: "false"                                                                     
  io.podman.annotations.autoremove/c2SoHwlDTDZLZDXJm: "FALSE"                                                            
  io.podman.annotations.autoremove/c16p9MF2WI27Wqa9P: "FALSE"                                                            
  io.podman.annotations.init/c2SoHwlDTDZLZDXJm: "FALSE"                                                                  
  io.podman.annotations.init/c16p9MF2WI27Wqa9P: "FALSE"                                                                  
  io.podman.annotations.privileged/c2SoHwlDTDZLZDXJm: "FALSE"                                                            
  io.podman.annotations.privileged/c16p9MF2WI27Wqa9P: "FALSE"                                                            
  io.podman.annotations.publish-all/c2SoHwlDTDZLZDXJm: "FALSE"                                                           
  io.podman.annotations.publish-all/c16p9MF2WI27Wqa9P: "FALSE"                                                           
  org.opencontainers.image.base.digest/c2SoHwlDTDZLZDXJm: sha256:36d93dbf1cf35346effba973a726cd4ba19a967b68c3ce03bde0c112
  org.opencontainers.image.base.digest/c16p9MF2WI27Wqa9P: sha256:36d93dbf1cf35346effba973a726cd4ba19a967b68c3ce03bde0c112
  org.opencontainers.image.base.name/c2SoHwlDTDZLZDXJm: localhost/interim-image:latest                                   
  org.opencontainers.image.base.name/c16p9MF2WI27Wqa9P: localhost/interim-image:latest                                   
```

* The Podman-specific annotations shouldn't be set since they are set "FALSE". 
* The CRI-O-specific ones should probably be not used at all.  What if users want to deploy it to a containerd node?  The Podman-specific annotations are extensions to enable certain feature in `kube play`, so we cannot entirely delete them (unless set false).
* The OCI `image.base` annotations shouldn't be there as well. Those relate to some image and the sha256 is exceeding the 63 character limit.

But before changing anything I want to figure out why all the (CRI-O) annotations were set?  I feel like I am missing (historic) context.  Can we delete https://github.com/containers/podman/blob/main/pkg/annotations/annotations.go?

@umohnani8 @rhatdan PTAL
