### ISSUE TITLE
[Bug]: kube generate ignores --read-only-tmpfs=

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#17368]
### Issue Description

I run my container once with

> /usr/local/bin/podman run --cap-add=IPC_LOCK --log-driver=none --net=host --read-only --read-only-tmpfs=false --mount type=bind,src=/etc/k,dst=/conf --rm=true -a=stderr -a=stdout -a=stdin --userns=auto:size=10 --name=k --tty localhost/k:2023-01-25

and once with

> /usr/local/bin/podman run --cap-add=IPC_LOCK --log-driver=none --net=host --read-only --read-only-tmpfs=true --mount type=bind,src=/etc/k,dst=/conf --rm=true -a=stderr -a=stdout -a=stdin --userns=auto:size=10 --name=k --tty localhost/k:2023-01-25

The difference is the value of `--read-only-tmpf`.  After each run, I call `podman generate kube k` and compate the outputs of both `podman generate kube` invokations.  The only difference is metadata.creationTimestamp.

Therefore the option `--read-only-tmpf=true|false` is ignored by `podman generate kube`.

### Steps to reproduce the issue

see above

### Describe the results you received

see above

### Describe the results you expected

When the value of --read-only-tmpfs= changes, the output of `podman kube generate` should also change.

### podman info output

```yaml
APIVersion: 4.4.1-dev
  Built: 1675520042
  BuiltTime: Sat Feb  4 14:14:02 2023
  GitCommit: 9c5b249e126e8d999be8b2c342057bc3e3f5640b
  GoVersion: go1.19.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1-dev
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
