### ISSUE TITLE
[Feature]: Strip newlines when parsing kubernetes pod yaml hostPath paths

### ISSUE THREAD

**Issue by sedrubal** [containers/podman#17397]
### Feature request description

I made a mistake in the kubernetes pod yaml file. To format it nicely I wrapped the `hostPath` in named volumes using the `>` yaml symbol:

```yaml
...
  volumes:
    - name: foo
      hostPath:
        path: >  # note the misplaced > character here
          /very/long/long/long/long/long/path
        type: Directory
```

instead of

```yaml
...
  volumes:
    - name: foo
      hostPath:
        path:  # no > character
          /very/long/long/long/long/long/path
        type: Directory
```

which results in the path `/very/long/long/long/long/long/path\n` (final newline!) instead of `/very/long/long/long/long/long/path` after parsing the yaml. Podman complained about the non existent path (no such file or directory) but in the error message the `\n` was truncated, which made it very difficult to debug the issue.

### Suggest potential solution

Either truncate the final newline directly after parsing or show the final new line also in the error message.

### Have you considered any alternatives?

I could easily fix the issue after fining it by just remove the misplaced `>` symbol which I thought I need.
