### ISSUE TITLE
play kube liveness HTTPS probe does not skip the certificate verification

### ISSUE THREAD

**Issue by Not-Code** [containers/podman#17510]
### Issue Description

When performing podman play kube with a pod containing a livenessProbe using HTTPS get, the probe fails when the certificate is self-signed:

curl: (60) SSL certificate problem: unable to get local issuer certificate

This does not respect the kubelet documentation [https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/]:

> If scheme field is set to HTTPS, the kubelet sends an HTTPS request skipping the certificate verification

This is probably related to this file [https://github.com/containers/podman/blob/main/pkg/specgen/generate/kube/kube.go] where the probe is defined as:

`commandString = fmt.Sprintf("curl -f %s://%s:%d%s || %s", uriScheme, host, probeHandler.HTTPGet.Port.IntValue(), path, failureCmd)`

and should instead be:

`commandString = fmt.Sprintf("curl -kf %s://%s:%d%s || %s", uriScheme, host, probeHandler.HTTPGet.Port.IntValue(), path, failureCmd)`

### Steps to reproduce the issue

Steps to reproduce the issue
1. Start a pod with a self-signed certificate
2. Add a liveness HTTPS probe
3. podman inspect the pod

### Describe the results you received

The pod keeps restarting and a podman inspect shows an issue with SSL certificate verification:
curl: (60) SSL certificate problem: unable to get local issuer certificate

### Describe the results you expected

As per kubelet documentation the SSL certificate verification should be skipped.

### podman info output

```yaml
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by queria** [comment]
This affects not just self-signed certificates, but ones trusted by system but generated for different hostname (for example IP or external names vs usage of localhost or different ip), making it complicated to use httpGet in livenessProbe.

One possible workaround is to use command probe with custom curl parameters like:
```
        livenessProbe:
          exec:
            command:
              - /bin/curl
              - -kf
              - 'https://localhost:8080/healthz'
```
