### ISSUE TITLE
`kube generate` prints in Note:, which is not necessary applicable for the current case

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#17743]
### Issue Description

`podman generate kube myname` prints:

```
# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
```

Podman shall determine if it is run privileged, rootful, under SELinux -enabled system.  Based on its fidings, podman shall  adapt (shorten) the Note-message above.

### Steps to reproduce the issue

See above

### Describe the results you received

See above

### Describe the results you expected

See above

### podman info output

```yaml
# podman version
Client:       Podman Engine
Version:      4.4.3-dev
API Version:  4.4.3-dev
Go Version:   go1.19.3
Git Commit:   73ce3c61c1bcf22a26f0442f23bf19c2cfc24a82
Built:        Wed Mar  1 21:58:11 2023
OS/Arch:      linux/amd64
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
