### ISSUE TITLE
`generate kube` creates a truncation warning

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#17742]
### Issue Description

When I type `podman generate kube my-name` it prints
```
time="2023-03-12T08:58:33Z" level=warning msg="Truncation Annotation: \"sha256:a4e1aeea1ecc17ab70cfdc4297186d81812cb575b8c2eb60af15a4d76a7d6916\" to \"sha256:a4e1aeea1ecc17ab70cfdc4297186d81812cb575b8c2eb60af15a4d7\": Kubernetes only allows 63 characters"
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.3-dev

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    org.opencontainers.image.base.digest/my-name: sha256:a4e1aeea1ecc17ab70cfdc4297186d81812cb575b8c2eb60af15a4d7
    org.opencontainers.image.base.name/my-name: localhost/baseimg-glibc236:2023-01-27
…
```
There shall be no such warning (truncated sha256-hash value), as there is nothing the user can do with the warning.

The warning indicates, that podman was used in a wrong way, without stating what the right way should have been.

### Steps to reproduce the issue

See above

### Describe the results you received

No warning printed by `podman kube generate`.

### Describe the results you expected

See above

### podman info output

```yaml
# podman version
Client:       Podman Engine
Version:      4.4.3-dev
API Version:  4.4.3-dev
Go Version:   go1.19.3
Git Commit:   73ce3c61c1bcf22a26f0442f23bf19c2cfc24a82
Built:        Wed Mar  1 21:58:11 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
