### ISSUE TITLE
Conflicts with other wsl distributions

### ISSUE THREAD

**Issue by xuanxianyou** [containers/podman#17980]
### Issue Description

After upgrading to Podman version 4.4.4, My WSL another distribution (Debian) failed to start. Debian can only be started normally without starting podman.

### Steps to reproduce the issue

Steps to reproduce the issue
1. start podman
2. start Debian
3. The Debian start error: Error: 0x80040326
Error code: Wsl/Service/0x80040326

### Describe the results you received

The Debian start error: Error: 0x80040326
Error code: Wsl/Service/0x80040326

### Describe the results you expected

Expect Debian and Podman to run simultaneously on my Windows system

### podman info output

```yaml
Client:       Podman Engine
Version:      4.4.4
API Version:  4.4.4
Go Version:   go1.19.5
Git Commit:   c8223435f49a860c8ac4281a85db39232745a7cb
Built:        Tue Mar 28 04:12:38 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Thu Sep  8 03:58:19 2022
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
