### ISSUE TITLE
DNS: no servers could be reached in `rootless` network on WSL2

### ISSUE THREAD

**Issue by klesh** [containers/podman#18530]
### Issue Description

I tried both `Podman Desktop for Window` and `Podman4.5 in WSL2`  in `rootless`  mode, the DNS just didn't seem to be working.
```
> podman network create hello
hello
> podman network inspect hello
[
     {
          "name": "hello",
          "id": "998d23d8b357df4017297226e458e56f57f36f5c8a53ac37552a157ffcef6338",
          "driver": "bridge",
          "network_interface": "podman2",
          "created": "2023-05-10T12:48:20.796574327+08:00",
          "subnets": [
               {
                    "subnet": "10.89.1.0/24",
                    "gateway": "10.89.1.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
> podman run --rm --network=hello busybox nslookup baidu.com
;; connection timed out; no servers could be reached
```

However, it seems find under `rootful` mode:
```
[klesh@klesh-laptop] /e/apt> sudo podman network inspect hello
[
     {
          "name": "hello",
          "id": "3edf7f49c8f5da8bf24b65ea53cdc768013d5eaf1bca366daa8c4c7af2eed6bf",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2023-05-09T23:56:41.968028336+08:00",
          "subnets": [
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
[klesh@klesh-laptop] /e/apt> sudo podman run --rm --network=hello -it busybox nslookup baidu.com
Server:         10.89.0.1
Address:        10.89.0.1:53

Non-authoritative answer:

Non-authoritative answer:
Name:   baidu.com
Address: 39.156.66.10
Name:   baidu.com
Address: 110.242.68.66

[klesh@klesh-laptop] /e/apt>  
```

Am I missing sth?

### Steps to reproduce the issue

Steps to reproduce the issue
1. create network in `rootless` mode: `podman network create hello`
2. run `nslookup` for a valid domain: `podman run --rm --network=hello -it busybox nslookup baidu.com`

### Describe the results you received

 see error : `;; connection timed out; no servers could be reached`

### Describe the results you expected

recieve ip adddress of the given domain

### podman info output

```yaml
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.2
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a
Built:        Fri Apr 14 23:21:09 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 23:42:56 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
