### ISSUE TITLE
`podman info` should include info about Pasta

### ISSUE THREAD

**Issue by PhrozenByte** [containers/podman#18561]
### Feature request description

`podman info` is supposed to display Podman related system information. This includes information about networking. For this reason `podman info` also includes a section about e.g. `slirp4netns`, looking like the following:

```
host:
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
```

Right now there's no similar info about Pasta, Podman's new and promising rootless networking option. I suggest adding such section.

The use case is the same as for slirp4netns: To check whether Pasta is installed, whether it's usable and the exact version being used (one could run Pasta with an arbitrary version).

### Suggest potential solution

`podman info` should also include info about Pasta, e.g. like the following (feel free to add other related info):

```
host:
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230509.g96f8d55-1.fc38.x86_64
    version: |-
      passt version 2023_05_09.96f8d55-10-gf1e0a67
```

### Have you considered any alternatives?

n/a

### Additional context

n/a
