### ISSUE TITLE
podman doesn't start `aardvark-dns` when in an LXC container

### ISSUE THREAD

**Issue by abalmos** [containers/podman#18783]
### Issue Description

Inside an LXC container, podman does not start `aardvark-dns`. This breaks container DNS resolution when a podman network is used because podman still properly re-writes the containers `/etc/resolve.conf` to point to (expected to be running) `aardvark-dns`.

I do not see this issue when using a very similar environment, but on metal rather than an LXC.

After starting the `aardvark-dns` daemon by hand with `/usr/libexec/podman/aardvark-dns --config /run/containers/storage/networks/aardvark-dns -p 53 run`, everything works as expected for the remainder of the LXC container's lifetime.

I understand that this environment may not be available to the podman developers. I am willing to do some debugging, but so far I have not been able to identity any error or other logging which may indicate the issue.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Start (in my case) a Fedora 38 LXC container.
2. `podman network create test`
3. `podman run --rm -it --network test fedora:38 bash`
4. `getent hosts example.org` <-- this returns nothing.

Without the `--network` flag `getent hosts example.org` returns `2606:2800:220:1:248:1893:25c8:1946 example.org`.

After starting `aardvark-dns` with `/usr/libexec/podman/aardvark-dns --config /run/containers/storage/networks/aardvark-dns -p 53 run` on the host, then the DNS resolution works even with the `--network` flag on podman. 

### Describe the results you received

DNS resolution doesn't work.

### Describe the results you expected

DNS resolution to work.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

Fedora 38


Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.2
Built:        Fri Apr 14 15:42:22 2023
OS/Arch:      linux/amd64
```

I can not easily upgrade the environment to podman 4.5.1, but based on the changelog, I do not think this issue is addressed.
```


### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Within an LXC container.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
