### ISSUE TITLE
Docker compose fails to pull podman images

### ISSUE THREAD

**Issue by SureshGota** [containers/podman#18843]
### Issue Description

I am working on a windows and have installed Podman. Inside the default WSL created by Podman I have installed docker compose.

Here's my compose file,
```
version: "3.9"
services:
    configurationsService:
        image: "localhost/configurations"
        hostname: configurationsService
        ports:
          - "51005:51005"
        restart: always
```

```
**Docker Compose** version v2.15.1

**Podman Version**
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 21:12:56 2023
OS/Arch:      linux/amd64
```

### Steps to reproduce the issue

I have built the images using `podman build` command and I can see them when I list them as `podman images`. I am also able to run the images using `podman run` command. 
However when I run `docker-compose up` it fails while trying to pull the image
with the error `initializing source docker://localhost/configurations:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused`

if I remove the localhost prefix from my image name it tries to connect to docker.io and fails there as well.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Fails to pull the images from local machine.

### podman info output

```yaml
NA
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
