### ISSUE TITLE
Unable to view services under podman system command -- macos

### ISSUE THREAD

**Issue by echang0929** [containers/podman#18988]
### Issue Description

Looks like there is no "service" command for "podman system" on MacOS.

Pls refer to the question on stackoverflow: [Unable to view services under podman system command](https://stackoverflow.com/questions/71825864/unable-to-view-services-under-podman-system-command-macos)

### Steps to reproduce the issue

Command used to start service : podman system service --time 5 

### Describe the results you received

Describe the results you received
Error Response : Error: unknown flag: --time

### Describe the results you expected

No error

### podman info output

```yaml
podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Sat May 27 01:58:19 2023
OS/Arch:      linux/arm64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
