### ISSUE TITLE
~/.docker/config.json must exist for compatibility reasons

### ISSUE THREAD

**Issue by marcosdiez** [containers/podman#19107]
### Issue Description

on the mac, with podman 4.5.1, `skaffold build` was giving container authentication errors even after `podman login`.

The solution was

`ln -sf ~/.config/containers/auth.json ~/.docker/config.json`

obviously it took me 4 hours to find that out, so it that symlink could exist by default, others would benefit from it.

### Steps to reproduce the issue

1. use mac m1
2. install podman
3. install skaffold

### Describe the results you received

failed to fetch builder image [reacted]: initializing source docker:[reacted]: unable to retrieve auth token: invalid username/password: unknown: Authentication is required

### Describe the results you expected

it should download the image

### podman info output

```yaml
podman on macos m1 (Ventura 13.2.1)

Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Git Commit:   9eef30051c83f62816a1772a743e5f1271b196d7
Built:        Fri May 26 12:10:12 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri May 26 14:58:19 2023
OS/Arch:      linux/arm64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
