### ISSUE TITLE
`podman machine init` fails on Win10: `The handle is invalid`

### ISSUE THREAD

**Issue by pe224** [containers/podman#19126]
### Issue Description

Running `podman machine init` fails at varying locations with `The handle is invalid`:
```
$ podman machine init
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Import wird ausgeführt. Dieser Vorgang kann einige Minuten dauern.
The operation completed successfully.
Configuring system...
Error: could not configure systemd settings for guest OS: write |1: The handle is invalid.
```

The nature of the error changes when running `init` multiple times. Sometimes it fails after key generation, sometimes it fails with `Error: could not create a WSL MOTD for guest OS: write |1: The handle is invalid.`, or `Error: could not add wheel to sudoers: write |1: The handle is invalid.`, but always with `handle is invalid`.
Is it related to the [`wslPipe` commands](https://github.com/containers/podman/blob/f33a3bdc35e952b9381207df95b43690c09a1fdc/pkg/machine/wsl/machine.go#L517)?

### Steps to reproduce the issue

Steps to reproduce the issue
1. remove all podman-related WSL distributions
2. run `podman machine init`

### Describe the results you received

The podman machine WSL distribution is created
```
$ wsl -l -v
  NAME                      STATE           VERSION
* Ubuntu                    Stopped         2
  podman-machine-default    Stopped         2
```

but the podman machine is not
```
$ podman machine ls
NAME        VM TYPE     CREATED     LAST UP     CPUS        MEMORY      DISK SIZE
```

### Describe the results you expected

Podman machine is correctly created and can be started

### podman info output

```yaml
podman version 4.5.1


$ wsl --version
WSL-Version: 1.2.5.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.51
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.3086
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
