### ISSUE TITLE
"unknown flag: --arch" error with podman build

### ISSUE THREAD

**Issue by ByerRA** [containers/podman#19142]
### Issue Description

While trying to build an image for "arm64" using the "--arch=arm64" flag with "podman build" I get an error that "--arch" is an unknown flag.

I'm using Ubuntu 18.04 and podman was installed from the Ubuntu repository.

### Steps to reproduce the issue

Steps to reproduce the issue
1. sudo apt-get update && sudo apt-get install podman
2. podman build --squash-all --arch=arm64 -f Containerfile.rootfs -t test-image

### Describe the results you received

Error: unknown flag: --arch

### Describe the results you expected

Was expecting my build to run.

### podman info output

```yaml
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 14105665536
  MemTotal: 16687841280
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: robert-E6430s
  kernel: 5.4.0-150-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 33m 13.59s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/rbyer/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/rbyer/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/rbyer/.local/share/containers/storage/volumes
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release
 "
Yes

### Additional environment details

Ubuntu 18.04

### Additional information

If you just execute "podman build --arch=arm64" you get the same error, "Error: unknown flag: --arch"
