### ISSUE TITLE
`podman search --list-tags` disables `--format`

### ISSUE THREAD

**Issue by bo0ts** [containers/podman#19156]
### Issue Description

Calling `podman search` with `--list-tags` disables the `--format` modifier. There should be a warning that those options conflict or that shouldn't happen.

### Steps to reproduce the issue

Steps to reproduce the issue

Run `podman search docker.io/library/ubuntu --list-tags --format "{{.Name}}:{{.Tag}}"`

### Describe the results you received

```
NAME                      TAG
docker.io/library/ubuntu  10.04
docker.io/library/ubuntu  12.04
```

### Describe the results you expected

```
docker.io/library/ubuntu:10.04
docker.io/library/ubuntu:12.04
```
or a warning that `--format` is ignored.

### podman info output

```yaml
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Git Commit:   9eef30051c83f62816a1772a743e5f1271b196d7
Built:        Fri May 26 17:10:12 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri May 26 19:58:19 2023
OS/Arch:      linux/arm64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes
