### ISSUE TITLE
How do you create a macvlan network with explicit DNS servers?

### ISSUE THREAD

**Issue by antifuchs** [containers/podman#19169]
### Issue Description

In pre-netavark podman releases, it was possible to specify `--dns=9.9.9.10` when creating a container. In 4.5.0, I can still create the container with the `--dns` argument, but that has no effect: `/etc/resolv.conf` is created from the host regardless.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman network create media-test -d macvlan -o parent=v55toys --ipam-driver=host-local --subnet "10.0.5.0/24" --ip-range 10.0.5.225/28 --gateway "10.0.5.1" --dns 9.9.9.10` fails: "Error: cannot set NetworkDNSServers if DNS is not enabled for the network: invalid argument"
2. `podman network create media-test -d macvlan -o parent=v55toys --ipam-driver=host-local --subnet "10.0.5.0/24" --ip-range 10.0.5.225/28 --gateway "10.0.5.1"` without DNS servers succeeds, but then:
3. `podman run --network=media-test --dns=9.9.9.9 --rm ubuntu:latest cat /etc/resolv.conf` shows the host's DNS configuration. However:
4. `podman run --dns=9.9.9.9 --rm ubuntu:latest cat /etc/resolv.conf | grep 9.9.9.9` does work.

### Describe the results you received

(see repro)

### Describe the results you expected

I would have hoped to be able to set DNS servers for all drivers, regardless of whether they have DNS resolution enabled or not.

Even if you can't set the DNS servers on the network, I would have expected the container creation argument to have the desired effect of using the specified servers instead of the host's.

### podman info output

```yaml
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 7
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/docker/podman-storage
  graphRootAllocated: 210241560576
  graphRootUsed: 95477915648
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 86
  runRoot: /home/asf
  transientStore: false
  volumePath: /var/lib/docker/podman-storage/volumes
version:
  APIVersion: 4.5.0
  Built: 315532800
  BuiltTime: Mon Dec 31 19:00:00 1979
  GitCommit: ""
  GoVersion: go1.20.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

This is running on a physical machine running NixOS 23.05, with a macvlan I'm hoping to parent to a specific ethernet device.
