### ISSUE TITLE
Port mapping is ignored in Kubernetes

### ISSUE THREAD

**Issue by ryshoooo** [containers/podman#19164]
### Issue Description

When running podman in a Kubernetes pod, the publish directive (i.e. port mapping) is completely ignored and skipped. The network host mode is used instead.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Have a Kubernetes cluster running (v1.27.1+)
2. Deploy podman pod: (tested with v.4.5.1)
```
apiVersion: v1
kind: Pod
metadata:
  name: podman
spec:
  containers:
  - name: podman
    image: quay.io/podman/stable:latest
    command: ["sleep"]
    args: ["infinity"]
    securityContext:
      privileged: true
```
3. Exec into the container and start a service, f.e. `podman run -d -p 4534:8080 quay.io/keycloak/keycloak start-dev`
4. Try `curl localhost:4534`, it'll never appear. However `curl localhost:8080` will.

### Describe the results you received

It seems that the network host is assumed by some reason. The directive to publish ports is definitely understood, but the port mapping is ignored and instead direct port exposition of the container is done.

### Describe the results you expected

Port mapping to work. If it is expected behavior, then at least some documentation on how to achieve port mapping for podman running in Kubernetes.

### podman info output

```yaml
Same as in `quay.io/podman/stable:latest`
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Kubernetes v1.27.1 (EKS and AKS)
