### ISSUE TITLE
podman kube play support posix permissions for configmap volumes

### ISSUE THREAD

**Issue by n35k3nd1r** [containers/podman#19313]
### Feature request description

Kubernetes allows to set specific file permission via the attribute "defaultMode"
[https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume/](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume/)

> configMap.defaultMode (int32)
defaultMode is optional: mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.

Example Use case:
If one of the containers is started as "non-root" the access to the ConfigMap volume is limited.

### Suggest potential solution

According to kubernate's documentation include the feature.

### Have you considered any alternatives?

As workaorund you can change the rights via script in advance.

### Additional context
Example POD:

```
apiVersion: v1 
 kind: Pod
 metadata:
   name: *dummy*
 spec:
     containers:
     - name: *dummy*
       image: *dummy*
       volumeMounts:
       - name: volume-config
         mountPath: "/etc/config"
         readOnly: false
     volumes:
     - configMap:
         defaultMode: 438
         name: volume-config-file
         optional: false
       name: volume-config
```
