### ISSUE TITLE
podman-kube-play (1) misstating the degree to which pod.spec.volumes is supported

### ISSUE THREAD

**Issue by christian-2** [containers/podman#19318]
### Issue Description

[`podman-kube-play (1)`](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-kube-play.1.md.in) states the following restriction (in [`kubernetes_support.md`](https://github.com/containers/podman/blob/main/docs/kubernetes_support.md)): *Podman Kube Play Support* / *Pod Fields* / `volumes`: no.

But I have the following example up-and-running with Podman 4.3.1's `podman kube play` (under Debian 12.1; relevant excerpt from my manifest): 

```
apiVersion: apps/v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: my-volume
       mountPath: /mnt
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-volume
```

### Steps to reproduce the issue

lookup the documentation (see provided links) vs. inspect the provided manifest (esp. `volumes`)

### Describe the results you received

apparent mismatch between documentation and actual capabilities

### Describe the results you expected

documentation stating to what actual degree `pod.spec.volumes` is supported (it is apparently not zero)

### podman info output

```yaml
I'm running Podman 4.3.1 on Debian 12.1, and I am referring to the latest documentation in GitHub. (Further details from `podman info` should be irrelevant in this case.)
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

n/a

### Additional information

n/a
