### ISSUE TITLE
`docker-compose`: Passing gpu with `driver: cdi` is not supported

### ISSUE THREAD

**Issue by raldone01** [containers/podman#19338]
### Issue Description

May be related to https://github.com/containers/podman/issues/19330.
See also https://github.com/NVIDIA/nvidia-container-runtime/issues/190#issuecomment-1647961573.

CDI Support in Docker will be an experimental feature in the Docker 25 release.

It will support the following `docker-compose.yml` file:
```
version: '3.8'
services:
cdi_test: # this is not working
    image: ubuntu:20.04
    deploy:
      resources:
        reservations:
          devices:
           - driver: cdi
             device_ids:
                - nvidia.com/gpu=all
                - nvidia.com/gds=all
                - nvidia.com/mofed=all
    command:
      - bash
      - -c
      - |
        nvidia-smi -L
```

### Steps to reproduce the issue

Steps to reproduce:

Prerequisites:
* Have the NVIDIA Container Toolkit (e.g. v1.13.5) installed
* Have a v25 Docker daemon configured in experimental mode
* Have generated the CDI specification for NVIDIA GPUs by running `sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml --device-name-strategy=uuid`
* Make sure you are using the `podman-docker-emulation-daemon`

Observe the following `docker-compose.yml`:
```yml
version: '3.8'
services:
  nvidia_test: # this is not working
    image: ubuntu:20.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
    command:
      - bash
      - -c
      - |
        nvidia-smi -L
  runtime_test: # this is working
    image: ubuntu:20.04
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command:
      - bash
      - -c
      - |
        nvidia-smi -L
  cdi_test: # this is not working
    image: ubuntu:20.04
    deploy:
      resources:
        reservations:
          devices:
           - driver: cdi
             device_ids:
                - nvidia.com/gpu=all
                - nvidia.com/gds=all
                - nvidia.com/mofed=all
    command:
      - bash
      - -c
      - |
        nvidia-smi -L
```

Launch via `docker-compose up`.

### Describe the results you received

Only the runtime container works.

### Describe the results you expected

All three containers should show the same output.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 98.59
    systemPercent: 0.38
    userPercent: 1.02
  cpus: 72
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: argon
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.4.4-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 54521659392
  memTotal: 135022321664
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.5-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 42947567616
  swapTotal: 42947567616
  uptime: 21h 35m 45.00s (Approximately 0.88 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/main/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/main/.local/share/containers/storage
  graphRootAllocated: 857601998848
  graphRootUsed: 271414001664
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/main/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1685139594
  BuiltTime: Sat May 27 00:19:54 2023
  GitCommit: 9eef30051c83f62816a1772a743e5f1271b196d7-dirty
  GoVersion: go1.20.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

**Comment by nicoya** [comment]
Is this expected to work when using podman-compose? None of the three containers in the above docker-compose.yml seem to work for me, however I can get nVidia support in a container via a plain podman commandline:

```
$ podman run --rm --device nvidia.com/gpu=all ubuntu nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 2070 (UUID: GPU-336c5a8a-839f-69a8-08cf-e3fdcd01e019)
```

**Comment by raldone01** [comment]
Interesting.
for me the runtime_test is working.
Thing is I had the understanding that podma-dockee should be a fully compatible emulation so I consider this an issue.

**Comment by nicoya** [comment]
Got it working with this:

```
version: '3.8'
services:
  nvidia_test:
    image: ubuntu
    devices:
      - nvidia.com/gpu=all
    command:
      - bash
      - -c
      - |
        nvidia-smi -L
```

**Comment by itzsimpl** [comment]
For me, none of these `docker-compose.yml` approaches works, however I can get nVidia support in a container via a plain podman commandline.

**Comment by raldone01** [comment]
> nvidia_test:
>     image: ubuntu
>     devices:
>       - nvidia.com/gpu=all
>     command:
>       - bash
>       - -c
>       - |
>         nvidia-smi -L

When I try this I get the following: `Error response from daemon: container create: stat nvidia.com/gpu=all: no such file or directory`

What version of podman are you running?
Do you have any special configuration active?

**Comment by elezar** [comment]
@raldone01 if you could point me at the code for `podman-compose`, I could try to see what additions are required to add CDI support there. I would assume that this would need similar extensions to those made to the `--device` command line argument. Your error message indicates that the entries in `devices:` are being interpreted as device nodes.

Note that Docker does not yet support CDI devices and these will only be available in Docker 25. In addition, the mechanism to request these device in the compose YAML do not match your expectations.

**Comment by raldone01** [comment]
I configured the runtime using `sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml --device-name-strategy=uuid`. Afterwards podman containers with `sudo podman run -ti --rm --device=nvidia.com/gpu=all ubuntu:18.04 nvidia-smi -L` worked. I am pretty sure this uses cdi.

I will look into the link you sent on Friday.

**Comment by raldone01** [comment]
If anyone has a working podman/docker-compose yml with cdi please share it. As far as I know it is not supported.

**Comment by raldone01** [comment]
As far as I can tell all options in `/usr/share/containers/containers.conf` are commented out and I can't remember changing it.
I will try to get a reproduce script working using distrobox or something like that.
My default ´ociRuntime´ in ´podman info´ is ´crun´.
I just verified docker is not even installed on the machine.
I am using ´Docker Compose version 2.20.3´.

Does ´sudo docker run --rm -e NVIDIA_VISIBLE_DEVICES=all ubuntu nvidia-smi -L´ work for you?
´´´
❯ sudo docker run --rm -e NVIDIA_VISIBLE_DEVICES=all ubuntu nvidia-smi -L
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
GPU 0: NVIDIA T600 (UUID: GPU-STUFF)
GPU 1: NVIDIA GeForce GTX 1080 (UUID: GPU-STUFF)
´´´´

**Comment by rhatdan** [comment]
Can we close this issue now, since there is a workaround, or is there still something Podman needs to fix?

**Comment by rhatdan** [comment]
Does it work with rootful podman?  Is this more a case of rootless versus rootful?

**Comment by raldone01** [comment]
I got a bit of new information. I'm currently reworking the issue. I will provide a reproducible Distrobox script to better test the issue.
I have not tried it with rootless yet.
The issue still exists.
Should I update the issue itself or add a new comment.

**Comment by rhatdan** [comment]
Add a new comment.

**Comment by mrnerdhair** [comment]
I am experiencing the same issue here, using the standalone `docker-compose` 2.23.0. I can do `sudo podman run -ti --rm --device=nvidia.com/gpu=all ubuntu:18.04 nvidia-smi -L` successfully, but none of the above flavors of compose file work.

**Comment by jesulo** [comment]
Hi, is the some option for enable gpu using podman-compose.yml? regards

**Comment by ageisen2000** [comment]
I am still experiencing this issue.

**Comment by elezar** [comment]
@gautaz what docker compose does is map the `devices` section in the compose file to HostConfig modifications (specifically [`DeviceRequests`]https://github.com/moby/moby/blob/b8165a9cd1c2933906edc3d72624c707ca9289e7/api/types/container/hostconfig.go#L259) entries) that are interpreted by the Docker daemon. I am not sure how this interacts with Podman.

If someone could point me at the execution path from running `podman-compose` -- and how Podman is invoked -- we can identify where support for the `cdi` driver needs to be added.

**Comment by laurensV** [comment]
Maybe related to my problem: I am trying to use the Docker API to create a container on a remote podman server with GPU support. With docker this can be done with device requests, but this comment https://github.com/containers/podman/pull/21180#issuecomment-1927171385 suggests that podman is not handling data via device_requests.. How would I use the docker api to enable gpu support in podman?

**Comment by rhatdan** [comment]
Have you tried with podman 5.0, some fixes whent in to handle GPUs from remote API.

**Comment by gautaz** [comment]
@elezar @laurensV The way docker-compose/podman-compose are supposed to communicate with podman is in fact also unclear to me. As @elezar pointed out, docker-compose communicates with docker through the daemon API but, in my particular case, I am using podman in its original rootless design, which means, AFAIU, no daemon, no API access through a socket.

@rhatdan I guess your question was for @laurensV.
In the meantime, I have also tried podman 5 but I am hitting other difficulties that I need to fully understand. These difficulties are related to the fact that since version 5, podman uses pasta for its network layer and not slirp4netns anymore. The fact that the Linux distribution I am using (NixOS) does not support pasta adds another layer of difficulties ([this seems to be a work in progress though](https://github.com/NixOS/nixpkgs/pull/265409)).

**Comment by qdm12** [comment]
Any news on this? Podman 5.x.x on Ubuntu is for now unusable / too-unstable as @gautaz mentioned.

So back to using Podman 4.9.3:

With [`podman-compose`](https://github.com/containers/podman-compose), CDI devices work just fine using

```yml
devices:
  - nvidia.com/gpu=0
```

but unfortunately `podman-compose` does not support the `ipc` key so it cannot use more than 1 gpu (https://github.com/containers/podman-compose/issues/218), which makes it sort of useless in my situtation.

With `podman compose` using [the docker `compose` plugin v2.26.1](https://github.com/docker/compose/releases/tag/v2.26.1) under the hood, the `ipc` key is working (because `compose` knows about it), but then nothing works to passthrough even a single GPU. I've tried:

```yml
devices:
  - nvidia.com/gpu=0
```

```yml
deploy:
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: 1
          capabilities: [gpu]
```

and

```yml
environment:
  - NVIDIA_VISIBLE_DEVICES=nvidia.com/gpu=0
```

My guess is it's a compatibility issue with docker tooling and the Podman socket, since podman-compose does manage to work with CDI. It's docker-compose (Python one) and the `compose` plugin (the Go one) that don't work with Podman.
