### ISSUE TITLE
Extra quotes around the distribution name on some systems

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#19340]
### Issue Description

Due to a bug in the parsing of /etc/os-release, explicit quote (`"`) are not removed before being stored.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman info`
2.
3.

### Describe the results you received

```yaml
  distribution:
    distribution: '"rocky"'
    version: "9.2"
```

### Describe the results you expected

```yaml
  distribution:
    distribution: rocky
    version: "9.2"
```

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

The quotes around the version are supposed to be there, since it's a string and not a number

Noticed when looking at the podman info output of another (unrelated) podman bug report...
