### ISSUE TITLE
user containers have Permission denied on data

### ISSUE THREAD

**Issue by markg85** [containers/podman#19397]
### Issue Description

Mounted data gives permission denied

### Steps to reproduce the issue

Compose file:
```
version: '3'
services:
  fih:
    build: .
    container_name: fih
    restart: unless-stopped
    environment:
      PORT: ${PORT}
    volumes:
      - /home/docker-data/fih/images:/src/images
      - /home/docker-data/fih/metadata:/src/metadata
  nginx:
    image: nginx:alpine
    container_name: fih_images
    volumes:
      - /home/docker-data/fih/images:/usr/share/nginx/html:ro
    restart: unless-stopped
```

### Describe the results you received

Permission denied

### Describe the results you expected

Working webserver

### podman info output

```yaml
-
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No
It runs podman version 4.4.1

### Additional environment details

AlmaLinux 9.2

### Additional information

(and here the actual report.. as i need to fill in a lot above)

I installed podman using this [guide](https://wiki.crowncloud.net/?How_to_Install_Podman_on_AlmaLinux_8) with the addition of enabling it at boot with `sudo systemctl enable podman` (and `sudo systemctl start podman`). 

This is in line with how things were done with docker before. 
I'm now playing with podman as it's supposed to be that better "contianers done right" project that fixes the lessons learned from docker. Or that's my impression of it :)

But i'm facing permission denied errors that remind me of the old docker days that i'm just baffled by to still be an issue now in 2023. I thought this was a tackled problem but apparently it's not as clear cut.

What you see me do in the compose file is map a couple folders in the container.
In the docker times those folders were having root permissions, the containers run as root too and all is well.
**Disclaimer**, please don't start about "root being bad, security, careful what you wish for, etc... I know.
**Disclaimer 2**, why don't i use podman volumes instead? I want to see and organize the files mounted inside the container on the host. With volumes it's well hidden and difficult to find. Why bother going through that hassle if a simple mount works much easier and allows me to backup/restore a  - to me - known folder.  If there is a better way for this, do feel free to share! 

So in comes podman. The folders now all have the same permission as the host user (just 1 user). I start the containers in a user context too (just podman run ... or podman-compose up -d..., there is no sudo in there anywhere). In my naive line of thought a service started as user surely should have access to my files, right?...

Permission denied.

Inspecting the container resulted in the observation that the folders i mounted into it were, within the container, owned by the root user. That seemed inconsistent to me but hey, i don't care, as long as that works. But it doen't. So i ch-owned my folders on the host as root too. Thinking that "root on host and root in container is both root, must be good?"... And it didn't work, same permission denied.

Further diving into this brought me on the user mapping stuff. I really don't want to deal with that fiddly stuff.
So the questions i have is: How do i make volume mounts in a rootless podman without all the incredible hassle?
Preferably both the host and container can see the folder contents.
