### ISSUE TITLE
using pasta network fails with 'Failed to open tun socket in namespace'

### ISSUE THREAD

**Issue by PhracturedBlue** [containers/podman#19428]
### Issue Description

Attempting to use pasta networking rootless:
```
podman run --rm -dt --net pasta -p 11080:80 quay.io/libpod/banner
Error: pasta failed with exit code 1:
No external routable interface for IPv6
Template interface: br0 (IPv4)
Namespace interface: br0
MAC:
    host: ea:c6:32:7d:07:bf
DHCP:
    assign: 192.168.1.91
    mask: 255.255.255.0
    router: 192.168.1.1
DNS:
    192.168.1.1
DNS search list:
    lan
Failed to open tun socket in namespace
```

### Steps to reproduce the issue

sudo apt install podman podman-netavark uidmap
podman run --rm -dt --net pasta -p 11080:80 quay.io/libpod/banner

### Describe the results you received

pasta created an error:
```
Error: pasta failed with exit code 1:
No external routable interface for IPv6
...
Failed to open tun socket in namespace
```

I also tested with:
```podman run --rm -dt --net pasta:--ipv4-only -p 11080:80 quay.io/libpod/banner```

which gives the same error message without the mention of IPv6

### Describe the results you expected

Container started

### podman info output

```yaml
Debian bookworm using packages from http://download.opensuse.org/repositories/home:/alvistack/Debian_12/


Client:       Podman Engine
Version:      4.6.0
API Version:  4.6.0
Go Version:   go1.20.6
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_
