### ISSUE TITLE
How to uninstall podman on Windows

### ISSUE THREAD

**Issue by stitchik** [containers/podman#19487]
### Issue Description

I tried to uninstall podman on Windows

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman machine stop`
2. podman machine rm
3. `podman --version` and I still get `podman version 4.6.0`

### Describe the results you received

I ran `docker run -d -p 80:80 docker/getting-started` and got  `docker: error during connect: Post "http://127.0.0.1:2375/run/user/1000/podman/podman.sock/v1.24/containers/create": dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.`

How can I remove podman completely?

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
podman version 4.6.0, Windows 10

podman machine info
Host:
  Arch: amd64
  CurrentMachine: ""
  DefaultMachine: ""
  EventsDir: C:\Users\xxx\.local\share\containers\podman\podman
  MachineConfigDir: C:\Users\xxx\.config\containers\podman\machine\wsl
  MachineImageDir: C:\Users\xxx\.local\share\containers\podman\machine\wsl
  MachineState: ""
  NumberOfMachines: 0
  OS: windows
  VMType: wsl
Version:
  APIVersion: 4.6.0
  Built: 1689891628
  BuiltTime: Fri Jul 21 01:20:28 2023
  GitCommit: 38e6fab9664c6e59b66e73523b307a56130316ae
  GoVersion: go1.20.3
  Os: windows
  OsArch: windows/amd64
  Version: 4.6.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Windows 10

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
