### ISSUE TITLE
Machine initialization hangs on windows server

### ISSUE THREAD

**Issue by fedinskiy** [containers/podman#19498]
### Issue Description

I have windows server machine on AWS and I am trying to start podman machine there, according to the manual[1]. When I run `podman machine init` it hangs (currently for an hour) without producing any output.

[1] https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md

### Steps to reproduce the issue

Steps to reproduce the issue
1.  ` podman machine init`
Or:
1. `podman machine init --cpus=2 --memory=2048 --rootful`

### Describe the results you received

the command hangs

### Describe the results you expected

Podman initialises guest virtual machine

### podman info output

```yaml
podman.exe version 4.6.0 (tried for 4.5.0 as well)



> systeminfo

Host Name:                 <EDITED>
OS Name:                   Microsoft Windows Server 2022 Datacenter
OS Version:                10.0.20348 N/A Build 20348
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          EC2
Registered Organization:   Amazon.com
Product ID:                <EDITED>
Original Install Date:     8/3/2023, 7:05:11 AM
System Boot Time:          8/3/2023, 7:04:44 AM
System Manufacturer:       Amazon EC2
System Model:              m5zn.metal
System Type:               x64-based PC
Processor(s):              2 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 7 GenuineIntel ~3800 Mhz  
                           [02]: Intel64 Family 6 Model 85 Stepping 7 GenuineIntel ~3800 Mhz  
BIOS Version:              Amazon EC2 1.0, 10/16/2017
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              N/A
Time Zone:                 (UTC) Coordinated Universal Time
Total Physical Memory:     196,241 MB
Available Physical Memory: 191,998 MB                                                         Virtual Memory: Max Size:  205,201 MB                                                         Virtual Memory: Available: 201,184 MB                                                         Virtual Memory: In Use:    4,017 MB                                                           
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              N/A
Hotfix(s):                 <EDITED>
Network Card(s):           1 NIC(s) Installed.
                           [01]: Amazon Elastic Network Adapter
                                 Connection Name: Ethernet 4
                                 DHCP Enabled:    Yes
                                 DHCP Server:     <EDITED>
                                 IP address(es)
                                 [01]: <EDITED>
                                 [02]: <EDITED>
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

```$ aws ec2 describe-instances --instance-id <>
"Hypervisor": "xen"
 "Architecture": "x86_64",
"VirtualizationType": "hvm",
                    "CpuOptions": {
                        "CoreCount": 24,
                        "ThreadsPerCore": 2
                    },

```
