### ISSUE TITLE
"podman machine start" error while "user-mode-networking=true" on Windows

### ISSUE THREAD

**Issue by nitramigen** [containers/podman#19511]
### Issue Description

When command **podman machine init --user-mode-networking=true --now** completed, I get an error 

> cp: cannot stat '/mnt/wsl/resolv.conf': No such file or directory

### Steps to reproduce the issue

Steps to reproduce the issue in Powershell (run as admin)
1. podman machine init --user-mode-networking=true --now

Other scenario:
1. podman machine init
2. podman machine set --user-mode-networking=true
3. podman machine start

### Describe the results you received

I got the following output with the error:

> Downloading VM image: fedora-podman-amd64-v37.0.56.tar.xz: done
> Extracting compressed file
> Importing operating system into WSL (this may take a few minutes on a new WSL install)...
> Installing user-mode networking distribution...
> Configuring system...
> Generating public/private abcd key pair.
> Your identification has been saved in podman-machine-default
> Your public key has been saved in podman-machine-default.pub
> The key fingerprint is:
> 
> [Omitted output]
> 
> Machine init complete
> Starting machine "podman-machine-default"
> Starting user-mode networking...
> **cp: cannot stat '/mnt/wsl/resolv.conf': No such file or directory**
> **Error: error setting up user-mode networking: exit status 1**

### Describe the results you expected

Expecting the following output and get prompted to the VM:

> Downloading VM image: fedora-podman-amd64-v37.0.56.tar.xz: done
> Extracting compressed file
> Importing operating system into WSL (this may take a few minutes on a new WSL install)...
> Installing user-mode networking distribution...
> Configuring system...
> Generating public/private abcd key pair.
> Your identification has been saved in podman-machine-default
> Your public key has been saved in podman-machine-default.pub
> The key fingerprint is:
> 
> [Omitted output]
> 
> Machine init complete
> Starting machine "podman-machine-default"
> Starting user-mode networking...
> 
> This machine is currently configured in rootless mode. If your containers
> require root permissions (e.g. ports < 1024), or if you run into compatibility
> issues with non-podman clients, you can switch using the following command:
> 
>    podman machine set --rootful
> 
> API forwarding for Docker API clients is not available due to the following startup failures.
>         could not start api proxy since expected pipe is not available: podman-machine-default
> 
> Podman clients are still able to connect.
> **Machine "podman-machine-default" started successfully**

### podman info output

```yaml
Arch: amd64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: C:\Users\nitramigen\.local\share\containers\podman\podman
  MachineConfigDir: C:\Users\nitramigen\.config\containers\podman\machine\wsl
  MachineImageDir: C:\Users\nitramigen\.local\share\containers\podman\machine\wsl
  MachineState: Running
  NumberOfMachines: 1
  OS: windows
  VMType: wsl
Version:
  APIVersion: 4.6.0
  Built: 1689891628
  BuiltTime: Thu Jul 20 18:20:28 2023
  GitCommit: 38e6fab9664c6e59b66e73523b307a56130316ae
  GoVersion: go1.20.3
  Os: windows
  OsArch: windows/amd64
  Version: 4.6.0
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Workaround found:

1. In Windows Explorer, go to **\\\\wsl$\podman-usermodenet\mnt\wsl**
2. create file **resolv.conf**
3. In Powershell, run **podman machine start**
