### ISSUE TITLE
Documentation of DELETE /libpod/play/kube incomplete

### ISSUE THREAD

**Issue by krucod3** [containers/podman#19945]
### Issue Description

Podman's REST API documentation does not give information about the payload or the options accepted by the [DELETE /play/kube](https://docs.podman.io/en/latest/_static/api.html?version=v4.3.1#tag/containers/operation/PlayKubeDownLibpod) endpoint. 
Additionally the description "Remove pods from kube play" of the endpoint is misleading as it deletes all supported K8s resources and not only pods.

### Steps to reproduce the issue

The endpoint itself works as expected, only the documentation is misleading/wrong.

### Describe the results you received

Faulty documentation

### Describe the results you expected

Correct documentation.

### podman info output

```yaml
Not really relevant here, but please:

Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.4
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a-dirty
Built:        Sun May 14 22:11:42 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
