### ISSUE TITLE
Is it possible to have execute permissions on /tmp for kube play created pods?

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#20320]
### Discussed in https://github.com/containers/podman/discussions/19859

<div type='discussions-op-text'>

<sup>Originally posted by **frenetic00** September  5, 2023</sup>
Is it possible to give /tmp execute permissions when running as a pod under systemd?

I've used Kubernetes yaml to build a pod of several containers to run Nextcloud.
One of the Nextcloud apps is failing to run correctly because it relies on having execute permissions in /tmp

My Kubernetes yaml is executed as a non-root user using a systemd service.
```
ExecStart=/usr/bin/podman kube play --network=ns:/var/run/netns/%U --replace --service-container=true %I
```

Inside the container, I can see that /tmp has been mounted with noexec
```
tmpfs /tmp tmpfs rw,nosuid,nodev,noexec,relatime,uid=1003,gid=1003,inode64 0 0
```

I'm new to go and namespaces, but I'm trying to get an understanding of what's going on while trying to solve my issue.

I can see in the [docs](https://github.com/containers/podman/blob/main/docs/source/markdown/options/systemd.md) that there is a systemd option for other podman commands that will mount several tmpfs file systems when systemd mode is enabled. Does the `--service-container` option ensure that that the container will be configured with systemd? I've seen some reference to it [here](https://github.com/containers/podman/blob/main/cmd/podman/kube/play.go#L191-L196).

I can also see that permissions for /tmp are being set [here](https://github.com/containers/podman/blob/main/libpod/container_internal_linux.go#L221) and [here](https://github.com/containers/podman/blob/main/libpod/container_internal_linux.go#L234-L245) but I'm still not sure how /tmp gets configured with the noexec option. Can anyone point me in the right direction? Thanks

</div>

**Comment by rhatdan** [comment]
The question I have is what is the kubernetes default?  Is /tmp in these situations exec or noexec?

@umohnani8 @ygalblum PTAL

**Comment by ygalblum** [comment]
I think there is something more specific here. I used the following simple pod.yml:
```
apiVersion: v1
kind: Pod
metadata:
  name: fedora
spec:
  containers:
  - name: fedora
    image: registry.fedoraproject.org/fedora:38
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
```
and applied it on an Openshift cluster.

Looking at the `/proc/mounts` I can see that `/tmp` is not mounted at all. So, it is part of the general mount on `/`. To confirm I also created a small shell script on `/tmp` and successfully ran it.

Then I wanted to see how podman handles it. First, I ran a simple `podman kube play` on this Yaml file. I did the same shell script thing and surprisingly, I was able to run it. I then looked at `/proc/mounts` and found this line:
```
tmpfs /tmp tmpfs rw,context="system_u:object_r:container_file_t:s0:c609,c736",nosuid,nodev,relatime,uid=1000,gid=1000,inode64 0 0
``` 
You can see that the `noexec` flag is not set.

So, I thought that maybe it is the service container option responsible for it. So, I wrapped the K8S YAML file with a `.kube` file:
```
[Kube]
Yaml=fedora.yml
```
I then reloaded systemd which produced this systemd unit file:
```
# Automatically generated by /usr/lib/systemd/user-generators/podman-user-generator
# 
[X-Kube]
Yaml=fedora.yml

[Unit]
SourcePath=/home/ygal/.config/containers/systemd/fedora.kube
RequiresMountsFor=%t/containers

[Service]
KillMode=mixed
Environment=PODMAN_SYSTEMD_UNIT=%n
Type=notify
NotifyAccess=all
SyslogIdentifier=%N
ExecStart=/usr/bin/podman kube play --replace --service-container=true /home/ygal/.config/containers/systemd/fedora.yml
ExecStopPost=/usr/bin/podman kube down /home/ygal/.config/containers/systemd/fedora.yml
```
and started the service. `Exec`ing into the container, I found the exact same line in `/proc/mounts`.

I did not look at the code referenced in the original description, so I may be wrong here. But, I think we need an example in which the `noexec` flag is set in Podman in order to compare

**Comment by sanmai-NL** [comment]
See: https://github.com/kubernetes/kubernetes/issues/48912

**Comment by rhatdan** [comment]
@sanmai-NL Not sure of the reference in the kubernetes?

@frenetic00 do you have a reproducer we could play with?

**Comment by yangskyboxlabs** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: cassandra
spec:
  containers:
  - name: cassandra
    image: cassandra:4.1.3
    network: 
    volumeMounts:
    - name: cassandra-pvc
      mountPath: /var/lib/cassandra
  volumes:
  - name: cassandra-pvc
    persistentVolumeClaim:
      claimName: cassandra-data
```

Log (`podman pod logs cassandra`):
[cassandra_noexec_tmp.log](https://github.com/containers/podman/files/13604312/cassandra_noexec_tmp.log)

**Comment by sanmai-NL** [comment]
> @sanmai-NL Not sure of the reference in the kubernetes?

The Kubernetes issue discusses the merits of `noexec` on `tmpfs`'s and the `/tmp/` mount specifically.

**Comment by agorgl** [comment]
I had the same problem with `lscr.io/linuxserver/unifi-network-application:latest` image that essentially is a JVM application extracting a native `.so` dependency in `/tmp` in runtime, and to make it work I had to overlay my own tmp pvc like this:

```
apiVersion: v1
kind: Pod
metadata:
  name: unifi
  labels:
    app: unifi
spec:
  containers:
    - name: unifi
      image: lscr.io/linuxserver/unifi-network-application:latest
...
      volumeMounts:
        - name: unifi-temp
          mountPath: /tmp
...
  volumes:
    - name: unifi-temp
      persistentVolumeClaim:
        claimName: unifi-temp
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-temp
  annotations:
    volume.podman.io/type: tmpfs
    volume.podman.io/device: tmpfs
    volume.podman.io/mount-options: exec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
