### ISSUE TITLE
wrong port forwarding on macvlan driver

### ISSUE THREAD

**Issue by mrrudy** [containers/podman#20527]
### Issue Description

Hi Team,
when creating port forward **and** using macvlan driver, external port is ignored. Additionally it works for internal port (in the below example curl to port 80 works fine). Also if both ports are same (e.g. 80:80) it will go unnoticed. 

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman network inspect lan_macvlan &>/dev/null || podman network create -d macvlan -o parent=eth0 lan_macvlan
2. systemctl enable --now netavark-dhcp-proxy.socket
3. podman run -d --rm --replace --network lan_macvlan --mac-address 02:42:C0:A8:01:12 --name test1 -p 8080:80 quay.io/libpod/alpine_nginx:latest
4. contIP=$(podman inspect test1 --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
5. curl http://${contIP}:8080;
6. curl http://${contIP}:80;

### Describe the results you received

```
$ curl http://${contIP}:8080;
curl: (7) Failed to connect to 192.168.1.159 port 8080: Connection refused

$ curl http://${contIP}:80;
podman rulez
```

### Describe the results you expected

```
$ curl http://${contIP}:8080;
podman rulez
```

### podman info output

```yaml
podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.19.8
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

podman in lxc container, debian bookworm
