### ISSUE TITLE
pasta failed to join network

### ISSUE THREAD

**Issue by fsdrw08** [containers/podman#20599]
### Issue Description

pasta failed to join podman network.

### Steps to reproduce the issue

Steps to reproduce the issue
1. run a podman container with pasta network mode, then join a network to this container:
```shell
podman run --name=pasta-nginx --net=pasta -d docker.io/nginxinc/nginx-unprivileged
podman network connect podman pasta-nginx
```

### Describe the results you received

Describe the results you received
```
Error: "pasta" is not supported: invalid network mode
```

### Describe the results you expected

Describe the results you expected
I hope the pasta network mode container can success join other podman bridge network, I would like to run reverse proxy in podman, and other containers in the same podman host only expose ports to the reverse proxy but not directly expose to the host, and also the reverse proxy is able to get the client source IP.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

Client:       Podman Engine
Version:      4.7.0
API Version:  4.7.0
Go Version:   go1.20.8
Built:        Thu Sep 28 02:24:38 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
