### ISSUE TITLE
applehv failure when doing 'podman machine ls' Error: listing vms: Get "/vm/state": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by benoitf** [containers/podman#20703]
### Issue Description

podman main branch of today (638199c495be139c37cd5ff5996f08e4a69100de)

if I want to initialize a machine, it says 'already exists', if I want to list machines there is an error

### Steps to reproduce the issue

Steps to reproduce the issue

```shell
CONTAINERS_MACHINE_PROVIDER="applehv" ./bin/darwin/podman machine init --log-level=DEBUG                                                                                                                                                                                                                                                                                            
INFO[0000] ./bin/darwin/podman filtering at log level debug
DEBU[0000] Using Podman machine with `applehv` virtualization provider
Error: podman-machine-default: VM already exists
DEBU[0000] Shutting down engines
```

default list
```
./bin/darwin/podman machine list                                                                                                                                                                                                                                                                                                                                                       NAME        VM TYPE     CREATED     LAST UP     CPUS        MEMORY      DISK SIZE
```

with env variable being set:
```
CONTAINERS_MACHINE_PROVIDER="applehv" ./bin/darwin/podman machine list --log-level=DEBUG                                                                                                                                                                                                                                                                                                   INFO[0000] ./bin/darwin/podman filtering at log level debug
DEBU[0000] Using Podman machine with `applehv` virtualization provider
DEBU[0000] connection refused: http://localhost:8081/vm/state
Error: listing vms: Get "/vm/state": unsupported protocol scheme ""
DEBU[0000] Shutting down engines
```



### Describe the results you received

Error: listing vms: Get "/vm/state": unsupported protocol scheme ""

### Describe the results you expected

I should see a podman machine ? as init says it already exists ?

### podman info output

```yaml
CONTAINERS_MACHINE_PROVIDER="applehv" ./bin/darwin/podman info                                                                                                                                                                                                                                                                                                                         
OS: darwin/arm64
provider: applehv
version: 4.8.0-dev
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
