### ISSUE TITLE
podman machine start stuck  starting status on Apple M3 Max

### ISSUE THREAD

**Issue by nutshellfool** [containers/podman#20859]
### Issue Description

podman machine start stuck 'Currently starting' status 

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init
2. podman --log-level=debug machine start

### Describe the results you received

➜  ~ podman --log-level=debug machine start
INFO[0000] podman filtering at log level debug
DEBU[0000] Using Podman machine with `qemu` virtualization provider
Starting machine "podman-machine-default"
DEBU[0000] {true 1500 map[forward-dest:[/run/user/502/podman/podman.sock] forward-identity:[/Users/RichardLee/.ssh/podman-machine-default] forward-sock:[/Users/RichardLee/.local/share/containers/podman/machine/qemu/podman.sock] forward-user:[core]] [] map[listen-qemu:unix:///var/folders/jn/41x0x_9955d9w0w83r6xy4rw0000gp/T/podman/qmp_podman-machine-default.sock] /var/folders/jn/41x0x_9955d9w0w83r6xy4rw0000gp/T/podman/podman-machine-default_proxy.pid 50420}
DEBU[0000] qemu cmd: [/opt/homebrew/bin/qemu-system-aarch64 -accel hvf -accel tcg -cpu host -M virt,highmem=on -drive file=/opt/homebrew/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -drive file=/Users/RichardLee/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw -m 2048 -smp 8 -fw_cfg name=opt/com.coreos/config,file=/Users/RichardLee/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix:/var/folders/jn/41x0x_9955d9w0w83r6xy4rw0000gp/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/jn/41x0x_9955d9w0w83r6xy4rw0000gp/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=apodman-machine-default_ready -device virtserialport,chardev=apodman-machine-default_ready,name=org.fedoraproject.port.0 -pidfile /var/folders/jn/41x0x_9955d9w0w83r6xy4rw0000gp/T/podman/podman-machine-default_vm.pid -virtfs local,path=/Users,mount_tag=vol0,security_model=none -virtfs local,path=/private,mount_tag=vol1,security_model=none -virtfs local,path=/var/folders,mount_tag=vol2,security_model=none -drive if=virtio,file=/Users/RichardLee/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-39.20231119.2.0-qemu.aarch64.qcow2]
Waiting for VM ...

-------------------------------
qemu debug  log output

![qemu-logs](https://github.com/containers/podman/assets/1439114/e189c5c1-05fa-4cdb-88e6-5428588da334)

### Describe the results you expected

poman machine start successful

### podman info output

```yaml
➜  ~ podman info
OS: darwin/arm64
provider: qemu
version: 4.8.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:50786->127.0.0.1:50420: read: connection reset by peer
➜  ~
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Apple M3 Max chip
MacOS: 14.1.2

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
