### ISSUE TITLE
Machine Start fail in user-mode networking 

### ISSUE THREAD

**Issue by Swympy** [containers/podman#20982]
### Issue Description

I have created a podman machine with -user-mode-networking via cli, and when I want to start it I have an error for -user-mode networking with exit status 42 
PS :  I'm in win10 and wsl is up to date

### Steps to reproduce the issue

Steps to reproduce the issue
1.  podman machine init --user-mode-networking --rootful
2. podman machine start

### Describe the results you received

```
podman machine start
Starting machine "podman-machine-default"
Starting user-mode networking...
Error: error setting up user-mode networking: exit status 42
```

### Describe the results you expected

.

### podman info output

```yaml
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3693
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes
