### ISSUE TITLE
Newly pulled image does not show up on Podman desktop v1.5.3 without restart

### ISSUE THREAD

**Issue by kaizencon** [containers/podman#21038]
### Issue Description

Newly pulled image does not show up on Podman desktop v1.5.3 without desktop restart

### Steps to reproduce the issue

Steps to reproduce the issue
1. From win 11 cmd, podman run -it alpine
2. Go to podman desktop
3. Look for alpine image, it wouldn't show
4. Restart the desktop
5. Image will show up under images section

### Describe the results you received

Describe the results you received

### Describe the results you expected

Image downloaded from CMD should show up in the desktop

### podman info output

```yaml
Client:       Podman Engine
Version:      4.7.2
API Version:  4.7.2
Go Version:   go1.20.10
Git Commit:   750b4c3a7c31f6573350f0b3f1b787f26e0fe1e3
Built:        Tue Oct 31 10:05:03 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 11:42:56 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Win 11
