### ISSUE TITLE
podman kube play should be able to read the bash variables

### ISSUE THREAD

**Issue by antverpp** [containers/podman#21057]
### Feature request description

For example, I have a number of manifests, where I want to refer some values by an environment variable:
spec:
  containers:
  - name: <myname>
    image: ${REGISTRY}/<myname>:${TAG}

where REGISTRY and TAG are defined as env variables, for example in the .env file.

**Comment by antverpp** [comment]
A clear and concise description of what you want to happen:
So, I define variables in .env file.
And I refer them in the manifest, as described above.
Like, REGISTRY=myregistry.com, TAG=0.0.1

And as a result, the podman play kube should render the manifest and pull the image myregistry.com/myname:0.0.1, 
being defined in the yaml manifest as "image: ${REGISTRY}/myname:${TAG}"

**Comment by rhatdan** [comment]
Interested in opening a PR to make this happen?

**Comment by giuseppe** [comment]
Does Kubernetes support it?

**Comment by roman-kiselenko** [comment]
Kubernetes YAML doesn't support this kind of variable interpolation.
You can achieve the same thing with [envsubst](https://man7.org/linux/man-pages/man1/envsubst.1.html)

```yaml
# my_pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: foobar
spec:
  containers:
  - name: container-1
    image: ${REGISTRY}/${REPO}:${TAG}
```

```shell
REGISTRY=myregistry.com REPO=project TAG=0.0.1 envsubst < my_pod.yaml > pod.yaml
```
```yaml
# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: foobar
spec:
  containers:
  - name: container-1
    image: myregistry.com/project:0.0.1
```
