### ISSUE TITLE
[MacOS] podman machine start hangs indefinitely after reinstallation

### ISSUE THREAD

**Issue by noursaadallah** [containers/podman#21120]
### Issue Description

I installed Podman + Podman-Desktop to experiment with a while back, I only tested a few basics (podman machine start, podman ps, started a test container) and I tested some docker compatibility which was seemingly working as well (alias docker command, and symlink the socket).
I uninstalled Podman + Podman-Desktop because I needed to use Docker like the rest of the team (and no need to keep Podman, it was not approved then)
Today we're all migrating to Podman, but after I reinstalled Podman + Podman-Desktop, when I try to init a new machine it works, but `podman machine start` hangs indefinitely:
```
Starting machine "podman-machine-default"
Waiting for VM ...
```

Also when I first reinstalled podman, I found some relic machines that I tested, meaning the uninstall process was not complete.

I tried uninstalling and cleaning up; then reinstalling. Same result
```
brew uninstall podman
rm -rf ~/.config/containers/
rm -rf ~/.local/share/containers
rm ~/.ssh/podman*
brew install podman
podman machine init
podman machine start
```

I tried uninstalling and reinstalling multiple times, each time trying a new suggestion from [issue 11319](https://github.com/containers/podman/issues/11319) and [issue 11393](https://github.com/containers/podman/issues/11393), but nothing seems to work. I also tried uninstalling & reinstalling qemu.

### Steps to reproduce the issue

Steps to reproduce the issue
1. brew install podman
2. brew uninstall podman
3. brew install podman
4. podman machine init
5. podman machine start

### Describe the results you received

podman machine start:
Starting machine "podman-machine-default"
Waiting for VM ...

### Describe the results you expected

podman machine start to work and start the machine

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
podman info

OS: darwin/arm64
provider: qemu
version: 4.8.2

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:49553: connect: connection refused
```

brew info podman (podman version not working):
```
==> podman: stable 4.8.2 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.8.2 (191 files, 56.7MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-12-29 at 11:59:01
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go ✔, go-md2man ✘, make ✘
Required: qemu ✔
```

OS: MacOS Ventura
architecture: arm64
kernel: Darwin Kernel Version 22.6.0
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
