### ISSUE TITLE
`podman machine start` stuck in podman 4.8.3 on Apple M1

### ISSUE THREAD

**Issue by bo0ts** [containers/podman#21169]
### Issue Description

After upgrading to 4.8.3 `podman machine start` fails to start the machine and is stuck at `Waiting for VM`. Neither machine reinit or system restart helped. This is using qemu and not (as in the other issue `applehv`). Podman was installed via brew.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init
2. podman machine start
3.

### Describe the results you received

Machine not starting

### Describe the results you expected

Machine stawrts

### podman info output

```yaml
podman machine info
Host:
  Arch: arm64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: /var/folders/2c/xzkz3mcj0pz1sxspkt_kwdb40000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/.../.config/containers/podman/machine/qemu
  MachineImageDir: /Users/.../.local/share/containers/podman/machine/qemu
  MachineState: Starting
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.8.3
  Built: 1704280724
  BuiltTime: Wed Jan  3 12:18:44 2024
  GitCommit: 85dc30df56566a654700722a4dd190e1b9680ee7
  GoVersion: go1.21.5
  Os: darwin
  OsArch: darwin/arm64
  Version: 4.8.3
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
