### ISSUE TITLE
Podman 4.8.3 stuck at podman machine init on Windows 11

### ISSUE THREAD

**Issue by koisurunippon** [containers/podman#21187]
### Issue Description

I installed Podman 4.8.3 on Windows 11 and stuck at podman machine init (I got the same issue with Podman 4.8.2)
I can extract the file fedora-podman-amd64-v39.0.16.tar.xz manually successfully, not sure why it was failed during the init command.

C:\Users\MyID>podman machine init
Downloading VM image: fedora-podman-amd64-v39.0.16.tar.xz: done
xz: (stdin): Compressed data is corrupt
Extracting compressed file: podman-machine-default_fedora-podman-amd64-v39.0.16.tar [--------------] 32.0KiB / 112.0MiB

![image](https://github.com/containers/podman/assets/142728322/998f655e-2ab4-4f8a-9ddc-b00415ceb974)
![image](https://github.com/containers/podman/assets/142728322/37cee7de-9b75-4945-ba77-c64eee1cc119)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Installed podman 4.8.3 from https://github.com/containers/podman/releases/download/v4.8.3/podman-4.8.3-setup.exe (wsl option checked)
2. Run podman machine init

### Describe the results you received

Describe the results you received:

Podman machine init command was failed to execute.

C:\Users\MyID>podman machine init
Downloading VM image: fedora-podman-amd64-v39.0.16.tar.xz: done
xz: (stdin): Compressed data is corrupt
Extracting compressed file: podman-machine-default_fedora-podman-amd64-v39.0.16.tar [--------------] 32.0KiB / 112.0MiB

### Describe the results you expected

Describe the results you expected:
Podman machine init command is successful.

### podman info output

```yaml
podman version: 4.8.3
operating system: Windows 11 64 bit (Intel)

C:\Users\MyID>podman machine init
Downloading VM image: fedora-podman-amd64-v39.0.16.tar.xz: done
xz: (stdin): Compressed data is corrupt
Extracting compressed file: podman-machine-default_fedora-podman-amd64-v39.0.16.tar [--------------] 32.0KiB / 112.0MiB
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
