### ISSUE TITLE
Podman kube support for GPU

### ISSUE THREAD

**Issue by elasticdotventures** [containers/podman#21188]
### Feature request description

I'm trying to access my GPU using `podman play kube` with a yaml file, the specific application is ollama

😁 When I use the podman run syntax suggested by the podman Container Device Interface docs this works:
```
podman run -it --rm --device nvidia.com/gpu=all --security-opt=label=disable --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```

😢 When I attempt to do the same with a k8s style pod.yaml file, I expect this to work but it doesn't:
```
apiVersion: v1
kind: Pod
metadata:
  name: ollama-server
spec:
  hostNetwork: true
  containers:
    - image: docker.io/ollama/ollama
      name: ollama
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
      ports:
        - containerPort: 11434
          hostPort: 11434
      resources:
        requests:
          memory: "500Mi"
        limits:
          nvidia.com/gpu: 1 # Request one GPU
          memory: "1Gi"

```

I can successfully run nvidia-smi inside the kube (with podman v4.8.2)
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html

```
 podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 3090 (UUID: GPU-6c5fef2a-981d-c3c0-d172-f715560de83d)
```

### Have you considered any alternatives?

Don't use `podman kube play`

### Additional context

I think this is related to issue #12587

It's interesting because the pod definition below also works and output that I have a GPU!? 
```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-gpu-pod
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1 # Request one GPU
```
