### ISSUE TITLE
podman machine start hangs at "Waiting for VM" (Mac Sonoma 14.1.2 M1 Pro Chip)

### ISSUE THREAD

**Issue by tim3003** [containers/podman#21237]
### Issue Description

Describe your issue

### Steps to reproduce the issue

Steps to reproduce the issue
1.podman machine init - Succesful (Machine init complete)
2.podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
<Hanging>

### Describe the results you received

podman machine strart hangs for ever

### Describe the results you expected

podman machine start should have started fine

### podman info output

```yaml
podman version 4.8.3
Mac Sonoma 14.1.2 M1 Pro Chip


$ podman machine info
Host:
  Arch: arm64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: /var/folders/dc/xlqxg0vs0wbc50hbq706pv240000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/ABC/.config/containers/podman/machine/qemu
  MachineImageDir: /Users/ABC/.local/share/containers/podman/machine/qemu
  MachineState: Starting
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.8.3
  Built: 1704280724
  BuiltTime: Wed Jan  3 03:18:44 2024
  GitCommit: 85dc30df56566a654700722a4dd190e1b9680ee7
  GoVersion: go1.21.5
  Os: darwin
  OsArch: darwin/arm64
  Version: 4.8.3
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

$podman machine start --log-level debug
Starting machine "podman-machine-default"
Waiting for VM …

Popup window opens up for qemu which is showing this message - Sychronous Exception a 0x........ ASSERT [ArmCpuDxe]... DefaultExceptionHandler.c(343) ((BOOLEAN)(0==1)) 
Screenshot attached as a file

![Screenshot 2024-01-11 at 4 24 06 PM](https://github.com/containers/podman/assets/156385886/489684a9-8983-4529-a3d7-cfe37eca338d)
