### ISSUE TITLE
Can not delete configmap key vaule related file using kube play

### ISSUE THREAD

**Issue by fsdrw08** [containers/podman#21307]
### Issue Description

Describe your issue
podman kube play cannot delete configmap key vaule related file 

### Steps to reproduce the issue

Steps to reproduce the issue
1. prepare all in one k8s kube yaml file, then run `podman kube play \path\to\yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-cm
data:
  key1: value1
  key2: value2

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: "docker.io/library/busybox:latest"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      args:
        - sleep
        - "3600"
      volumeMounts:
        - name: test
          mountPath: /mnt/test
  volumes:
    - name: test
      configMap:
        name: busybox-cm
  restartPolicy: Never
```

2. run `ls` command to get the files in dir `/mnt/test` which mount from configmap in container
```
$ podman exec busybox-busybox ls /mnt/test
key1
key2
```
3. update the kube yaml file, comment out the key2 in configmap, run again `podman kube play /path/to/file`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-cm
data:
  key1: value1
  # key2: value2

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: "docker.io/library/busybox:latest"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      args:
        - sleep
        - "3600"
      volumeMounts:
        - name: test
          mountPath: /mnt/test
  volumes:
    - name: test
      configMap:
        name: busybox-cm
  restartPolicy: Never
```
4. run `ls` command to get the files in dir `/mnt/test` which mount from configmap in container, the key2 still there
```
$ podman exec busybox-busybox ls /mnt/test
key1
key2
```

### Describe the results you received

Describe the results you received

podman kube play cannot delete configmap key vaule related file 

### Describe the results you expected

Describe the results you expected

podman kube play should update the configmap related volume when the data key in configmap yaml file was deleted 

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

OS: FCOS 39

Client:       Podman Engine
Version:      4.8.2
API Version:  4.8.2
Go Version:   go1.21.4
Built:        Mon Dec 11 21:23:04 2023
OS/Arch:      linux/amd64
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
