### ISSUE TITLE
podman machine on Windows WSL2 does not stop "autoremove" containers depending on Windows machine

### ISSUE THREAD

**Issue by feloy** [containers/podman#21482]
### Issue Description

We are encountering different behaviours of the same podman machine server (4.9.0) on two different Windows machines (both W11). We are using WSL2 to run the machines on both sides.

On the first machine, we have a container marked as "Autoremove" running, when we stop and restart the podman machine, the container has been deleted.

On the second machine, with the same container marked as "Autoremove", when the podman machine is stopped and restarted, the container is still present (and stopped) after the restart.

I'm not sure if is related to Windows version or not, but what is the expected behaviour? Deleted or not deleted?

Do you have an idea where the difference of behaviour could come from?

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman run -d --rm nginx
2. podman machine stop
3. podman machine start
4.  podman container list --all

### Describe the results you received

An empty list on first machine, a stopped container on second machine.

### Describe the results you expected

An empty list on both versions

### podman info output

```yaml
Client:       Podman Engine
Version:      4.9.1
API Version:  4.9.1
Go Version:   go1.21.6
Git Commit:   118829d7fc68c34d5a317cda90b69884f3446f5c
Built:        Thu Feb  1 15:09:25 2024
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.9.0
API Version:  4.9.0
Go Version:   go1.21.6
Built:        Wed Jan 24 11:07:27 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

First machine (container deleted):
```
wsl --version
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3007
```

Second machine (container not deleted):
```
Versione WSL: 2.0.14.0
Versione kernel: 5.15.133.1-1
Versione WSLg: 1.0.59
Versione MSRDC: 1.2.4677
Versione Direct3D: 1.611.1-81528511
Versione DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versione di Windows: 10.0.22621.3007
````

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
