### ISSUE TITLE
kube play: rootlessport conflict with ID X

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#21560]
Only three instances, with two of them in the last month:
```
$ podman [options] kube play /tmp/podman_test2218753273/pod.yaml
[starting container <c1>: rootlessport conflict with ID 4]
[starting container <c1>: rootlessport conflict with ID 4 starting container <c2>: a dependency of container <c2> failed to start: container state improper]
Pod:
<p>
Container:
<c2>
         
         
starting container <c1>: rootlessport conflict with ID 4
starting container <c2>: a dependency of container <c2> failed to start: container state improper
Error: failed to start 2 containers
```

* fedora-38 : int podman fedora-38 rootless host boltdb
    * [01-17 16:17](https://api.cirrus-ci.com/v1/artifact/task/5879463490093056/html/int-podman-fedora-38-rootless-host-boltdb.log.html#t--Podman-kube-play-test-with-reserved-PublishAll-annotation-in-yaml--1) in Podman kube play test with reserved PublishAll annotation in yaml
* fedora-39 : int podman fedora-39 rootless host sqlite
    * [01-30 09:16](https://api.cirrus-ci.com/v1/artifact/task/5196874873831424/html/int-podman-fedora-39-rootless-host-sqlite.log.html#t--Podman-kube-play-test-with-reserved-PublishAll-annotation-in-yaml--1) in Podman kube play test with reserved PublishAll annotation in yaml
* fedora-39β : int podman fedora-39β rootless host boltdb
    * [10-24-2023 16:04](https://api.cirrus-ci.com/v1/artifact/task/4684023591600128/html/int-podman-fedora-39β-rootless-host-boltdb.log.html#t--Podman-kube-play-test-with-reserved-PublishAll-annotation-in-yaml--1) in Podman kube play test with reserved PublishAll annotation in yaml

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(3) | podman(3) | fedora-39β(1) | rootless(3) | host(3) | boltdb(2) |
|  |  | fedora-39(1) |  |  | sqlite(1) |
|  |  | fedora-38(1) |  |  |  |

**Comment by Luap99** [comment]
The error basically means the the same port is specified twice so rootlessport rejects such invalid config.

I however have no idea how this can happen because podman should de-duplicate any conflicts or throw an error much earlier in the stack. It would be helpful if the test would print the generate yaml to see if the yaml was generated incorrectly.

**Comment by Luap99** [comment]
Yaml to reproduce
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-09T13:53:30Z"
  name: test-pod
spec:
  containers:
  - image: quay.io/libpod/testimage:20221018
    name: test
    ports:
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 8081
      hostPort: 8081
    - containerPort: 8080
      hostPort: 8081
```

That doesn't answer why this flakes but it does answer how to get this error and proves that kube play performs no validation on the input ports at all which is a problem.
