### ISSUE TITLE
Error response from daemon: crun: mount `sysfs` to `sys`: Operation not permitted: OCI permission denied - not sure what to do

### ISSUE THREAD

**Issue by virzak** [containers/podman#21680]
### Issue Description

I'm getting

Error response from daemon: crun: mount `sysfs` to `sys`: Operation not permitted: OCI permission denied

No idea how to avoid, debug or which error logs I need to look into

### Steps to reproduce the issue

Steps to reproduce the issue
1. install podman
2. podman machine init
3. podman machine set --rootful
4. podman machine start
5. choco install docker-compose -y
6. add C:\ProgramData\Docker\cli-plugins to path
7. `podman compose up` from .devcontainer directory
8. Alternatively to previous step run this by opening VS Code

### Describe the results you received

```
Successfully tagged docker.io/library/devcontainer-app:latest
fe408a709f8f67e2510d760cb1c7dd0977e8f409e20640f166762332b4d79846
Successfully built fe408a709f8f
Successfully tagged devcontainer-app
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
[+] Running 2/2
 ✔ Container devcontainer-db-1   Created                                                                                                       0.1s
 ✔ Container devcontainer-app-1  Created                                                                                                       1.4s
Attaching to app-1, db-1
db-1   | SQL Server 2022 will run as non-root by default.
db-1   | This container is running as user mssql.
db-1   | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: crun: mount `sysfs` to `sys`: Operation not permitted: OCI permission denied
Error: executing C:\ProgramData\Docker\cli-plugins\docker-compose.exe up: exit status 1
```

### Describe the results you expected

The container should have started.

### podman info output

```yaml
<details>


  🚀  podman compose up
>>>> Executing external compose provider "C:\\ProgramData\\Docker\\cli-plugins\\docker-compose.exe". Please refer to the documentation for details. <<<<

Sending build context to Docker daemon  3.316kB
STEP 1/7: FROM mcr.microsoft.com/devcontainers/dotnet:8.0-bookworm
STEP 2/7: ENV PATH $PATH:/home/vscode/.dotnet:/home/vscode/.dotnet/tools
--> 9f698d0908c9
STEP 3/7: ARG NODE_VERSION="none"
--> 787879070a47
STEP 4/7: RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
--> 0a6474b01985
STEP 5/7: COPY mssql/installSQLtools.sh installSQLtools.sh
--> 19e94b7cd894
STEP 6/7: RUN bash ./installSQLtools.sh      && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts
Installing mssql-tools
Get:1 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:2 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm InRelease [3617 B]
Get:3 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.9 kB]
Get:4 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:5 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:7 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
Get:8 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main amd64 Packages [28.8 kB]
Get:9 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main all Packages [342 B]
Get:10 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
Get:11 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [12.7 kB]
Get:12 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [138 kB]
Fetched 9260 kB in 1s (8058 kB/s)
Reading package lists...
W: https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists...
Building dependency tree...
Reading state information...
libunwind8 is already the newest version (1.6.2-3).
libunwind8 set to manually installed.
The following additional packages will be installed:
  libltdl7 libodbc2 libodbccr2 libodbcinst2 odbcinst unixodbc unixodbc-common
Suggested packages:
  odbc-postgresql tdsodbc
The following NEW packages will be installed:
  libltdl7 libodbc2 libodbccr2 libodbcinst2 msodbcsql17 mssql-tools odbcinst
  unixodbc unixodbc-common unixodbc-dev
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 1834 kB of archives.
After this operation, 3017 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libltdl7 amd64 2.4.7-5 [393 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 libodbc2 amd64 2.3.11-2+deb12u1 [150 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 libodbccr2 amd64 2.3.11-2+deb12u1 [17.7 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 unixodbc-common all 2.3.11-2+deb12u1 [8172 B]
Get:5 http://deb.debian.org/debian bookworm/main amd64 libodbcinst2 amd64 2.3.11-2+deb12u1 [34.2 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 odbcinst amd64 2.3.11-2+deb12u1 [12.1 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 unixodbc amd64 2.3.11-2+deb12u1 [28.0 kB]
Get:8 http://deb.debian.org/debian bookworm/main amd64 unixodbc-dev amd64 2.3.11-2+deb12u1 [231 kB]
Get:9 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main amd64 msodbcsql17 amd64 17.10.5.1-1 [749 kB]
Get:10 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main amd64 mssql-tools amd64 17.10.1.1-1 [211 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Fetched 1834 kB in 0s (19.1 MB/s)
Selecting previously unselected package libltdl7:amd64.
(Reading database ... 22748 files and directories currently installed.)
Preparing to unpack .../0-libltdl7_2.4.7-5_amd64.deb ...
Unpacking libltdl7:amd64 (2.4.7-5) ...
Selecting previously unselected package libodbc2:amd64.
Preparing to unpack .../1-libodbc2_2.3.11-2+deb12u1_amd64.deb ...
Unpacking libodbc2:amd64 (2.3.11-2+deb12u1) ...
Selecting previously unselected package libodbccr2:amd64.
Preparing to unpack .../2-libodbccr2_2.3.11-2+deb12u1_amd64.deb ...
Unpacking libodbccr2:amd64 (2.3.11-2+deb12u1) ...
Selecting previously unselected package unixodbc-common.
Preparing to unpack .../3-unixodbc-common_2.3.11-2+deb12u1_all.deb ...
Unpacking unixodbc-common (2.3.11-2+deb12u1) ...
Selecting previously unselected package libodbcinst2:amd64.
Preparing to unpack .../4-libodbcinst2_2.3.11-2+deb12u1_amd64.deb ...
Unpacking libodbcinst2:amd64 (2.3.11-2+deb12u1) ...
Selecting previously unselected package odbcinst.
Preparing to unpack .../5-odbcinst_2.3.11-2+deb12u1_amd64.deb ...
Unpacking odbcinst (2.3.11-2+deb12u1) ...
Selecting previously unselected package unixodbc.
Preparing to unpack .../6-unixodbc_2.3.11-2+deb12u1_amd64.deb ...
Unpacking unixodbc (2.3.11-2+deb12u1) ...
Selecting previously unselected package unixodbc-dev:amd64.
Preparing to unpack .../7-unixodbc-dev_2.3.11-2+deb12u1_amd64.deb ...
Unpacking unixodbc-dev:amd64 (2.3.11-2+deb12u1) ...
Selecting previously unselected package msodbcsql17.
Preparing to unpack .../8-msodbcsql17_17.10.5.1-1_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Unpacking msodbcsql17 (17.10.5.1-1) ...
Selecting previously unselected package mssql-tools.
Preparing to unpack .../9-mssql-tools_17.10.1.1-1_amd64.deb ...
Unpacking mssql-tools (17.10.1.1-1) ...
Setting up unixodbc-common (2.3.11-2+deb12u1) ...
Setting up libltdl7:amd64 (2.4.7-5) ...
Setting up libodbc2:amd64 (2.3.11-2+deb12u1) ...
Setting up libodbccr2:amd64 (2.3.11-2+deb12u1) ...
Setting up libodbcinst2:amd64 (2.3.11-2+deb12u1) ...
Setting up odbcinst (2.3.11-2+deb12u1) ...
Setting up unixodbc (2.3.11-2+deb12u1) ...
Setting up msodbcsql17 (17.10.5.1-1) ...
odbcinst: Driver installed. Usage count increased to 1.
    Target directory is /etc
Setting up unixodbc-dev:amd64 (2.3.11-2+deb12u1) ...
Setting up mssql-tools (17.10.1.1-1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u4) ...
Installing sqlpackage
Archive:  sqlpackage.zip
  inflating: /opt/sqlpackage/Azure.Core.dll
  inflating: /opt/sqlpackage/Azure.Identity.dll
  inflating: /opt/sqlpackage/Azure.Security.KeyVault.Keys.dll
  inflating: /opt/sqlpackage/createdump
  inflating: /opt/sqlpackage/libclrjit.so
  inflating: /opt/sqlpackage/libcoreclr.so
  inflating: /opt/sqlpackage/libcoreclrtraceptprovider.so
  inflating: /opt/sqlpackage/libdbgshim.so
  inflating: /opt/sqlpackage/libhostfxr.so
  inflating: /opt/sqlpackage/libhostpolicy.so
  inflating: /opt/sqlpackage/libmscordaccore.so
  inflating: /opt/sqlpackage/libmscordbi.so
  inflating: /opt/sqlpackage/libSystem.Globalization.Native.so
  inflating: /opt/sqlpackage/libSystem.IO.Compression.Native.so
  inflating: /opt/sqlpackage/libSystem.Native.so
  inflating: /opt/sqlpackage/libSystem.Net.Security.Native.so
  inflating: /opt/sqlpackage/libSystem.Security.Cryptography.Native.OpenSsl.so
  inflating: /opt/sqlpackage/Microsoft.ApplicationInsights.dll
  inflating: /opt/sqlpackage/Microsoft.Bcl.AsyncInterfaces.dll
  inflating: /opt/sqlpackage/Microsoft.Build.dll
  inflating: /opt/sqlpackage/Microsoft.Build.Framework.dll
  inflating: /opt/sqlpackage/Microsoft.Build.Utilities.Core.dll
  inflating: /opt/sqlpackage/Microsoft.CSharp.dll
  inflating: /opt/sqlpackage/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.dll
  inflating: /opt/sqlpackage/Microsoft.Data.SqlClient.dll
  inflating: /opt/sqlpackage/Microsoft.Data.Tools.Schema.Sql.dll
  inflating: /opt/sqlpackage/Microsoft.Data.Tools.Schema.Sql.pdb
  inflating: /opt/sqlpackage/Microsoft.Data.Tools.Schema.Sql.xml
  inflating: /opt/sqlpackage/Microsoft.Data.Tools.Utilities.dll
  inflating: /opt/sqlpackage/Microsoft.Data.Tools.Utilities.pdb
  inflating: /opt/sqlpackage/Microsoft.Data.Tools.Utilities.xml
  inflating: /opt/sqlpackage/Microsoft.Extensions.Caching.Abstractions.dll
  inflating: /opt/sqlpackage/Microsoft.Extensions.Caching.Memory.dll
  inflating: /opt/sqlpackage/Microsoft.Extensions.DependencyInjection.Abstractions.dll
  inflating: /opt/sqlpackage/Microsoft.Extensions.Logging.Abstractions.dll
  inflating: /opt/sqlpackage/Microsoft.Extensions.Options.dll
  inflating: /opt/sqlpackage/Microsoft.Extensions.Primitives.dll
  inflating: /opt/sqlpackage/Microsoft.Identity.Client.dll
  inflating: /opt/sqlpackage/Microsoft.Identity.Client.Extensions.Msal.dll
  inflating: /opt/sqlpackage/Microsoft.IdentityModel.Abstractions.dll
  inflating: /opt/sqlpackage/Microsoft.IdentityModel.JsonWebTokens.dll
  inflating: /opt/sqlpackage/Microsoft.IdentityModel.Logging.dll
  inflating: /opt/sqlpackage/Microsoft.IdentityModel.Protocols.dll
  inflating: /opt/sqlpackage/Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
  inflating: /opt/sqlpackage/Microsoft.IdentityModel.Tokens.dll
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Dac.dll
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Dac.Extensions.dll
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Dac.Extensions.pdb
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Dac.Extensions.xml
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Dac.pdb
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Dac.xml
  inflating: /opt/sqlpackage/Microsoft.SqlServer.DacAzureExtensions.dll
  inflating: /opt/sqlpackage/Microsoft.SqlServer.DacAzureExtensions.pdb
  inflating: /opt/sqlpackage/Microsoft.SqlServer.DacAzureExtensions.xml
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Server.dll
  inflating: /opt/sqlpackage/Microsoft.SqlServer.TransactSql.ScriptDom.dll
  inflating: /opt/sqlpackage/Microsoft.SqlServer.Types.dll
  inflating: /opt/sqlpackage/Microsoft.VisualBasic.Core.dll
  inflating: /opt/sqlpackage/Microsoft.VisualBasic.dll
  inflating: /opt/sqlpackage/Microsoft.Win32.Primitives.dll
  inflating: /opt/sqlpackage/Microsoft.Win32.Registry.dll
  inflating: /opt/sqlpackage/Microsoft.Win32.SystemEvents.dll
  inflating: /opt/sqlpackage/mscorlib.dll
  inflating: /opt/sqlpackage/netstandard.dll
  inflating: /opt/sqlpackage/sqlpackage
  inflating: /opt/sqlpackage/sqlpackage.deps.json
  inflating: /opt/sqlpackage/sqlpackage.dll
  inflating: /opt/sqlpackage/sqlpackage.pdb
  inflating: /opt/sqlpackage/sqlpackage.runtimeconfig.json
  inflating: /opt/sqlpackage/sqlpackage.xml
  inflating: /opt/sqlpackage/System.AppContext.dll
  inflating: /opt/sqlpackage/System.Buffers.dll
  inflating: /opt/sqlpackage/System.Collections.Concurrent.dll
  inflating: /opt/sqlpackage/System.Collections.dll
  inflating: /opt/sqlpackage/System.Collections.Immutable.dll
  inflating: /opt/sqlpackage/System.Collections.NonGeneric.dll
  inflating: /opt/sqlpackage/System.Collections.Specialized.dll
  inflating: /opt/sqlpackage/System.ComponentModel.Annotations.dll
  inflating: /opt/sqlpackage/System.ComponentModel.Composition.dll
  inflating: /opt/sqlpackage/System.ComponentModel.DataAnnotations.dll
  inflating: /opt/sqlpackage/System.ComponentModel.dll
  inflating: /opt/sqlpackage/System.ComponentModel.EventBasedAsync.dll
  inflating: /opt/sqlpackage/System.ComponentModel.Primitives.dll
  inflating: /opt/sqlpackage/System.ComponentModel.TypeConverter.dll
  inflating: /opt/sqlpackage/System.Configuration.ConfigurationManager.dll
  inflating: /opt/sqlpackage/System.Configuration.dll
  inflating: /opt/sqlpackage/System.Console.dll
  inflating: /opt/sqlpackage/System.Core.dll
  inflating: /opt/sqlpackage/System.Data.Common.dll
  inflating: /opt/sqlpackage/System.Data.DataSetExtensions.dll
  inflating: /opt/sqlpackage/System.Data.dll
  inflating: /opt/sqlpackage/System.Diagnostics.Contracts.dll
  inflating: /opt/sqlpackage/System.Diagnostics.Debug.dll
  inflating: /opt/sqlpackage/System.Diagnostics.DiagnosticSource.dll
  inflating: /opt/sqlpackage/System.Diagnostics.FileVersionInfo.dll
  inflating: /opt/sqlpackage/System.Diagnostics.Process.dll
  inflating: /opt/sqlpackage/System.Diagnostics.StackTrace.dll
  inflating: /opt/sqlpackage/System.Diagnostics.TextWriterTraceListener.dll
  inflating: /opt/sqlpackage/System.Diagnostics.Tools.dll
  inflating: /opt/sqlpackage/System.Diagnostics.TraceSource.dll
  inflating: /opt/sqlpackage/System.Diagnostics.Tracing.dll
  inflating: /opt/sqlpackage/System.dll
  inflating: /opt/sqlpackage/System.Drawing.Common.dll
  inflating: /opt/sqlpackage/System.Drawing.dll
  inflating: /opt/sqlpackage/System.Drawing.Primitives.dll
  inflating: /opt/sqlpackage/System.Dynamic.Runtime.dll
  inflating: /opt/sqlpackage/System.Formats.Asn1.dll
  inflating: /opt/sqlpackage/System.Globalization.Calendars.dll
  inflating: /opt/sqlpackage/System.Globalization.dll
  inflating: /opt/sqlpackage/System.Globalization.Extensions.dll
  inflating: /opt/sqlpackage/System.IdentityModel.Tokens.Jwt.dll
  inflating: /opt/sqlpackage/System.IO.Compression.Brotli.dll
  inflating: /opt/sqlpackage/System.IO.Compression.dll
  inflating: /opt/sqlpackage/System.IO.Compression.FileSystem.dll
  inflating: /opt/sqlpackage/System.IO.Compression.ZipFile.dll
  inflating: /opt/sqlpackage/System.IO.dll
  inflating: /opt/sqlpackage/System.IO.FileSystem.AccessControl.dll
  inflating: /opt/sqlpackage/System.IO.FileSystem.dll
  inflating: /opt/sqlpackage/System.IO.FileSystem.DriveInfo.dll
  inflating: /opt/sqlpackage/System.IO.FileSystem.Primitives.dll
  inflating: /opt/sqlpackage/System.IO.FileSystem.Watcher.dll
  inflating: /opt/sqlpackage/System.IO.IsolatedStorage.dll
  inflating: /opt/sqlpackage/System.IO.MemoryMappedFiles.dll
  inflating: /opt/sqlpackage/System.IO.Packaging.dll
  inflating: /opt/sqlpackage/System.IO.Pipes.AccessControl.dll
  inflating: /opt/sqlpackage/System.IO.Pipes.dll
  inflating: /opt/sqlpackage/System.IO.UnmanagedMemoryStream.dll
  inflating: /opt/sqlpackage/System.Linq.dll
  inflating: /opt/sqlpackage/System.Linq.Expressions.dll
  inflating: /opt/sqlpackage/System.Linq.Parallel.dll
  inflating: /opt/sqlpackage/System.Linq.Queryable.dll
  inflating: /opt/sqlpackage/System.Memory.Data.dll
  inflating: /opt/sqlpackage/System.Memory.dll
  inflating: /opt/sqlpackage/System.Net.dll
  inflating: /opt/sqlpackage/System.Net.Http.dll
  inflating: /opt/sqlpackage/System.Net.Http.Json.dll
  inflating: /opt/sqlpackage/System.Net.HttpListener.dll
  inflating: /opt/sqlpackage/System.Net.Mail.dll
  inflating: /opt/sqlpackage/System.Net.NameResolution.dll
  inflating: /opt/sqlpackage/System.Net.NetworkInformation.dll
  inflating: /opt/sqlpackage/System.Net.Ping.dll
  inflating: /opt/sqlpackage/System.Net.Primitives.dll
  inflating: /opt/sqlpackage/System.Net.Quic.dll
  inflating: /opt/sqlpackage/System.Net.Requests.dll
  inflating: /opt/sqlpackage/System.Net.Security.dll
  inflating: /opt/sqlpackage/System.Net.ServicePoint.dll
  inflating: /opt/sqlpackage/System.Net.Sockets.dll
  inflating: /opt/sqlpackage/System.Net.WebClient.dll
  inflating: /opt/sqlpackage/System.Net.WebHeaderCollection.dll
  inflating: /opt/sqlpackage/System.Net.WebProxy.dll
  inflating: /opt/sqlpackage/System.Net.WebSockets.Client.dll
  inflating: /opt/sqlpackage/System.Net.WebSockets.dll
  inflating: /opt/sqlpackage/System.Numerics.dll
  inflating: /opt/sqlpackage/System.Numerics.Vectors.dll
  inflating: /opt/sqlpackage/System.ObjectModel.dll
  inflating: /opt/sqlpackage/System.Private.CoreLib.dll
  inflating: /opt/sqlpackage/System.Private.DataContractSerialization.dll
  inflating: /opt/sqlpackage/System.Private.Uri.dll
  inflating: /opt/sqlpackage/System.Private.Xml.dll
  inflating: /opt/sqlpackage/System.Private.Xml.Linq.dll
  inflating: /opt/sqlpackage/System.Reflection.DispatchProxy.dll
  inflating: /opt/sqlpackage/System.Reflection.dll
  inflating: /opt/sqlpackage/System.Reflection.Emit.dll
  inflating: /opt/sqlpackage/System.Reflection.Emit.ILGeneration.dll
  inflating: /opt/sqlpackage/System.Reflection.Emit.Lightweight.dll
  inflating: /opt/sqlpackage/System.Reflection.Extensions.dll
  inflating: /opt/sqlpackage/System.Reflection.Metadata.dll
  inflating: /opt/sqlpackage/System.Reflection.Primitives.dll
  inflating: /opt/sqlpackage/System.Reflection.TypeExtensions.dll
  inflating: /opt/sqlpackage/System.Resources.Extensions.dll
  inflating: /opt/sqlpackage/System.Resources.Reader.dll
  inflating: /opt/sqlpackage/System.Resources.ResourceManager.dll
  inflating: /opt/sqlpackage/System.Resources.Writer.dll
  inflating: /opt/sqlpackage/System.Runtime.Caching.dll
  inflating: /opt/sqlpackage/System.Runtime.CompilerServices.Unsafe.dll
  inflating: /opt/sqlpackage/System.Runtime.CompilerServices.VisualC.dll
  inflating: /opt/sqlpackage/System.Runtime.dll
  inflating: /opt/sqlpackage/System.Runtime.Extensions.dll
  inflating: /opt/sqlpackage/System.Runtime.Handles.dll
  inflating: /opt/sqlpackage/System.Runtime.InteropServices.dll
  inflating: /opt/sqlpackage/System.Runtime.InteropServices.RuntimeInformation.dll
  inflating: /opt/sqlpackage/System.Runtime.Intrinsics.dll
  inflating: /opt/sqlpackage/System.Runtime.Loader.dll
  inflating: /opt/sqlpackage/System.Runtime.Numerics.dll
  inflating: /opt/sqlpackage/System.Runtime.Serialization.dll
  inflating: /opt/sqlpackage/System.Runtime.Serialization.Formatters.dll
  inflating: /opt/sqlpackage/System.Runtime.Serialization.Json.dll
  inflating: /opt/sqlpackage/System.Runtime.Serialization.Primitives.dll
  inflating: /opt/sqlpackage/System.Runtime.Serialization.Xml.dll
  inflating: /opt/sqlpackage/System.Security.AccessControl.dll
  inflating: /opt/sqlpackage/System.Security.Claims.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.Algorithms.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.Cng.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.Csp.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.Encoding.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.OpenSsl.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.Primitives.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.ProtectedData.dll
  inflating: /opt/sqlpackage/System.Security.Cryptography.X509Certificates.dll
  inflating: /opt/sqlpackage/System.Security.dll
  inflating: /opt/sqlpackage/System.Security.Permissions.dll
  inflating: /opt/sqlpackage/System.Security.Principal.dll
  inflating: /opt/sqlpackage/System.Security.Principal.Windows.dll
  inflating: /opt/sqlpackage/System.Security.SecureString.dll
  inflating: /opt/sqlpackage/System.ServiceModel.Web.dll
  inflating: /opt/sqlpackage/System.ServiceProcess.dll
  inflating: /opt/sqlpackage/System.Text.Encoding.CodePages.dll
  inflating: /opt/sqlpackage/System.Text.Encoding.dll
  inflating: /opt/sqlpackage/System.Text.Encoding.Extensions.dll
  inflating: /opt/sqlpackage/System.Text.Encodings.Web.dll
  inflating: /opt/sqlpackage/System.Text.Json.dll
  inflating: /opt/sqlpackage/System.Text.RegularExpressions.dll
  inflating: /opt/sqlpackage/System.Threading.Channels.dll
  inflating: /opt/sqlpackage/System.Threading.dll
  inflating: /opt/sqlpackage/System.Threading.Overlapped.dll
  inflating: /opt/sqlpackage/System.Threading.Tasks.Dataflow.dll
  inflating: /opt/sqlpackage/System.Threading.Tasks.dll
  inflating: /opt/sqlpackage/System.Threading.Tasks.Extensions.dll
  inflating: /opt/sqlpackage/System.Threading.Tasks.Parallel.dll
  inflating: /opt/sqlpackage/System.Threading.Thread.dll
  inflating: /opt/sqlpackage/System.Threading.ThreadPool.dll
  inflating: /opt/sqlpackage/System.Threading.Timer.dll
  inflating: /opt/sqlpackage/System.Transactions.dll
  inflating: /opt/sqlpackage/System.Transactions.Local.dll
  inflating: /opt/sqlpackage/System.ValueTuple.dll
  inflating: /opt/sqlpackage/System.Web.dll
  inflating: /opt/sqlpackage/System.Web.HttpUtility.dll
  inflating: /opt/sqlpackage/System.Windows.dll
  inflating: /opt/sqlpackage/System.Windows.Extensions.dll
  inflating: /opt/sqlpackage/System.Xml.dll
  inflating: /opt/sqlpackage/System.Xml.Linq.dll
  inflating: /opt/sqlpackage/System.Xml.ReaderWriter.dll
  inflating: /opt/sqlpackage/System.Xml.Serialization.dll
  inflating: /opt/sqlpackage/System.Xml.XDocument.dll
  inflating: /opt/sqlpackage/System.Xml.XmlDocument.dll
  inflating: /opt/sqlpackage/System.Xml.XmlSerializer.dll
  inflating: /opt/sqlpackage/System.Xml.XPath.dll
  inflating: /opt/sqlpackage/System.Xml.XPath.XDocument.dll
  inflating: /opt/sqlpackage/WindowsBase.dll
  inflating: /opt/sqlpackage/LICENSE.TXT
--> a01dfa6ed2c8
STEP 7/7: LABEL "com.docker.compose.image.builder"="classic"
COMMIT docker.io/library/devcontainer-app
--> fe408a709f8f
[Warning] one or more build args were not consumed: [DOCKER_BUILDKIT]
Successfully tagged docker.io/library/devcontainer-app:latest
fe408a709f8f67e2510d760cb1c7dd0977e8f409e20640f166762332b4d79846
Successfully built fe408a709f8f
Successfully tagged devcontainer-app
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
[+] Running 2/2
 ✔ Container devcontainer-db-1   Created                                                                                                       0.1s
 ✔ Container devcontainer-app-1  Created                                                                                                       1.4s
Attaching to app-1, db-1
db-1   | SQL Server 2022 will run as non-root by default.
db-1   | This container is running as user mssql.
db-1   | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: crun: mount `sysfs` to `sys`: Operation not permitted: OCI permission denied
Error: executing C:\ProgramData\Docker\cli-plugins\docker-compose.exe up: exit status 1
```

</details>
```


### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
