### ISSUE TITLE
Quadlet with [Pod] dns problem with latest podman-next 5.0.0-dev-e59544189 from fedora39

### ISSUE THREAD

**Issue by chrismaster** [containers/podman#21688]
### Issue Description

Got two rootless quadlets in ~/.config/containers/systemd
dashy.pod
```
[Pod]
PodName=dashyPOD
PublishPort=8086:80
```
dashy.container
```
[Unit]
Description=DashyAPP
After=local-fs.target

[Container]
Image=ghcr.io/lissy93/dashy:latest
ContainerName=dashy
Volume=%h/dashyDATA.yml:/app/public/conf.yml:Z
Environment=NODE_ENV=production
#PublishPort=8086:80
UserNS=auto
AutoUpdate=registry
Pod=dashy.pod

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
```
Without pod there are no dns problesm, with .pod configuration I get  
`Error: getaddrinfo ENOTFOUND dashyPOD`

I think --add-host=host:ip is not allowed in .pod so I can't set the hostname for dashyPOD....

For this example there has to be a dashyDATA.yml file in ~
dashyData.yml
```
pageInfo:
  title: Home Lab
sections: # An array of sections
- name: Example Section
  icon: far fa-rocket
  items:
  - title: GitHub
    description: Dashy source code and docs
    icon: fab fa-github
    url: https://github.com/Lissy93/dashy
  - title: Issues
    description: View open issues, or raise a new one
    icon: fas fa-bug
    url: https://github.com/Lissy93/dashy/issues
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a passwordless rootless someexampleusername
2. Login to the user with eg sudo machinectl shell --uid someexampleusername
3. Take the two quadlets and copy them to ~/.confic/containers/systemd/
4. Copy the example dashyDATA.yml to home
5. systemctl --user daemon-reload
6. systemctl --user restart dashy-pod

### Describe the results you received

Feb 16 06:36:27 someexampleusername dashy[80696]: Error: getaddrinfo ENOTFOUND dashyPOD
Feb 16 06:36:27 someexampleusername dashy[80696]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
Feb 16 06:36:27 someexampleusername dashy[80696]:   errno: -3008,
Feb 16 06:36:27 someexampleusername dashy[80696]:   code: 'ENOTFOUND',
Feb 16 06:36:27 someexampleusername dashy[80696]:   syscall: 'getaddrinfo',
Feb 16 06:36:27 someexampleusername dashy[80696]:   hostname: 'dashyPOD'
Feb 16 06:36:27 someexampleusername dashy[80696]: }
Feb 16 06:36:27 someexampleusername dashy[80696]: error Command failed with exit code 1.

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
starting app
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
