### ISSUE TITLE
ls: cannot open directory '.': Permission denied in host mounted paths

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [containers/podman#22004]
### Issue Description

Describe your issue

If using a monted path we have a denied acess, this with root command too.

### Steps to reproduce the issue

Steps to reproduce the issue
1. set the envs for paths
2. run "podman run --rm -v $PACKAGES_DIR:/buildd -v $KERNEL_DIR:/buildd/sources -it quay.io/droidian/build-essential:trixie-amd64 bash"
3. if be to buildd we get a ls: cannot open directory '.': Permission denied

### Describe the results you received

Describe the results you received

ls: cannot open directory '.': Permission denied

### Describe the results you expected

Describe the results you expected

Enter in the Directory 

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

Client:       Podman Engine
Version:      5.0.0-rc1
API Version:  5.0.0-rc1
Go Version:   go1.22.0
Built:        Sun Feb 11 20:38:54 2024
OS/Arch:      linux/amd64

Running Fedora Silverblue Rawhide
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
