### ISSUE TITLE
Podman info has become slower again, when running on ubuntu or debian

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#22102]
### Feature request description

Previously we were able to speed up the execution time of `podman info`, by using `dlocate`

* #19317

But it still takes a long time to execute, and it has gotten longer with 4.9/5.0 compared to 3.4

When using `podman info` (or `podman-remote version`) to test, the delay can be annoying...

### Suggest potential solution

When querying deb packages, containers-common should use "dlocate" for both searches.

It should also **not** try again with dpkg and dpkg-query, if already tried it with dlocate.

### Have you considered any alternatives?

There could be a configuration to hide the packaging information from the output, perhaps

Other container runtimes are using the output from `--version`, rather than the package

### Additional context

It seems that for some reason it is also slowing down podman-remote version? Not only info

`time podman-remote version` takes 5 seconds to execute, while it probably should not do so

**Comment by afbjorklund** [comment]
When installing `dlocate` and the text database, it takes less than a second (which is still OK)

With `debfile` and the binary database, the execution time is a fraction of a second (<100 ms)

The main reason it is slower in Podman v5 compared to v3, is the large number of new / unpackaged helpers...

And that the version code assumes that it is reasonable fast to look up versions, like it is when using `rpm -qf`.

**Comment by afbjorklund** [comment]
The program `pasta` dumps some license spam in the output of --version, it probably needs filtering out?

```
  pasta:
    executable: /usr/local/libexec/podman/pasta
    package: Unknown
    version: |
      pasta 2024_02_20.1e6f92b
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
```

when compared with a more relevant (although non-standard)

```
  slirp4netns:
    executable: /usr/local/libexec/podman/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.1.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
```
