### ISSUE TITLE
Cannot run a pod with ipvlan network and host as a parent

### ISSUE THREAD

**Issue by sb-101** [containers/podman#22111]
### Issue Description

Hi guys,

I am facing an issue with my **rootless podman** trying to **attach an ipvlan network created with the host as a parent**,
I always get an error: `Error: netavark: Netlink error: No such device (os error 19)`

It works with sudo but I don't want to use it :-)
Thank you for your help !

BR.

### Steps to reproduce the issue

**1. creation of network:**
`$ podman network create -d ipvlan --subnet=192.168.1.0/24 --gateway 192.168.1.1 -o parent=eth0 host_network`
network created.

**2. creation of vm:**
`$ podman run --net=host_network --ip=192.168.1.20 -it --rm alpine /bin/sh`
As rootless, that gives me an error: `Error: netavark: Netlink error: No such device (os error 19)`
But if I use sudo, it works. The aim is to have a rootless pod and not a pod created with sudo :)

### Describe the results you received

**1. creation of network:** ok

**2. creation of vm:** gives me an error: `Error: netavark: Netlink error: No such device (os error 19)`
But if I use sudo, it works. The aim is to have a rootless pod and not a pod created with sudo :)

### Describe the results you expected

I expected to have a rootless pod using the same network than the host, but not a pod created with sudo :)

### podman info output

```yaml
Podman version: (installed with dnf install)
Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.20.10
Built:        Tue Mar  5 23:07:04 2024
OS/Arch:      linux/amd64`

OS: Almalinux on latest version 9.3 (up to date)
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
