### ISSUE TITLE
e2e: kube play, huge annotation: podman rm hangs

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#22246]
Seeing a new flake recently, so far only in podman-remote root. Not OS-specific:
```
Podman kube play
  test with annotation size within limits
....
# podman-remote [options] kube play /var/tmp/pme2e-1564132875/pm3097852031/kube.yaml
[works fine]
← Exit  [It] test with annotation size within limits
→ Enter [AfterEach] TOP-LEVEL
# podman-remote [options] stop --all -t 0
[works fine]
# podman-remote [options] pod rm -fa -t 0

[FAILED] Timed out after 90.000s.
```

* debian-13 : int remote debian-13 root host sqlite [remote]
    * [04-02 12:13](https://api.cirrus-ci.com/v1/artifact/task/6139292626452480/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1) in TOP-LEVEL [AfterEach] Podman kube play test with annotation size within limits
    * [04-01 13:30](https://api.cirrus-ci.com/v1/artifact/task/5682052488495104/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1) in TOP-LEVEL [AfterEach] Podman kube play test with annotation size within limits
    * [03-26 14:32](https://api.cirrus-ci.com/v1/artifact/task/5092261734645760/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1) in TOP-LEVEL [AfterEach] Podman kube play test with annotation size within limits
* fedora-39 : int remote fedora-39 root host sqlite [remote]
    * [04-02 08:52](https://api.cirrus-ci.com/v1/artifact/task/4904182371581952/html/int-remote-fedora-39-root-host-sqlite.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1) in TOP-LEVEL [AfterEach] Podman kube play test with annotation size within limits
* rawhide : int remote rawhide root host sqlite [remote]
    * [04-02 21:12](https://api.cirrus-ci.com/v1/artifact/task/6674818871853056/html/int-remote-rawhide-root-host-sqlite.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1) in TOP-LEVEL [AfterEach] Podman kube play test with annotation size within limits

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(5) | remote(5) | debian-13(3) | root(5) | host(5) | sqlite(5) |
|  |  | rawhide(1) |  |  |  |
|  |  | fedora-39(1) |  |  |  |

**Comment by edsantiago** [comment]
I instrumented my no-retries PR, to dump the yaml, and here it is [f39 remote root](https://api.cirrus-ci.com/v1/artifact/task/6436086845538304/html/int-remote-fedora-39-root-host-sqlite.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1):
```
           apiVersion: v1
           kind: Pod
           metadata:
             creationTimestamp: "2019-07-17T14:44:08Z"
             name: testPod
             labels:
               app: testPod
         
         
             annotations:
             
               name: SOMETHING TOO LONG FOR GITHUB TO LET ME PUT IN A COMMENT             
         
         
           spec:
             restartPolicy: Never
             hostname: 
             hostNetwork: false
         
             hostAliases:
             initContainers:
             containers:
             - command:
               - top
               args:
               - -d
               - 1.5
               env:
               - name: HOSTNAME
               image: quay.io/libpod/testimage:20240123
               name: testCtr
               imagePullPolicy: missing
               securityContext:
                 allowPrivilegeEscalation: true
                 privileged: false
                 readOnlyRootFilesystem: false
               ports:
               - containerPort: 
                 hostIP: 
                 hostPort: 
                 protocol: TCP
               workingDir: /
               volumeMounts:
           status: {}
           # podman-remote [options] kube play /var/tmp/podman-e2e-1368536477/subtest-2044718688/kube.yaml
           Pod:
           0ca4807ad93b155bc3c542fb835620d492581d937217f3f43cf260a0b90942b7
           Container:
           7db8ba2673e8a2f2fd99803932a9914b0273438795962bbf2b05b49b14535139

[hang]
```
