### ISSUE TITLE
Podman compose windows VM volume mount issue

### ISSUE THREAD

**Issue by tppalani** [containers/podman#22289]
### Issue Description

Not able to Run the compose file is that any special volume mount path need be set when we are using widows VM?

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

compose yaml

```
version: '3'
services:
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/mysql:5.7
    container_name: mysql_3306
    restart: unless-stopped                                   
    volumes:
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/init-file.sql:/etc/mysql/init-file.sql"
      - "./mysql/data:/var/lib/mysql"
#      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/log/mysql/error.log:/var/log/mysql/error.log"
      - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d" # init sql script directory -- tips: it can be excute  when `/var/lib/mysql` is empty
    environment:                        # set environment,equals docker run -e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root         # set root password
      MYSQL_DATABASE: demo              # init database name
    ports:                              # port mappping
      - "3306:3306"
```

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
Error: crun: mount `/mnt/c/Users/viswa/workspace/Hikari/mysql/my.cnf` to `etc/mysql/my.cnf`: Not a directory: OCI runtime error
exit code: 126
podman start mysql_3306
Error: unable to start container "d387d64cf06b3c851cedb47f6b986e6bcee5eeddae9dff3c2d65509ba2b8937a": crun: mount `/mnt/c/Users/viswa/workspace/Hikari/mysql/my.cnf` to `etc/mysql/my.cnf`: Not a directory: OCI runtime error
exit code: 125
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
