### ISSUE TITLE
Revert to  slirp4netns

### ISSUE THREAD

**Issue by gdonval** [containers/podman#22363]
### Issue Description

Pasta is not fit for purpose: it fails when used in rootless containers (https://github.com/containers/podman/issues/22197 and https://github.com/containers/podman/issues/22190) and breaks existing installations.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set up a quadlet that requires net.
2. Reboot.
3. See the quadlet randomly work or not.
4. When it doesn't, run `sudo journalctl` and see:
   

### Describe the results you received

Describe the results you received

```pasta[...]: External interface not usable```

### Describe the results you expected

Describe the results you expected

I expect my containers to run every single time like it did before with slirp4netns.

How do you want to be taken seriously vs Docker when you push broken software?

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

Client:       Podman Engine
Version:      5.0.0
API Version:  5.0.0
Go Version:   go1.22.0
Built:        Tue Mar 19 00:00:00 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

Fedora CoreOS, guys, not a 3rd party distro.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

It might be good to write tests too, so that changes like this one can be tested first, instead of waiting for your customers to yell when it fails.
