### ISSUE TITLE
swagger specs are missing definitions of `definitions` after version 3

### ISSUE THREAD

**Issue by wez** [containers/podman#22499]
I've been looking at generating a client for the podman API and noticed this issue.
It affects essentially all of the definitions in the openapi spec, not just the one I use here as an example.

Take a look at https://storage.googleapis.com/libpod-master-releases/swagger-v3.4.4.yaml; it has this definition for `AuthConfig`, which declares fields and types, and looks generally very useful:

```yaml
AuthConfig:
  description: AuthConfig contains authorization information for connecting to a
    Registry
  properties:
    auth:
      type: string
      x-go-name: Auth
    email:
      description: |-
        Email is an optional value associated with the username.
        This field is deprecated and will be removed in a later
        version of docker.
      type: string
      x-go-name: Email
    identitytoken:
      description: |-
        IdentityToken is used to authenticate the user and get
        an access token for the registry.
      type: string
      x-go-name: IdentityToken
    password:
      type: string
      x-go-name: Password
    registrytoken:
      description: RegistryToken is a bearer token to be sent to a registry
      type: string
      x-go-name: RegistryToken
    serveraddress:
      type: string
      x-go-name: ServerAddress
    username:
      type: string
      x-go-name: Username
  type: object
  x-go-package: github.com/containers/podman/pkg/domain/entities/types
```

Compare with https://storage.googleapis.com/libpod-master-releases/swagger-v4.9.4.yaml and https://storage.googleapis.com/libpod-master-releases/swagger-v5.0.1.yaml, all that is included is a non-standard reference to a go package, which is not very useful:

```yaml
AuthConfig:
    x-go-package: github.com/containers/podman/v5/pkg/domain/entities/types
```

AFAICT, this makes it impossible to generate code for these definitions in non-golang environments.

I don't really know that much about swagger/openapi, or the build process used here to extract the spec from the code, but I did find https://github.com/go-swagger/go-swagger/issues/2119 where it is discussed that these `x-go-` extension fields can be harmful, and it suggests that setting `SWAGGER_GENERATE_EXTENSION=false` in the environment is a way to prevent those from being generated when running the swagger code generator.

```console
SWAGGER_GENERATE_EXTENSION=false && swagger generate spec -o ./swagger.yml
```

Perhaps this is simply(!?) fixed by exporting that variable in the CI process?

I did try to take a quick run at trying this out, but I'm on ubuntu 22.04 and not a golang person, and I was immediately defeated by not having a new enough version of golang available, and I'm already 3 levels further down a rabbit hole than I intended to be, so I had to stop digging here. Sorry!
