### ISSUE TITLE
podman: exec not signaling child processes upon receiving termination signal

### ISSUE THREAD

**Issue by agorgl** [containers/podman#22495]
### Issue Description

Processes inside a container spawned by `podman exec` invocations are not killed when the `podman exec` invocation in the host that spawned them receives a kill signal itself

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run a simple container using `podman run --rm -it --name alpine alpine`
2. Watch the processes in the container using `watch -n 1 ps aux`
3. Exec a command from the host using `podman exec -it alpine /bin/sh -c 'sleep 1000'`
4. Find the podman exec pid in the host using `ps aux | grep podman | grep sleep` and kill it using `kill <pid>`

### Describe the results you received

Watch as the `podman exec` invocation gets killed in the host, but the process inside the container is not signaled and keeps running.

### Describe the results you expected

For the process `exec`ed by `podman exec` to be signaled to terminate upon killing the `podman exec` process itself

### podman info output

```yaml
❯ podman version                                                                                                                                                                 1m 13s
Client:       Podman Engine
Version:      5.0.2
API Version:  5.0.2
Go Version:   go1.22.2
Git Commit:   3304dd95b8978a8346b96b7d43134990609b3b29-dirty
Built:        Thu Apr 18 14:13:19 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes
