### ISSUE TITLE
podman pull does not use https_proxy when using podman machine, but will use on linux

### ISSUE THREAD

**Issue by sedyh** [containers/podman#22898]
### Issue Description

Hello. I'm making a mitm proxy that prevents image downloading when the critical vulnerability was found.
I noticed that the behavior for reading environment variables on macos is very different from the behavior on linux.
I would like to be able to specify a proxy only for single image pulling command without exporting it globally, as in docker (just like how podman works on linux right now).

I read this discussion, but I need to be able to launch the podman machine without a proxy (because it will not start if I try to get podman/machine-os through it, since the proxy is not ready yet), and only then use it for pulling.
https://github.com/containers/podman/issues/11941

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init
2. podman machine start
3. https_proxy="user:pass@127.0.0.1:9991" podman pull alpine:3.18

### Describe the results you received

linux: podman used the proxy
macos: podman didn't use the proxy

### Describe the results you expected

linux: podman used the proxy
macos: podman used the proxy

### podman info output

```yaml
Client:       Podman Engine
Version:      5.1.0
API Version:  5.1.0
Go Version:   go1.22.3
Git Commit:   4e9486dbc63c24bfe109066abbb54d5d8dc2489e
Built:        Wed May 29 21:52:05 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.1.0-dev-c9808e7ed
API Version:  5.1.0-dev-c9808e7ed
Go Version:   go1.22.2
Built:        Mon May 13 03:00:00 2024
OS/Arch:      linux/arm64
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_
