### ISSUE TITLE
Cannot ssh into machine with networkingMode=mirrored

### ISSUE THREAD

**Issue by damlys99** [containers/podman#22975]
### Issue Description

After setting networkingMode=mirrored in .wslconfig I'm no longer able to use Podman Desktop.
That happens only after upgrading Podman Desktop version (I don't remember from what version exactly, but Podman on the machine got upgraded from 4.9.3 to 5.0.3).

I have HyperVFirewall disabled.
What's unusual, after starting other WSL distro - ubuntu in other cmd, issues are disappearing, as that somehow triggers network to mirror

### Steps to reproduce the issue

1. Set networkingMode=Mirrored in .wslconfig
2. wsl --shutdown
3. podman machine start
5. "Bash" in cmd (starts Ubuntu - default distro for me)
6. podman machine ssh - works

### Describe the results you received

Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        could not start api proxy since expected pipe is not available: podman-machine-default

Podman clients are still able to connect.
Error: machine did not transition into running state: ssh error: machine is not listening on ssh port

podman machine ssh - timeouts
but after starting Ubuntu with "Bash" in other cmd
podman machine ssh - works, docker ps works etc.

### Describe the results you expected

podman machine start
podman machine ssh
*works*

### podman info output

```yaml
Client:       Podman Engine
Version:      5.0.3
API Version:  5.0.3
Go Version:   go1.22.3
Git Commit:   d08315df35cb6e95f65bf3935f529295c6e54742
Built:        Fri May 10 20:02:40 2024
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      5.0.3
API Version:  5.0.3
Go Version:   go1.22.2
Built:        Fri May 10 02:00:00 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

HyperV Firewall is disabled

.wslconfig
```
[wsl2]
networkingMode=mirrored
dnsTunneling=true
autoProxy=true

[experimental]
hostAddressLoopback=true
```
