### ISSUE TITLE
Podman

### ISSUE THREAD

**Issue by POnakS** [containers/podman#23000]
### Issue Description

Regression in new podman machine images, machine does not start correctly

### Steps to reproduce the issue

Steps to reproduce the issue
1. Configure WSL to use mirrored mode
2. Install latest podman desktop (v1.10.3) and latest podman (v5.1.1)
3. Create machine via podman desktop or cli
4. call `podman machine start`

### Describe the results you received

```
Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

Podman clients are still able to connect.
Error: machine did not transition into running state: ssh error: machine is not listening on ssh port
```

Machine is listed as running when I do `podman machine list`
`podman machine ssh` times out.
Docker socket is not available.

### Describe the results you expected

Podman machine starts and socket is available, I can ssh into the machine.

### podman info output

```yaml
host:
    arch: amd64
    currentmachine: podman-machine-default
    defaultmachine: podman-machine-default
    eventsdir: C:\Users\redacted\.local\share\containers\podman\podman
    machineconfigdir: C:\Users\redacted\.config\containers\podman\machine\wsl
    machineimagedir: C:\Users\redacted\.local\share\containers\podman\machine\wsl
    machinestate: Running
    numberofmachines: 1
    os: windows
    vmtype: wsl
version:
    apiversion: 5.1.1
    version: 5.1.1
    goversion: go1.22.3
    gitcommit: bda6eb03dcbcf12a5b7ae004c1240e38dd056d24
    builttime: Tue Jun  4 23:40:05 2024
    built: 1717537205
    osarch: windows/amd64
    os: windows
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

I've tried multiple machines:

- Default for podman v5.1.1 does not work
- [v20240614061401](https://github.com/containers/podman-machine-wsl-os/releases/tag/v20240614061401) - does not work
- [v20240417162145](https://github.com/containers/podman-machine-wsl-os/releases/tag/v20240417162145) - newest one which works

### Additional information

Maybe related to however these issues may have different root causes:
https://github.com/containers/podman/issues/22975
https://github.com/containers/podman/issues/22240
