### ISSUE TITLE
unlinkat directory not empty on commit (rootless)

### ISSUE THREAD

**Issue by dg424** [containers/podman#23023]
### Issue Description

Getting the following error "randomly" when trying to build an image using the following command -> podman build --isolation chroot -t <tag> .

`17:11:18  COMMIT foo:latest
17:11:18  --> 4434cee3fd5
17:11:18  Successfully tagged localhost/foo:latest
17:11:32  time="2024-06-14T21:11:30Z" level=error msg="error deleting build container \"dffdfc25f7f9f183eaca0c83ad95cd42daa5fbe0f33ec56cc8c525f3b0d5a98f\": 1 error occurred:\n\t* unlinkat /var/lib/containers/storage/vfs/dir/2157acd33ff63d42f27f2b14276c62bd0dea9d6d856849bad18da2220dfdf9e9: directory not empty\n\n\n"
17:11:32  Error: unlinkat /var/lib/containers/storage/vfs/dir/2157acd33ff63d42f27f2b14276c62bd0dea9d6d856849bad18da2220dfdf9e9: directory not empty
`

Any ideas/things to try etc ?

### Steps to reproduce the issue

Unfortunately, the issue cannot be reproduced reliably and as stated in the description, it seems to occur randomly.

### Describe the results you received

See description

### Describe the results you expected

No error and a successful image build.

### podman info output

```yaml
bash-4.4# podman version
WARN[0000] Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user 
Client:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.19.10
Built:        Wed Oct  4 14:55:19 2023
OS/Arch:      linux/amd64
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Runs on an GCP compute engine instance

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
