### ISSUE TITLE
Failed to start a x86 podman machine (5.1.2) on Apple MacOS M1 14.5 with applehv

### ISSUE THREAD

**Issue by marvin659** [containers/podman#23256]
### Issue Description

I tried to create a podman machine (x86) on Apple MacOS 14.5 M1 but failed. I need to run a x86 machine sometimes since I need to work on x86 for some work.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run `podman machine init --image-path https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20240407.3.0/x86_64/fedora-coreos-39.20240407.3.0-qemu.x86_64.qcow2.xz intel`
2. Run `podman machine start intel`

### Describe the results you received

See the error `Starting machine "intel" Error: vfkit exited unexpectedly with exit code 0`

### Describe the results you expected

The X86 machine should be started

### podman info output

```yaml
podman info                       
OS: darwin/arm64
provider: applehv
version: 5.1.2

vfkit --version
vfkit version: 0.5.1

I have Rosetta 2 installed.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

vfkit --version
vfkit version: 0.5.1

podman --version
podman version 5.1.2
