### ISSUE TITLE
podman version 5.1.1 fail to remove image: tag not known

### ISSUE THREAD

**Issue by jianzhangbjz** [containers/podman#23315]
### Issue Description

podman version 5.1.1 fail to remove image: tag not known
```console
jiazha-mac:test jiazha$  podman images 
REPOSITORY                                                 TAG         IMAGE ID      CREATED         SIZE
<none>                                                     <none>      c554891cf5ef  15 minutes ago  875 MB
quay.io/openshifttest/etcd-index                           33450       c7714389537d  15 minutes ago  1.94 kB
<none>                                                     <none>      61849e3068d0  16 minutes ago  656 MB
<none>                                                     <none>      0e677047f1e8  16 minutes ago  724 MB
<none>                                                     <none>      f55631f76979  18 minutes ago  671 MB
registry.redhat.io/openshift4/ose-operator-registry-rhel9  v4.16       a3ebe997b487  7 days ago      875 MB

jiazha-mac:test jiazha$ podman rmi quay.io/openshifttest/etcd-index:33450
Error: quay.io/openshifttest/etcd-index:33450: tag not known

jiazha-mac:test jiazha$ podman --version
podman version 5.1.1
```
But, podman 4.9.4 works well.
```console
[cloud-user@preserve-olm-env2 opm]$ podman rmi quay.io/openshifttest/etcd-index:33450
Untagged: quay.io/openshifttest/etcd-index:33450
Deleted: f55631f76979fbe1c9620b82799a9becba13b0303831eeb988b482390e109b9d
[cloud-user@preserve-olm-env2 opm]$ podman --version
podman version 4.9.4-rhel
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman pull quay.io/openshifttest/etcd-index:33450
2. podman rmi quay.io/openshifttest/etcd-index:33450
3.

### Describe the results you received

Describe the results you received
```console
jiazha-mac:test jiazha$ podman rmi quay.io/openshifttest/etcd-index:33450
Error: quay.io/openshifttest/etcd-index:33450: tag not known
```

### Describe the results you expected

podman rmi can remove the tag image.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

jiazha-mac:test jiazha$ podman version
Client:       Podman Engine
Version:      5.1.1
API Version:  5.1.1
Go Version:   go1.22.3
Git Commit:   bda6eb03dcbcf12a5b7ae004c1240e38dd056d24
Built:        Wed Jun  5 05:34:52 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.1.2
API Version:  5.1.2
Go Version:   go1.22.5
Built:        Wed Jul 10 08:00:00 2024
OS/Arch:      linux/arm64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
