### ISSUE TITLE
Rootless podman run result in different UID/GID from podman unshare

### ISSUE THREAD

**Issue by SoloGao** [containers/podman#23370]
### Issue Description

Rootless podman is deployed in our machines for years. Recently one of our users found he is unable to write any data in mounted folders. We then dig into it for a bit.

The user have subuid/subgid of 513998848:65536.

We are sure that all files in the folder belongs to the user. 

When we use podman unshare shell to access the folder, it shows "root:root" for each file. And we can do all operations inside the folder.

However, when we use podman run -v to access the folder, it shows "65534(nobody):65534(nobody)", any operations results in "permission denied"

Then we chmod -R a+w to the folder, user is able to write inside the container. Outside the container, we see the "513999872  513999872", which is 513998848 + 1024.

P.S. Inside the container, uid is root(0)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Ensure the dir is in local dir(not nfs) and owned by the current user.
2. Run podman unshare shell to test writing/reading
3. Run podman run -v to test writing/reading

### Describe the results you received

Podman unshare results in correct uid:gid
Podman run results in subuid+1024. Some files owned by 65534:65534 inside.

### Describe the results you expected

All files owned by root inside and the current user outside.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

podman: 4.6.1
os: rocky 9.3
arch: amd64

idMappings:
    gidmap:
    - container_id: 0
      host_id: THE_USER'S_HOST_GID
      size: 1
    - container_id: 1
      host_id: 513998848
      size: 65536
    uidmap:
    - container_id: 0
      host_id: THE_USER'S_HOST_UID
      size: 1
    - container_id: 1
      host_id: 513998848
      size: 65536
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
