### ISSUE TITLE
Issue with podman : --volumes-from

### ISSUE THREAD

**Issue by nanditararvi** [containers/podman#23643]
### Issue Description

The podman ---volumes-from isnt mounting folders from exiting image created

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a image of any repo
2. Try to mount this image using --volumes-from onto other conatiner
3. See that files arent getting mounted

![image](https://github.com/user-attachments/assets/cb8b56c1-71d2-4d48-b7c1-40039c221cd7)

### Describe the results you received

Files are missing when image volume is mounted onto the container

![image](https://github.com/user-attachments/assets/6e8f0219-6485-466b-90cc-3aa497ff5cbe)

### Describe the results you expected

At --volume-from mount; similar to docker; it should mount all files onto the container from image. Works properly in docker

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

Podman version:

version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.4
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Ubuntu 22.04 machine used

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
