### ISSUE TITLE
Failed to start pod with rootless container using --cgroup-parent

### ISSUE THREAD

**Issue by mmmmaeda** [containers/podman#23780]
### Issue Description

In Podman5.2.0-dev, if the --cgroup-parent option is used when creating a Pod, the Pod fails to start.
In Podman4.4.1, pod starts successfully with the same option.
When comparing the two versions, it appears that in Podman5.2.0-dev, the cgroup path following /sys/fs/cgroup/user.slice is not named `user`, but rather it is named after the parent slice.

--cgroup-parent=pnew.slice:
Correct(Podman4.4.1):&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/`pnew`.slice/`pnew`-libpod_pod_$POD_ID.slice
Incorrect(Podman5.2.0-dev): /sys/fs/cgroup/user.slice/`pnew`-1000.slice/user@1000.service/`pnew`.slice/`pnew`-libpod_pod_$POD_ID.slice

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create pod with the option `--cgroup-parent`.
   `podman pod create --cgroup-parent=pnew.slice my-pod`
2. Start pod.
   `podman pod start my-pod`

### Describe the results you received

$ podman pod create --cgroup-parent=pnew.slice my-pod
a4ce4d9c04d357922b461b109c1440e4bc280ed805d91e53f9e18e0ea947386a
$ podman pod start my-pod
Error: starting container 62e745dd38edf151927d4f3845620461b5901a7fc97588eb42ebe0d211e32883: unable to create pod cgroup for pod a4ce4d9c04d357922b461b109c1440e4bc280ed805d91e53f9e18e0ea947386a: creating cgroup user.slice/pnew-1000.slice/user@1000.service/pnew.slice/pnew-libpod_pod_a4ce4d9c04d357922b461b109c1440e4bc280ed805d91e53f9e18e0ea947386a.slice: Unit pnew-libpod_pod_a4ce4d9c04d357922b461b109c1440e4bc280ed805d91e53f9e18e0ea947386a.slice was already loaded or has a fragment file

### Describe the results you expected

Successfully start the Pod.

### podman info output

```yaml
$ podman version
Client:       Podman Engine
Version:      5.2.0-dev
API Version:  5.2.0-dev
Go Version:   go1.21.11 (Red Hat 1.21.11-1.el9_4)
Git Commit:   8a53e8eb677f4b10f31f69714ab0f3f964e508cd
Built:        Tue Jul 23 12:39:03 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional information

The cgroup path for rootless containers has been changed in the following:
https://github.com/containers/podman/pull/19888/commits/5121c9eb0e0f461530f9a28fbfc0c35ce197b4b2
