### ISSUE TITLE
play kube: define dependent environment variables

### ISSUE THREAD

**Issue by Poweranimal** [containers/podman#24181]
### Feature request description

Running a kubernetes manifest with `podman play kube` should expand variables, based on enviroment variables, inside an enviroment variable of a container.

E.g.:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-app
spec:
  selector:
    matchLabels:
      app: some-app
  template:
    metadata:
      labels:
        app: some-app
    spec:
      containers:
      - name: some-app
        image: docker.io/some-org/some-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DATABASE
            value: postgres
          - name: ConnectionStrings__DefaultConnection
            value: "User ID=$(POSTGRES_USER);Host=postgres;Port=$(POSTGRES_PORT);Database=$(POSTGRES_DATABASE);SearchPath=public"
```

### Suggest potential solution

Implementation of the k8s stand to define dependent enviroment variables.
https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/

### Have you considered any alternatives?

String replacement inside the container's command.
