### ISSUE TITLE
Cannot init a machine

### ISSUE THREAD

**Issue by cbclark64** [containers/podman#24581]
### Issue Description

I can't init a new machine.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install the latest Podman
2. run podman machine init
3.

### Describe the results you received

podman machine init
Looking up Podman Machine image at quay.io/podman/machine-os:5.3 to create VM
Error: pinging container registry quay.io: Get "http://quay.io/v2/": proxyconnect tcp: dial tcp 127.0.0.1:9090: connect: connection refused

### Describe the results you expected

I expected a new machine to be initialized.

### podman info output

```yaml
podman info
OS: darwin/amd64
provider: applehv
version: 5.3.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v5.3.0/libpod/_ping": dial unix /var/folders/y2/_f7rk7b14_ldbt1v6gdg_sr00000gp/T/storage-run-502/podman/podman.sock: connect: no such file or directory

macOS Sonoma v14.6 on Intel
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional information

I had installed Podman Desktop and had it install Podman.  I was able to use it but had to work on a different task for a few weeks.  When coming back to run the same commands as before (Red Hat's Migration Toolkit for Applications), I started receiving the proxy error.
i've never used a proxy on this machine.  

I manually downloaded the Podman v5.3.0 package and installed it.  I still get the proxy error.

I can reach the container registries using curl just fine...e.g.

curl -vv https://quay.io
* Host quay.io:443 was resolved.
* IPv6: (none)
* IPv4: 34.193.48.139, 44.196.219.73, 18.206.134.3, 52.72.3.19, 54.91.115.61, 44.206.139.207
*   Trying 34.193.48.139:443...
* Connected to quay.io (34.193.48.139) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.quay.io
*  start date: Dec 27 00:00:00 2023 GMT
*  expire date: Jan 24 23:59:59 2025 GMT
*  subjectAltName: host "quay.io" matched cert's "quay.io"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://quay.io/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: quay.io]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: quay.io
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 200 
< date: Fri, 15 Nov 2024 22:55:28 GMT
< content-type: text/html; charset=utf-8
< content-length: 77706
< server: nginx/1.22.1
< x-frame-options: DENY
< cache-control: no-cache, no-store, must-revalidate
< vary: Cookie
< set-cookie: _csrf_token=eyJfY3NyZl90b2tlbiI6IlZSNWx2Tmx1b3NYUHBuNlo2aGkxOHNjTDVzcU1FbjkwenZpMUc4Y3V5Vk53eERHc0c1WkQ2eWFiVjFSRTJNZkEifQ.ZzfRYA.px4u90wkHl_b0MCFJKsX_XowGiQ; Secure; HttpOnly; Path=/; SameSite=Lax
< x-frame-options: DENY
< strict-transport-security: max-age=63072000; preload
< 
<!DOCTYPE html>
blah blah blah
