### ISSUE TITLE
macOS: Custom DNS resolvers in `/etc/resolver` not working in podman 5.3.1

### ISSUE THREAD

**Issue by Stehsegler** [containers/podman#24669]
### Issue Description

In my environment, I have to use an private DNS server for private domains in addition to the default public/internet DNS. I set this up on macOS by defining a custom resolver for the relevant domains in `/etc/resolver`. After updating podman to version 5.3.1 on the macOS host, private domains can no longer be resolved from within containers (or the Podman machine, for that matter). Downgrading to 5.3.0 on the host fixes the issue, no matter what podman version is running within the machine.

### Steps to reproduce the issue

Steps to reproduce the issue
1. On macOS, create a custom DNS resolver in `/etc/resolver` pointing to a DNS server which is able to resolve domains your system's default DNS server cannot resolve.
2. Install podman 5.3.1, initialize a machine and start a container.
3. Within the container, try to resolve a domain from your custom DNS server.

### Describe the results you received

Domain cannot be resolved.

### Describe the results you expected

Domain can be resolved, as was the case with podman <= 5.3.0.

### podman info output

```yaml
`podman info` seems to collect information only from the podman instance within the machine, while the issue seems to be caused by the podman components on the macOS host. Therefore, I'll limit myself to some details of the host environment:

- OS: macOS 15.1.1 Sequoia
- Architecture: ARM64/Apple M3 Max
- Podman version: 5.3.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes
