### ISSUE TITLE
podman machine can't start

### ISSUE THREAD

**Issue by csemaan1A** [containers/podman#24807]
### Issue Description

Hello,

I'm not able to run podman machine in my local.

I added below the steps to reproduce and the error I'm facing.

Would you please check it, and tell me whether I'm missing anything in my setup?
Thank you in advance,
Christian Semaan

### Steps to reproduce the issue

First I'm stoping and removing my podman machine 
podman machine list
podman machine stop podman-machine-default
podman machine rm podman-machine-default --force

then, I'm updating wsl
wsl --list
wsl --unregister podman-net-usermode
echo "Checking for wsl updates"
wsl --shutdown
wsl --update

then, I'm initiating a new podman machine
podman machine init podman-machine-default --rootful --user-mode-networking --memory 4048 --cpus 4 --disk-size 100

then I run it
podman machine start podman-machine-default

### Describe the results you received

podman machine start podman-machine-default
Starting machine "podman-machine-default"
Starting user-mode networking...
cp: cannot stat '/mnt/wsl/resolv.conf': No such file or directory
Error: error setting up user-mode networking: command C:\Users\csemaan\AppData\Local\Microsoft\WindowsApps\wsl.exe [-u root -d podman-net-usermode bash] failed: exit status 1

### Describe the results you expected

podman machine started

### podman info output

```yaml
windows 10
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.19045.5131
podman version 5.3.1
podman desktop 1.14.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
