### ISSUE TITLE
Problem installing podman from source: sudo make install fails

### ISSUE THREAD

**Issue by flowejam** [containers/podman#24913]
### Issue Description

I was following the instructions [here](https://podman.io/docs/installation#building-from-source), as per the podman contributors guide. It causes a bit of unnecessary friction for newcomers that would be worth fixing I think. A similar issue was encountered previously: https://github.com/containers/podman/issues/19755 . In my case, the build worked, but installing with this command failed: 
`sudo make install PREFIX=/usr`

I'm willing to submit a PR for this issue but was unsure of whether editing the docs or the Makefile would be preferred.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run `sudo go env GOOS` without having /usr/local/go/bin added to secure_path

### Describe the results you received

The issue in the Makefile is with these two lines: 
```
GO ?= go                                                                        
NATIVE_GOOS := $(shell env -u GOOS $(GO) env GOOS)
```
so this error is encountered:
Required variable NATIVE_GOOS value is undefined, whitespace, or empty.  Stop.`

### Describe the results you expected

A successful installation from source after following the instructions [here](https://podman.io/docs/installation#building-from-source) and running `sudo make install PREFIX=/usr`. 

### podman info output

```yaml


OS: Ubuntu 22.04.5 LTS
Client:       Podman Engine
Version:      5.4.0-dev
API Version:  5.4.0-dev
Go Version:   go1.23.4
Git Commit:   d3cd5098f0abb54279ce4abe594d309e2bc027b0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

virt-manager
