### ISSUE TITLE
Podman Persistently Segfaults After Failed Layer

### ISSUE THREAD

**Issue by AngleSideAngle** [containers/podman#24941]
### Issue Description

Hello!
While installing a rather large number of packages in a container image (running `podman build`), podman ran out of storage to install new layers into. This led to the command crashing with an error, as expected. However, any subsequent attempts to use podman, including running `podman system prune` and `podman info`, attempt to remove the incomplete layer before segfaulting. I attached the output of `podman info`, including the full segfault.

### Steps to reproduce the issue

It's difficult for me to reproduce this issue because I cannot use podman on my computer. However, here is what created the issue:
1. Build large layer, run out of storage in the root partition
2. Run any podman command, aside from `podman version`

### Describe the results you received

When running most podman commands, the output is as follows:
```bash
WARN[0000] Found incomplete layer "ebc5d36be1c5500749813af50ec87b0a4d4549a39f6b89be767e1bb5ceaba462", deleting it 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x55f9d9799217]
```
followed by the full segfault, which is attached as a [file](https://github.com/user-attachments/files/18313349/out.txt)

### Describe the results you expected

Podman commands shouldn't segfault, eg. `podman info` should print info, `podman run ubuntu` should run an ubuntu container, etc.

### podman info output

```yaml
- podman version 5.3.1
- fedora sericea
- x86_64
- rpm-ostree status output:
State: idle
Deployments:
● fedora:fedora/41/x86_64/sericea
                  Version: 41.20250106.0 (2025-01-06T00:54:18Z)
               BaseCommit: d1eec07d9aa1bd1d4f133df42303db96b636a288ee403d76d5d68c7fff516f27
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 133.0.3-2.fc41
          LayeredPackages: distrobox helix rsms-inter-fonts source-foundry-hack-fonts

  fedora:fedora/41/x86_64/sericea
                  Version: 41.20241230.0 (2024-12-30T00:38:03Z)
               BaseCommit: dfe723ba5e89d50552ae34a526d643013f13e6e45bb72f2f415bb7d72f7cc3ea
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 133.0.3-2.fc41
          LayeredPackages: distrobox helix rsms-inter-fonts source-foundry-hack-fonts
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

The podman command that initially ran into a storage issue was being executed as a rust `std::process::Command`, installing 20+ packages/dependencies on the image `docker.io/nixos/nix:latest`. This probably isn't relevant, though.

### Additional information

This is my first time (over several years of use) having any issues with podman, although I have experienced a similar initial error with a full root partition when using docker on WSL.
