### ISSUE TITLE
podman run  -v /dev:/dev failed

### ISSUE THREAD

**Issue by ningmingxiao** [containers/podman#25051]
### Issue Description

```
[root@iZuf63rpfknjha2yy6g8dwZ ~]# podman run  -v /dev:/dev  -it  registry.openanolis.cn/openanolis/anolisos:23.2 sh 
Error: container create failed (no logs from conmon): conmon bytes "": readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
[root@iZuf63rpfknjha2yy6g8dwZ ~]# podman version
Client:       Podman Engine
Version:      4.9.4-rhel
API Version:  4.9.4-rhel
Go Version:   go1.21.13 (Red Hat 1.21.13-3.0.1.module+an8.9.0+11260+a43a3bbe)
Built:        Wed Nov 27 14:11:18 2024
OS/Arch:      linux/amd64
[root@iZuf63rpfknjha2yy6g8dwZ ~]# 
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman run  -v /dev:/dev  -it  registry.openanolis.cn/openanolis/anolisos:23.2 sh

### Describe the results you received

failed to create container

### Describe the results you expected

create successfuly

### podman info output

```yaml
[root@iZuf63rpfknjha2yy6g8dwZ ~]# podman version
Client:       Podman Engine
Version:      4.9.4-rhel
API Version:  4.9.4-rhel
Go Version:   go1.21.13 (Red Hat 1.21.13-3.0.1.module+an8.9.0+11260+a43a3bbe)
Built:        Wed Nov 27 14:11:18 2024
OS/Arch:      linux/amd64
[root@iZuf63rpfknjha2yy6g8dwZ ~]#
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
