### ISSUE TITLE
podman compose : incorrect label com.docker.compose.network

### ISSUE THREAD

**Issue by az-z** [containers/podman#25114]
### Issue Description

Hello,

I'm facing the following error:
**network az_vault_default was found but has incorrect label com.docker.compose.network set to "" (expected: "default")**

### Steps to reproduce the issue

Steps to reproduce the issue
use the following yml:
```
services:
  service1:
    image: nginx
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/ping"]
      interval: 2s
      timeout: 60s
      retries: 20
  service2:
    image: nginx
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      service1:
        condition: service_healthy
```
2. execute : 
```
podman compose -f 1.yml up service2
>>>> Executing external compose provider "/usr/libexec/docker/cli-plugins/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

network az_vault_default was found but has incorrect label com.docker.compose.network set to "" (expected: "default")
Error: executing /usr/libexec/docker/cli-plugins/docker-compose -f 1.yml up service2: exit status 1
```

or
```
podman compose -f 1.yml up 
>>>> Executing external compose provider "/usr/libexec/docker/cli-plugins/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

network az_vault_default was found but has incorrect label com.docker.compose.network set to "" (expected: "default")
Error: executing /usr/libexec/docker/cli-plugins/docker-compose -f 1.yml up: exit status 1
```

3. Additional information:
note the difference in "config" between "podman compose" and podman-compose":
```
 podman-compose -f 1.yml config
services:
  service1:
    environment:
      PORT: '3000'
    healthcheck:
      interval: 2s
      retries: 20
      test:
      - CMD
      - curl
      - -f
      - http://localhost:3004/ping
      timeout: 60s
    image: nginx
    ports:
    - 3000:3000
  service2:
    depends_on:
      service1:
        condition: service_healthy
    environment:
      PORT: '3001'
    image: nginx
    ports:
    - 3001:3001

```

and

```
podman compose -f 1.yml config
>>>> Executing external compose provider "/usr/libexec/docker/cli-plugins/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

name: az_vault
services:
  service1:
    environment:
      PORT: "3000"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3004/ping
      timeout: 1m0s
      interval: 2s
      retries: 20
    image: nginx
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
  service2:
    depends_on:
      service1:
        condition: service_healthy
        required: true
    environment:
      PORT: "3001"
    image: nginx
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3001
        published: "3001"
        protocol: tcp
**networks:
  default:
    name: az_vault_default**
```

### Describe the results you received

Describe the results you received
**network az_vault_default was found but has incorrect label com.docker.compose.network set to "" (expected: "default")**

Containers fail to start.

### Describe the results you expected

I expect : 
1. service1 to start
2. service 2 not to start due to a health check failing on service1.

### podman info output

```yaml
podman -v
podman version 5.3.1

podman-compose -v
podman-compose version 1.2.0
podman version 5.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Environment configuration:
```
cat /etc/redhat-release
Fedora release 40 (Forty)

ls -l ~/.config/systemd/user/
total 4
drwxr-xr-x 2 az az 4096 Apr 12  2024 sockets.target.wants
[az@dell5000 az_vault]$ ls -l ~/.config/systemd/user/sockets.target.wants/
total 0
lrwxrwxrwx 1 az az 35 Apr 12  2024 podman.socket -> /usr/lib/systemd/user/podman.socket
[az@dell5000 az_vault]$ ls -al $XDG_RUNTIME_DIR/podman/podman.sock
srw-rw---- 1 az az 0 Jan 21 09:20 /run/user/1000/podman/podman.sock
[az@dell5000 az_vault]$ curl -H "Content-Type: application/json" --unix-socket /var/run/user/$UID/podman/podman.sock http://localhost/_ping
OK
```

### Additional information

podman 5.3.2 (latest) was released 2 days ago. Fedora 40 doesn't have it available yet.
