### ISSUE TITLE
Trying to run Podman machine to use with Azure devops build agent - Failed to configure network (networkingMode Nat), falling back to VirtioProxy

### ISSUE THREAD

**Issue by nddipiazza** [containers/podman#25283]
### Discussed in https://github.com/containers/podman/discussions/25279

<div type='discussions-op-text'>

<sup>Originally posted by **nddipiazza** February 10, 2025</sup>
I have a local On-Prem Azure Devops instance with Windows build agents

I'd like to utilize Podman from these Windows build agents so that I can utilize Podman inside my Azure Devops pipelines.

I am running a podman machine like so:

podman machine info
```
host:
    arch: amd64
    currentmachine: podman-machine-default
    defaultmachine: podman-machine-default
    eventsdir: C:\Users\MyServiceAccountHere\.local\share\containers\podman\podman
    machineconfigdir: C:\Users\MyServiceAccountHere\.config\containers\podman\machine\wsl
    machineimagedir: C:\Users\MyServiceAccountHere\.local\share\containers\podman\machine\wsl
    machinestate: Stopped
    numberofmachines: 1
    os: windows
    vmtype: wsl
version:
    apiversion: 5.3.1
    version: 5.3.1
    goversion: go1.23.3
    gitcommit: 4cbdfde5d862dcdbe450c0f1d76ad75360f67a3c
    builttime: Thu Nov 21 09:45:23 2024
    built: 1732203923
    osarch: windows/amd64
    os: windows
```

Here are the Podman commands I'm doing:
```
podman machine init --user-mode-networking 
podman machine start
podman pull quay.io/podman/hello
```

Result:

```
Starting machine "podman-machine-default"
Starting user-mode networking...
wsl: Failed to configure network (networkingMode Nat), falling back to networkingMode VirtioProxy.

your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

	podman machine set --rootful

API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully

Trying to pull quay.io/podman/hello:latest...
Error: initializing source docker://quay.io/podman/hello:latest: pinging container registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io: Temporary failure in name resolution
##[error]PowerShell exited with code '1'.
```

I am not able to query quay.io from my podman container.

Note that the `MyServiceAccountHere` user that is running the process is not an actually logged in user. They are a service account that runs the Azure Devops agent service process.

How do I allow this Pipeline-like access to work?</div>
