### ISSUE TITLE
"Podman Compose Setup" fails. No asset found for windows and x86_64

### ISSUE THREAD

**Issue by Axeltherabbit** [containers/podman#25353]
### Issue Description

The compose setup fails on windows
```
Error: No asset found for windows and x86_64
E @ Onboarding.svelte:221
k @ Onboarding.svelte:204
await in k
y @ Onboarding.svelte:160
M @ Onboarding.svelte:267
await in M
I @ Onboarding.svelte:256
Zr @ misc.js:39
(anonymous) @ Button.svelte:76
(anonymous) @ events.js:66
fm @ shared.js:44
a @ events.js:65
```

![Image](https://github.com/user-attachments/assets/113ee898-6898-4eec-a8ba-1613d81c36d0)

### Steps to reproduce the issue

Try setting up compose

### Describe the results you received

"Failed Downloading Compose" 

### Describe the results you expected

Compose is installed

### podman info output

```yaml
PS Z:\> podman version                                                                                                  Client:       Podman Engine                                                                                             Version:      5.3.2
API Version:  5.3.2
Go Version:   go1.23.5
Git Commit:   85043bb1a3818102194afa82845cb63841067c9c
Built:        Wed Jan 22 13:42:46 2025
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      5.3.1
API Version:  5.3.1
Go Version:   go1.22.7
Built:        Thu Nov 21 00:00:00 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes
