### ISSUE TITLE
Support stopsignal in kube files

### ISSUE THREAD

**Issue by saolof** [containers/podman#25389]
### Feature request description

The kubernetes API is getting a field for stop signals added for version 1.33 set to be released in April. This means that the --stop-signal flag can be supported in Kube pod definitions, currently it can only be specified in the CLI or in quadlets.

https://github.com/kubernetes/enhancements/issues/4960

### Suggest potential solution

Being able to pass a stop signal for containers in the same way as in the Kubernetes API, by adding the field in the Lifecycle field of Container.

```yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    lifecycle:
      stopSignal: SIGUSR1
```
