### ISSUE TITLE
Text output flickers a lot when using podman pull

### ISSUE THREAD

**Issue by ponychicken** [containers/podman#25426]
### Issue Description

https://github.com/user-attachments/assets/5e239ccc-37d2-4427-84db-981f25d82a6f

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run podman pull

### Describe the results you received

Output flickers massively

### Describe the results you expected

Nice download bars like docker

### podman info output

```yaml
Client:       Podman Engine
Version:      5.3.1
API Version:  5.3.1
Go Version:   go1.23.3
Built:        Thu Nov 21 01:00:00 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
