### ISSUE TITLE
Podman logo on Mac installer does not render well

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#25475]
### Issue Description

The Podman logo on the Mac OS installer does not render well (see attached screenshot).

![Image](https://github.com/user-attachments/assets/f4d5ff30-e4fb-4494-8ca5-c6d786a38517)

### Steps to reproduce the issue

Install Podman on Mac OS.

### Describe the results you received

The logo does not render correctly making the installer look less appealing.

### Describe the results you expected

The logo should render correctly.

### podman info output

```yaml
OS: darwin/arm64
buildOrigin: pkginstaller
provider: applehv
version: 5.4.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes
