### ISSUE TITLE
subnet in podman_network as list

### ISSUE THREAD

**Issue by rkozlo** [containers/podman#25633]
### Feature request description

According to documentation and code subnet in podman_network is a string. Podman itself allows to pass subnet multiple times so it should be list of cidrs
`subnet=dict(type='str', required=False),`

```
  subnet:
    description:
      - Subnet in CIDR format
    type: str
```

### Have you considered any alternatives?

Alternative is to create multiple networks

### Additional context

I am testing case with ipvlan with l3
