### ISSUE TITLE
podman search does not sanitize the --format input

### ISSUE THREAD

**Issue by justin-octo** [containers/podman#26055]
### Issue Description

When declaring an input, `podman search --format bob` does not properly deal with the input for the `--format` flag.  The command will output:
```
$ podman search registry --format bob
bob
bob
bob
bob
bob
...
```

This should produce an error showing the allowed formatting options.  Anything other than the allowed options should result in an error message.

I have not explored any vulnerabilities that may exist.

### Steps to reproduce the issue

Steps to reproduce the issue
1.  Run `podman search whatever --format anything_other_than_allowed_options

### Describe the results you received

Podman returns:

```
anything_other_than_allowed_options
anything_other_than_allowed_options
anything_other_than_allowed_options
anything_other_than_allowed_options
anything_other_than_allowed_options
anything_other_than_allowed_options
anything_other_than_allowed_options
...
```

### Describe the results you expected

Podman returns an error listing the possible format options.

### podman info output

```yaml
Client:
  APIVersion: 5.4.0
  BuildOrigin: pkginstaller
  Built: 1739297158
  BuiltTime: Tue Feb 11 10:05:58 2025
  GitCommit: f9f7d48b24b1ca4403f189caaeab1cb8ff4a9aa2
  GoVersion: go1.23.6
  Os: darwin
  OsArch: darwin/arm64
  Version: 5.4.0
...
  kernel: 6.12.9-200.fc41.aarch64
...
version:
  APIVersion: 5.4.0
  BuildOrigin: Fedora Project
  Built: 1739232000
  BuiltTime: Mon Feb 10 16:00:00 2025
  GitCommit: ""
  GoVersion: go1.23.5
  Os: linux
  OsArch: linux/arm64
  Version: 5.4.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes
