### ISSUE TITLE
docker compose run --entrypoint '' is not used to by-pass the image entrypoint

### ISSUE THREAD

**Issue by stacyharper** [containers/podman#26078]
### Issue Description

`docker compose run --entrypoint ''` is ignored when used with a Podman socket server. It is used by a Docker server.

### Steps to reproduce the issue

Steps to reproduce the issue
1. connect docker to a podman context
2. use a `docker compose run --entrypoint ''` command

### Describe the results you received

The entrypoint is still used

### Describe the results you expected

No entrypoint is used

### podman info output

```yaml
Client:
 Version:           28.1.1
 API version:       1.41 (downgraded from 1.49)
 Go version:        go1.24.2
 Git commit:        4eba3773274f9d21ba90ae5bc719c3f1e4bb07a1
 Built:             Sat Apr 19 17:22:41 2025
 OS/Arch:           linux/amd64
 Context:           podman-rootless

Server: linux/amd64/alpine-3.22.0_alpha20250108
 Podman Engine:
  Version:          5.3.2
  APIVersion:       5.3.2
  Arch:             amd64
  BuildTime:        2025-04-11T19:40:01+02:00
  Experimental:     false
  GitCommit:        
  GoVersion:        go1.24.2
  KernelVersion:    6.14.5-0-edge
  MinAPIVersion:    4.0.0
  Os:               linux
 Conmon:
  Version:          conmon version 2.1.13, commit: unknown
  Package:          conmon-2.1.13-r0
 OCI Runtime (crun):
  Version:          crun version 1.21
commit: 10269840aa07fb7e6b7e1acff6198692d8ff5c88
rundir: /run/user-1000/crun
spec: 1.0.0
+SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  Package:          crun-1.21-r0
 Engine:
  Version:          5.3.2
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.24.2
  Git commit:       
  Built:            Fri Apr 11 19:40:01 2025
  OS/Arch:          linux/amd64
  Experimental:     false

Docker Compose version v2.35.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Alpine Linux Edge

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
