### ISSUE TITLE
auth token default lookup paths - podman login man page XDG_RUNTIME_DIRECTORY seems inconsitent

### ISSUE THREAD

**Issue by baalkor** [containers/podman#26189]
### Issue Description

The website https://docs.podman.io/en/stable/markdown/podman-login.1.html as well as the man page state that, by default, it will looks for auth.json file in "XDG_RUNTIME_DIR". 

But looking ( and confirming also) it seems to look in $XDG_CONFIG_HOME instead. 

This lead to people setting their auth.json in /run/user/<id> instead of /home/<user>/.config/... As XDG_RUNTIME_DIR is not permanent, the token gets clear upon each reboot.

In few word, can you confirm storing auth.json in XDG_RUNTIME_DIR by default is intended ?  

Ref: https://specifications.freedesktop.org/basedir-spec/latest/

### Steps to reproduce the issue

man podman login

![Image](https://github.com/user-attachments/assets/6334c5da-ce53-4713-8bfc-42c94841906c)

![Image](https://github.com/user-attachments/assets/6740c0ad-1c5c-4311-8ecb-039ecd23de99)

### Describe the results you received

Poeple loosing auth.json because storing them in a temporary location instead of the "regular" XDG_CONFIG_DIR

### Describe the results you expected

Man page/website "podman login" with the correct auth token location XDG_CONFIG_DIR/.

### podman info output

```yaml
Platform : Rocky Linux 8 
Package : podman-4.9.4-20.module+el8.10.0+1948+4b5cd4a9.x86_64
Client:       Podman Engine
Version:      4.9.4-rhel
API Version:  4.9.4-rhel
Go Version:   go1.22.11 (Red Hat 1.22.11-1.module+el8.10.0+1936+ea614e46)
Built:        Wed Mar 26 17:50:46 2025
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
