### ISSUE TITLE
Configuring tzdata failed when running ubuntu container

### ISSUE THREAD

**Issue by chenzhiwei** [containers/podman#26196]
### Issue Description

I set the `tz = "local"` in containers.conf file, I am using WSL2 Ubuntu.

When I try to configure tzdata I got following error, this seems the `/etc/localtime` is mounted into containers from host.

```
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa      4. Arctic    7. Australia  10. Pacific
  2. America     5. Asia      8. Europe     11. Etc
  3. Antarctica  6. Atlantic  9. Indian     12. Legacy
Geographic area:
Use of uninitialized value $_[1] in join or string at /usr/share/perl5/Debconf/DbDriver/Stack.pm line 112.
mv: cannot move '/etc/localtime.dpkg-new' to '/etc/localtime': Device or resource busy
Use of uninitialized value $val in substitution (s///) at /usr/share/perl5/Debconf/Format/822.pm line 84, <GEN6> line 4.
Use of uninitialized value $val in concatenation (.) or string at /usr/share/perl5/Debconf/Format/822.pm line 85, <GEN6> line 4.
dpkg: error processing package tzdata (--configure):
 installed tzdata package post-installation script subprocess returned error exit status 1
```

### Steps to reproduce the issue

Steps to reproduce the issue

```
podman run -it --rm ubuntu:24.04

apt update
apt -y install tzdata
```

### Describe the results you received

configure tzdata failed

### Describe the results you expected

should no error

### podman info output

```yaml
Client:       Podman Engine
Version:      5.0.2
API Version:  5.0.2
Go Version:   go1.22.2
Git Commit:   3304dd95b8978a8346b96b7d43134990609b3b29
Built:        Sat Apr 20 17:05:23 2024
OS/Arch:      linux/amd64

Client:       Podman Engine
Version:      5.5.0
API Version:  5.5.0
Go Version:   go1.24.3
Git Commit:   0dbcb51477ee7ab8d3b47d30facf71fc38bb0c98
Built:        Sat May 24 19:17:46 2025
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No
