### ISSUE TITLE
Quadlet generator does not properly handle spaces in `Environment` value

### ISSUE THREAD

**Issue by mkfrey** [containers/podman#26259]
### Issue Description

Spaces in the value of an environment variable are not properly handled by the systemd generator for quadlets. The variable is split into a second one when a space occurs.

### Steps to reproduce the issue

Take this quadlet file as an example:

```
[Container]
ContainerName=collabora
Environment=server_name=office.mydomain.com
Environment=extra_params=--o:ssl.enable=false --o:ssl.termination=true
Image=docker.io/collabora/code
Label=io.containers.autoupdate=registry
Network=webservices
PodmanArgs=--restart on-failure
[Install]
WantedBy=default.target
```

It contains the environment variable `extra_params` with the value `--o:ssl.enable=false --o:ssl.termination=true` containing a space.

### Describe the results you received

This is the `ExecStart` of the resulting virtual .service file:

`ExecStart=/usr/bin/podman run --name collabora --cidfile=%t/%N.cid --replace --rm --cgroups=split --network webservices --sdnotify=conmon -d --env --o:ssl.termination=true --env extra_params=--o:ssl.enable=false --env server_name=office.mydomain.com --label io.containers.autoupdate=registry --restart on-failure docker.io/collabora/code`

The value is split into two separate parameters, `--env --o:ssl.termination=true` and `--env extra_params=--o:ssl.enable=false`.

### Describe the results you expected

The `ExecStart` command should contain `--env "extra_params=--o:ssl.enable=false --o:ssl.termination=true"`.

### podman info output

```yaml
Client:        Podman Engine
Version:       5.5.0
API Version:   5.5.0
Go Version:    go1.24.3
Git Commit:    0dbcb51477ee7ab8d3b47d30facf71fc38bb0c98
Built:         Wed May 14 02:00:00 2025
Build Origin:  Fedora Project
OS/Arch:       linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details
