### ISSUE TITLE
Podman complains about OpenSSL 3.4.0 on Ubuntu 25.04

### ISSUE THREAD

**Issue by XNinety9** [containers/podman#26262]
### Issue Description

Hi everyone.

I'm giving Ubuntu 25.04 a try, and it looks like podman has a hard time handling a dependency to OpenSSL 3.4.0. Whenever I try to spin my compose file, I get an error:

```
text time="2025-06-02T15:50:20+02:00" level=error msg="Rootless netns cleanup error after failed setup: 1 error occurred:\n\t* rootless netns: kill network process: permission denied\n\n"
text Error: unable to start container "abd7c8a3ca7e2631cc7d6458dd93289c2bad42632bd65c005ecd0789056c3d13": netavark: IO error: Error while applying dns entries: IO error: aardvark-dns failed to start: systemd-run: /var/tmp/_MEIUmFl59/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/x86_64-linux-gnu/systemd/libsystemd-shared-257.so)
```

Here is the compose file I use:

```
version: "3.8"

services:
  cassandra-seed:
    image: docker.io/library/cassandra:5.0.4
    container_name: cassandra-seed
    cap_add:
      - NET_ADMIN
    environment:
      CASSANDRA_CLUSTER_NAME: test-cluster
      CASSANDRA_SEEDS: cassandra-seed
      CASSANDRA_LISTEN_ADDRESS: cassandra-seed
      CASSANDRA_BROADCAST_ADDRESS: cassandra-seed
      # Trim JVM heap for a laptop; delete the next two lines if RAM is no issue
      MAX_HEAP_SIZE: 512m
      HEAP_NEWSIZE: 100M
    ports:
      - "9042:9042"            # expose CQL to your host
    volumes:
      - seed_data:/var/lib/cassandra
    # The healtcheck is mandatory in order to avoid nodes tokens collision when the cluster starts.
    # Here it's used to start nodes one after another
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m      # Time between each healthcheck
      start_period: 1m  # Time before first check
      timeout: 10s      # Healthcheck command timeout
      retries: 5        # Number of retries before the service is declares "unhealthy"

  cassandra-node-1:
    image: docker.io/library/cassandra:5.0.4
    container_name: cassandra-node-1
    cap_add:
      - NET_ADMIN
    environment:
      CASSANDRA_CLUSTER_NAME: test-cluster
      CASSANDRA_SEEDS: cassandra-seed
      CASSANDRA_LISTEN_ADDRESS: cassandra-node-1
      CASSANDRA_BROADCAST_ADDRESS: cassandra-node-1
      MAX_HEAP_SIZE: 512m
      HEAP_NEWSIZE: 100M
    ports:
      - "9043:9042"
    depends_on:
      cassandra-seed:
        condition: service_healthy
    volumes:
      - node1_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m      # Time between each healthcheck
      start_period: 1m  # Time before first check
      timeout: 10s      # Healthcheck command timeout
      retries: 5        # Number of retries before the service is declares "unhealthy"

  cassandra-node-2:
    image: docker.io/library/cassandra:5.0.4
    container_name: cassandra-node-2
    cap_add:
      - NET_ADMIN
    environment:
      CASSANDRA_CLUSTER_NAME: test-cluster
      CASSANDRA_SEEDS: cassandra-seed
      CASSANDRA_LISTEN_ADDRESS: cassandra-node-2
      CASSANDRA_BROADCAST_ADDRESS: cassandra-node-2
      MAX_HEAP_SIZE: 512m
      HEAP_NEWSIZE: 100M
    ports:
      - "9044:9042"
    depends_on:
      cassandra-node-1:
        condition: service_healthy
    volumes:
      - node2_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m      # Time between each healthcheck
      start_period: 1m  # Time before first check
      timeout: 10s      # Healthcheck command timeout
      retries: 5        # Number of retries before the service is declares "unhealthy"

  cassandra-node-3:
    image: docker.io/library/cassandra:5.0.4
    container_name: cassandra-node-3
    cap_add:
      - NET_ADMIN
    environment:
      CASSANDRA_CLUSTER_NAME: test-cluster
      CASSANDRA_SEEDS: cassandra-seed
      CASSANDRA_LISTEN_ADDRESS: cassandra-node-3
      CASSANDRA_BROADCAST_ADDRESS: cassandra-node-3
      MAX_HEAP_SIZE: 512m
      HEAP_NEWSIZE: 100M
    ports:
      - "9045:9042"
    depends_on:
      cassandra-node-2:
        condition: service_healthy
    volumes:
      - node3_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m      # Time between each healthcheck
      start_period: 1m  # Time before first check
      timeout: 10s      # Healthcheck command timeout
      retries: 5        # Number of retries before the service is declares "unhealthy"

volumes:
  seed_data:
  node1_data:
  node2_data:
  node3_data:
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create the compose file from the content above
2. podman compose up -d

### Describe the results you received

I get the following output:
```
podman compose up -d           
>>>> Executing external compose provider "/home/x99/.local/bin/podman-compose". Please see podman-compose(1) for how to disable this message. <<<<

11253640f424109071b8c71b8990d41240d99929c62030ab86a87c34b5d4f112
1a1a139e33ef30695c3baa49fc813c958ec00a99d00a28dcbde61afdf4080cfb
text time="2025-06-02T16:02:48+02:00" level=error msg="Rootless netns cleanup error after failed setup: 1 error occurred:\n\t* rootless netns: kill network process: permission denied\n\n"
text Error: unable to start container "1a1a139e33ef30695c3baa49fc813c958ec00a99d00a28dcbde61afdf4080cfb": netavark: IO error: Error while applying dns entries: IO error: aardvark-dns failed to start: systemd-run: /var/tmp/_MEIjGlaYg/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/x86_64-linux-gnu/systemd/libsystemd-shared-257.so)
67220a9a12535975e6384d75863460e346bccd928f87a3df9f024d32f20ff58a
```

Furthermore, all containers can't go past the "Created" status. 

### Describe the results you expected

All 4 container up and running. This setup worked with the repo version of podman on Ubuntu 24.04.

### podman info output

```yaml
Podman: 5.4.1
Podman compose: 1.4.0
Ubuntu: 25.04
Architecture: x86 64bits
OpenSSL version: OpenSSL 3.4.1 11 Feb 2025 (Library: OpenSSL 3.4.1 11 Feb 2025)
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
