### ISSUE TITLE
.build quadlet fails if `Pull` key included

### ISSUE THREAD

**Issue by ishanarora** [containers/podman#26327]
### Issue Description

For example if `Pull=newer` is included in .build a quadlet then the generated service file includes:
```
ExecStart=/usr/bin/podman build --pull newer --tag ...
```
The above command fails with error:
```
Error: accepts at most 1 arg(s), received 2
```

Running the command with `--pull=newer` instead of `--pull newer` (`=` instead of space) fixes the command.

A possible fix would be if the podman-systemd.unit generator used `=` instead of space for passing arguments in the podman command-line

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a .build quadlet with `Pull=newer` in `[Build]` section
2. generate the systemd unit file
3. Start the generated unit

### Describe the results you received

```
Error: accepts at most 1 arg(s), received 2
```

### Describe the results you expected

Successful build. No errors.

### podman info output

```yaml
version:
  APIVersion: 5.5.1
  Built: 1749464740
  BuiltTime: Mon Jun  9 10:25:40 2025
  GitCommit: 850db76dd78a0641eddb9ee19ee6f60d2c59bcfa
  GoVersion: go1.24.4
  Os: linux
  OsArch: linux/amd64
  Version: 5.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional information

A workaround is to use `PodmanArgs=--pull=newer` instead of `Pull=newer`
