### ISSUE TITLE
Feature Request: Add `selinuxLabel` Option in Podman Play Kube YAML

### ISSUE THREAD

**Issue by ArthurWuTW** [containers/podman#26437]
**Description**

I ran the OpenSearch container with commands:

```bash

$ cd /home/arthur/Desktop

$ mkdir data1

$ podman unshare chown 1000:1000 data1

$ podman run \
  --name opensearch \
  -p 9200:9200 \
  -p 9600:9600 \
  -e discovery.type=single-node \
  -e plugins.security.disabled=true \
  -e bootstrap.memory_lock=true \
  -e OPENSEARCH_JAVA_OPTS="-Xms512m -Xmx512m" \
  -e OPENSEARCH_INITIAL_ADMIN_PASSWORD=YourSecurePassword123! \
  -v /home/arthur/Desktop/data1:/usr/share/opensearch/data:z \
  opensearchproject/opensearch:2.13.0

```

Then, I wanted to convert this setup to a pod yaml file for `podman play kube`, but I noticed the note in the [doc](https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html)
> Note: hostPath volume types created by kube play is given an SELinux shared label (z), bind mounts are not relabeled (use chcon -t container_file_t -R <directory>).

This means that if we mount an existing host directory, we still need to manually run `chcon` on it beforehand, which may not be very intuitive for users unfamiliar with SELinux.

**Suggest potential solution**

Introduce a new `selinuxLabel` field in `volumeMounts` to represent the SELinux mount labeling behavior.

- `shared` corresponds to `:z`

- `private` corresponds to `:Z`

Example YAML

```yaml

apiVersion: v1
...
  containers:
    - name: opensearch
      image: opensearchproject/opensearch:2.13.0
      ...
      volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-data
          selinuxLabel: shared # :z   <------------------- NEW!


  volumes:
    - name: opensearch-data
      hostPath:
        path: /home/arthur/Desktop/opensearch-data
        type: Directory

```
**Question**

Would this proposal be a reasonable enhancement? if so, I'd be happy to contribute this feature.
