### ISSUE TITLE
The generated yaml file does not work the same way as if I manually created a pod

### ISSUE THREAD

**Issue by mecurc** [containers/podman#7318]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I manually create a pod then attach containers everything works. But when i try to play a generated kube file i got a permission denied errors.

1. I manually create a pod and attach containers:
``` sh
podman pod create --name=droplet -p 8080:80 -p 8443:443

podman run -d --name nginx --pod droplet \
    -v /var/pods/droplet/nginx:/etc/nginx:ro,Z \
    -v ~/.acme.sh/example.com:/etc/letsencrypt:ro,Z \
     nginx:1.19.1-alpine

podman run -d --name n8n --pod droplet \
    -v /var/pods/droplet/n8n:/root/.n8n:Z \
    -e GENERIC_TIMEZONE="Europe/Moscow" \
    -e N8N_BASIC_AUTH_ACTIVE=true \
    -e N8N_BASIC_AUTH_USER="user" \
    -e N8N_BASIC_AUTH_PASSWORD="password" \
    -e N8N_HOST="example.comi" \
    -e VUE_APP_URL_BASE_API="example.comi" \
    -e N8N_ENCRYPTION_KEY="secret-token-key" \
    -e NODE_FUNCTION_ALLOW_BUILTIN="*" \
    -e NODE_FUNCTION_ALLOW_EXTERNAL="lodash" \
    -e WEBHOOK_TUNNEL_URL="https://example.com" \
     n8nio/n8n:0.76.0
```
Everything works here.

2. So, lets generate a `droplet.yml` by `podman generate kube droplet > droplet.yml` command.
3. `podman play kube droplet.yml`

**Describe the results you received:**
My containers exited with errors codes because `permission denied` to all volumes.

**Describe the results you expected:**
Everything works like it works with just commands from step 1.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:      2.0.4
API Version:  1
Go Version:   go1.14.6
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
APIVersion: 1
Built: 0
BuiltTime: Thu Jan  1 00:00:00 1970
GitCommit: ""
GoVersion: go1.14.6
OsArch: linux/amd64
Version: 2.0.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Rootless mode.

**Comment by danopia** [comment]
Hello, to the best of my knowledge, Kubernetes does not have an equivalent for podman's `:Z` flag (which relabels the volume to match a unique-per-container selinux label). The Kubernetes selinux support is to specify [a fixed label](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#assign-selinux-labels-to-a-container) for the container, which is used for all volumes.

So it makes sense that running the pod through kube YAML lost the `:Z` volume option. A workaround would be using `:z` instead, which relabels the volume for any container -- then running the pod through kube yaml should work in the future since the host directory is already labelled correctly.

This doesn't solve your problem, just providing some insight from how Kubernetes handles selinux (which is, not well). One possibility to support Z and z flags in the kube yaml would be storing those flags in a kube annotation [similar to this](https://github.com/stardustapp/cloud-infra/blob/master/apps/linuxserver-base/statefulset.yaml#L17).

**Comment by mecurc** [comment]
Hi! Thank you for answering.

Unfortunately, I use the *.yml file with the podman cli. The documentation for `podman play kube` says: 
`Note: HostPath volume types created by play kube will be given an SELinux private label (Z)`

http://docs.podman.io/en/latest/markdown/podman-play-kube.1.html.

So I expect the generated podman file to work as if I had manually created a pod and added containers to it.

**Comment by averyfreeman** [comment]
> Hello, to the best of my knowledge, Kubernetes does not have an equivalent for podman's `:Z` flag (which relabels the volume to match a unique-per-container selinux label). The Kubernetes selinux support is to specify [a fixed label](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#assign-selinux-labels-to-a-container) for the container, which is used for all volumes.
> 
> So it makes sense that running the pod through kube YAML lost the `:Z` volume option. A workaround would be using `:z` instead, which relabels the volume for any container -- then running the pod through kube yaml should work in the future since the host directory is already labelled correctly.
> 
> This doesn't solve your problem, just providing some insight from how Kubernetes handles selinux (which is, not well). One possibility to support Z and z flags in the kube yaml would be storing those flags in a kube annotation [similar to this](https://github.com/stardustapp/cloud-infra/blob/master/apps/linuxserver-base/statefulset.yaml#L17).

I am experiencing this same problem, but my system does not have SELinux, as I am using Ubuntu 20.04.

Should I open a new bug report, or post my criteria in this same thread?

**Comment by averyfreeman** [comment]
Upon further reading, I'm seeing `podman play kube` feature is "very much under development" - are the YAML files created from `podman generate kube` only intended to be run by kubernetes?  Should I just assume that for now podman is broken in this area?

**Comment by rhatdan** [comment]
@ashley-cui @haircommander @mheon PTAL

**Comment by haircommander** [comment]
@averyfreeman can I see the kube yaml file you created?

**Comment by averyfreeman** [comment]
> @averyfreeman can I see the kube yaml file you created?

Absolutely:

The YAML file auto-generated by `podman generate kube < wptestpod.yaml`:

```
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.0.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2020-08-26T17:02:56Z'
  labels:
    app: wptestpod
  name: wptestpod
spec:
  containers:
    - command:
        - apache2-foreground
      env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TERM
          value: xterm
        - name: container
          value: podman
        - name: WORDPRESS_DB_NAME
          value: wp
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: APACHE_CONFDIR
          value: /etc/apache2
        - name: PHP_LDFLAGS
          value: -Wl,-O1 -pie
        - name: PHP_VERSION
          value: 7.4.9
        - name: PHP_EXTRA_CONFIGURE_ARGS
          value: --with-apxs2 --disable-cgi
        - name: GPG_KEYS
          value: 42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312
        - name: WORDPRESS_DB_PASSWORD
          value: t3stp4ssw0rd
        - name: APACHE_ENVVARS
          value: /etc/apache2/envvars
        - name: PHP_ASC_URL
          value: https://www.php.net/distributions/php-7.4.9.tar.xz.asc
        - name: PHP_SHA256
          value: 23733f4a608ad1bebdcecf0138ebc5fd57cf20d6e0915f98a9444c3f747dc57b
        - name: PHP_URL
          value: https://www.php.net/distributions/php-7.4.9.tar.xz
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: PHP_CPPFLAGS
          value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
        - name: PHP_MD5
        - name: PHP_EXTRA_BUILD_DEPS
          value: apache2-dev
        - name: PHP_CFLAGS
          value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
        - name: WORDPRESS_SHA1
          value: 03fe1a139b3cd987cc588ba95fab2460cba2a89e
        - name: PHPIZE_DEPS
          value: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c"
        - name: WORDPRESS_VERSION
          value: '5.5'
        - name: PHP_INI_DIR
          value: /usr/local/etc/php
        - name: HOSTNAME
          value: wptestpod
      image: docker.io/library/wordpress:latest
      name: wptestwp
      ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      workingDir: /var/www/html
    - command:
        - mysqld
      env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TERM
          value: xterm
        - name: container
          value: podman
        - name: MYSQL_PASSWORD
          value: t3stp4ssw0rd
        - name: GOSU_VERSION
          value: '1.12'
        - name: GPG_KEYS
          value: 177F4010FE56CA3336300305F1656F24C74CD1D8
        - name: MARIADB_MAJOR
          value: '10.5'
        - name: MYSQL_ROOT_PASSWORD
          value: t3stp4ssw0rd
        - name: MARIADB_VERSION
          value: 1:10.5.5+maria~focal
        - name: MYSQL_DATABASE
          value: wp
        - name: MYSQL_USER
          value: wordpress
        - name: HOSTNAME
          value: wptestpod
      image: docker.io/library/mariadb:latest
      name: wptestdb
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      workingDir: /
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}
```

The same YAML file with several removals referenced by https://www.redhat.com/sysadmin/compose-podman-pods  :

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2020-08-26T17:02:56Z'
  labels:
    app: wptestpod
  name: wptestpod
spec:
  containers:
    - name: wptest-web
      env:
        - name: WORDPRESS_DB_NAME
          value: wp
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: testpassword
      image: docker.io/library/wordpress:latest
      ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      workingDir: /var/www/html
    - name: wptest-db
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: testpassword
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: testpassword
        - name: MYSQL_DATABASE
          value: wp
      image: docker.io/library/mariadb:latest
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      workingDir: /
status: {}
```

Both produce same result (pod cannot be accessed, `403 error forbidden`) but were created from a working pod created by commands 

(again, I tested this twice on two similar systems, free of any pods or images at start, both for testing YAML and commands):

```
podman create --name wptestpod -p 8080:80

podman run \
-d --restart=always --pod=wptestpod2 \
-e MYSQL_ROOT_PASSWORD="myrootpass" \
-e MYSQL_DATABASE="wp" \
-e MYSQL_USER="wordpress" \
-e MYSQL_PASSWORD="w0rdpr3ss" \
--name=wptest-db mariadb


podman run \
-d --restart=always --pod=wptestpod2 \
-e WORDPRESS_DB_NAME="wp" \
-e WORDPRESS_DB_USER="wordpress" \
-e WORDPRESS_DB_PASSWORD="w0rdpr3ss" \
-e WORDPRESS_DB_HOST="127.0.0.1" \
--name wptest-web wordpress
```  

Hope you can make use of this info. Thanks for your help!
