### ISSUE TITLE
Feature: support uidmap with `podman play kube`

### ISSUE THREAD

**Issue by akvadrako** [containers/podman#7504]
/kind feature

I would like to use pod.yaml as a rootless alternative to docker-compose. In a pod I'm working on, some containers expect to run as root and some expect to run as a non-root user. I would like all of them to map to my current user in the host's namespace.

For this I need some way to pass the **uidmap** option using a pod.yaml file. Something like:

```
spec:
  containers:
  - name: as1000
    securityContext:
      UIDMap: 300:0:1
      GIDMap: 300:0:1
```

Related: https://github.com/moby/moby/issues/28593 https://github.com/kubernetes/enhancements/issues/127 https://github.com/containers/podman/issues/6123

**Comment by rhatdan** [comment]
Is this syntax valid for Kubernetes?

**Comment by rhatdan** [comment]
@haircommander @giuseppe WDYT?

**Comment by haircommander** [comment]
hey @Akasurde upstream still seems to be figuring out how the support for usernamespaces will land. right now, it's added as an annotation, and only processed by the cri implementation. I would rather not handle this until there is clarity with the upstream on what the approach will be

**Comment by Akasurde** [comment]
@haircommander I think you meant @akvadrako

**Comment by haircommander** [comment]
oops, sorry for the noise, yes I did mean @akvadrako

**Comment by haircommander** [comment]
@akvadrako does the https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#securitycontext-v1-core `runAsUser` field fit your needs? I'm not sure we support it right now, but if you need a container to run as a certain user on the host, I do not think you need usernamespaces for that

**Comment by akvadrako** [comment]
`runAsUser` is supported, but it's not enough. For example, given this pod:
```yaml
apiVersion: v1
kind: Pod
metadata: { name: demo }
spec:
  containers:
  - name: as1000
    image: docker.io/alpine
    command: [ "sh", "-c", "touch /tmp/abc-1000" ]
    securityContext:
      runAsUser: 1000
    volumeMounts:
    - { mountPath: /tmp, name: tmp }
  - name: asroot
    image: docker.io/alpine
    command: [ "sh", "-c", "touch /tmp/abc-root" ]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - { mountPath: /tmp, name: tmp }
  volumes:
  - name: tmp
    hostPath: { path: /tmp }
```
one finds that:
- /tmp/abc-root is owned by my current user
- /tmp/abc-1000 is owned by 100999 (due to my /etc/subuid file)
but I want that both files are owned by my current user.
