### ISSUE TITLE
readonly mount is not supported in kubernetes yaml

### ISSUE THREAD

**Issue by x70b1** [containers/podman#7550]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

At the moment a setting like `readonly: true` is ignored for a mount in a kubernetes yaml.
I found out that it seems to be supported for a cli run: https://github.com/containers/podman/pull/6380 

**Steps to reproduce the issue:**

```
spec:
  hostname: dns
  restartPolicy: always
  containers:
    - image: ...
      name: ...
      volumeMounts:
        - name: dnsovertls-config
          mountPath: /etc/unbound/unbound.conf
          readonly: true                                              <------------------------------

  volumes:
    - name: dnsovertls-config
      hostPath:
        path: /srv/podman/dns/dnsovertls/config/unbound.conf
        type: File
```

**Describe the results you received:**

The container is still able to write in a file.

**Describe the results you expected:**

The container should not be able to change a file on the host.

**Output of `podman version`:**

```
podman version 2.0.6
```
