### ISSUE TITLE
REST API docker-compat, gitlab-runner

### ISSUE THREAD

**Issue by psgreco** [containers/podman#7693]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

gitlab-runner fails to run tasks using the docker compatible API

**Steps to reproduce the issue:**

1. install gitlab-runner for your distro

2. register gitlab-runner so it can run the jobs (gitlab-runner register -n -u "https://gitlab.com/" -r "<project key>" --name "builderpodman" --executor "docker" --docker-image "<base image>" --tag-list "podmanrunner" --run-untagged=false)

3. Create a job for the job in gl (in my case I created one for docker and one for podman, to compare)
```yml
stages:
  - build

.build:containertest:
  stage: build
  before_script:
    - echo "${EXECUTOR} running before script"
  script:
    - echo "${EXECUTOR} running script"

build:docker:
  extends: .build:containertest
  tags:
    - dockerrunner
  variables:
    EXECUTOR: "docker"
    CI_DEBUG_TRACE: "true"

build:podman:
  extends: .build:containertest
  tags:
    - podmanrunner
  variables:
    EXECUTOR: "podman"
    CI_DEBUG_TRACE: "true"
```

**Describe the results you received:**
```Running with gitlab-runner 13.3.1 (738bbe5a)
  on builderpodman ZAq3tJzX
Preparing the "docker" executor
00:39
Using Docker executor with image arm64v8/centos:8 ...
Pulling docker image gitlab/gitlab-runner-helper:arm64-738bbe5a ...
Using docker image sha256:98583b9e0b760274a726eb36f90a47e5bf4ac0750fa7fad8b907b994a7e98479 for gitlab/gitlab-runner-helper:arm64-738bbe5a ...
Pulling docker image arm64v8/centos:8 ...
Using docker image sha256:9d5bccb1776bd298334234395ecd1e33ec7050e8ee3fc821daed7c484588b17b for arm64v8/centos:8 ...
Preparing environment
Getting source from Git repository
Executing "step_script" stage of the job script
Job succeeded
```
Job succeeds but nothing is actually being executed https://gitlab.com/psgreco/podman_tests/-/jobs/745351978

**Describe the results you expected:**
```
Running with gitlab-runner 13.2.2 (a998cacd)
  on builderdocker 5JcQ-XCB
Preparing the "docker" executor
00:06
Using Docker executor with image arm64v8/centos:8 ...
Pulling docker image arm64v8/centos:8 ...
Using docker image sha256:9d5bccb1776bd298334234395ecd1e33ec7050e8ee3fc821daed7c484588b17b for arm64v8/centos:8 ...
Preparing environment
Running on runner-5jcq-xcb-project-21214845-concurrent-0 via c7-docker-runner...
Getting source from Git repository
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/psgreco/podman_tests/.git/
Created fresh repository.
Checking out e1797bc6 as tests...
Skipping Git submodules setup
Executing "step_script" stage of the job script
$ echo "${EXECUTOR} running before script"
docker running before script
$ echo "${EXECUTOR} running script"
docker running script
Job succeeded
``` 
Job is normally executed (example from docker) https://gitlab.com/psgreco/podman_tests/-/jobs/745321893

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:      2.1.0-rc1
API Version:  1
Go Version:   go1.14.7
Built:        Mon Sep 14 17:22:18 2020
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**
[podman_system_service.txt](https://github.com/containers/podman/files/5246295/podman_system_service.txt)
[gitlab_runner_job1.txt](https://github.com/containers/podman/files/5246341/gitlab_runner_job1.txt)

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-2.1.0-0.2.rc1.fc32.aarch64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on ARM64
Logs may not belong to the same execution, since tests were ran several times
