### ISSUE TITLE
How to connect to pod started from deployment definition

### ISSUE THREAD

**Issue by bluebrown** [containers/podman#7738]
/kind Question

Hi,

I am trying out the new feature of running a deployment definition. Before when I was using a created pod, I could assign an IP address to this pod. `podman pod create --name my-pod -p 8080:80`. 

The pods from the deployment file don't seem to expose a port and I can't find any documentation on this. 
In Kubernetes, it looks like it is usually paired with a top level service definition that exposes the port. [See here](https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/).

I am trying something like this but it doesn't work. I can't access the container.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - port: 8080
        - targetPort: 8080
        - containerPort: 80
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
````
These are the running containers.

```shell
CONTAINER ID  IMAGE                 COMMAND               CREATED         STATUS             PORTS   NAMES
0551ed5f7ce0  tomcat                catalina.sh run       20 seconds ago  Up 19 seconds ago          nginx-deployment-pod-0-tomcat
677383fe7b7f  k8s.gcr.io/pause:3.2                        20 seconds ago  Up 20 seconds ago          319739a24dbe-infra
6eb7b7cfa335  nginx                 /docker-entrypoin...  20 seconds ago  Up 19 seconds ago          nginx-deployment-pod-0-nginx
```

**Comment by zhangguanzhang** [comment]
could you paste the output of `podman version`?

**Comment by zhangguanzhang** [comment]
you could use the hostPort
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - port: 8080
        - hostPort: 81
        - targetPort: 8080
        - containerPort: 80
```
