### ISSUE TITLE
generate kube should use tag

### ISSUE THREAD

**Issue by langdon** [containers/podman#7838]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When you use `podman generate kube` you expect to be able to run the result immediately. However, possibly depending on how you created the pod, you generate a yaml file that uses `:latest` for the tag. If you turn around and try to `play kube` that file, it fails trying to pull container images that the user has because it can't pull something with a `:latest` tag. `generate kube` should create yaml that is immediately runnable. To top it off, there is no indication of the issue being the tag unless you search and find #5186

**Steps to reproduce the issue:**

1. manually create containers in a pod called my-pod
1. podman generate kube my-pod > my-pod.yaml
1. podman pod rm -f my-pod
1. podman play kube my-pod.yaml

**Describe the results you received:**

```
Trying to pull registry.access.redhat.com/simpler-tools:latest...
  name unknown: Repo not found
</snip>
```

**Describe the results you expected:**
```
Pod: <UUID>
Containers: 
<UUID>
<UUID>
```
**Additional information you deem important (e.g. issue happens only occasionally):**

To make matters a bit more annoying, it does, in fact, create the pod with no UUID in the output or any indication it did so. Which, in order to do further testing/debugging, you have to manually remove. 

**Output of `podman version`:**

```
F32: 2.0.6
RHEL8: 1.9.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.6-1.fc32.x86_64
podman-1.9.3-2.module+el8.2.1+6867+366c07d6.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by umohnani8** [comment]
Tried this with podman master and it works fine for me. I created a pod with a fedora container running in it and was able to `podman play kube <yaml-file>`
```
podman play kube mypod.yaml
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob 22cef3226003 [--------------------------------------] 0.0b / 0.0b
Copying config e6b57c0d9f done  
Writing manifest to image destination
Storing signatures
Pod:
9e6ceeada01e996cd2cd28ec782e1ba3b6f31f0c4c71ea3e1138b182fd9cff2b
Container:
c41014d9cacf072abc42f63657bffb9d69ea34c7cc5a2fd204887f60b2a054f0

podman pod ps
POD ID        NAME    STATUS   CREATED        INFRA ID      # OF CONTAINERS
9e6ceeada01e  mypod   Running  5 minutes ago  696d1aca49a5  2
podman ps
CONTAINER ID  IMAGE                                     COMMAND     CREATED        STATUS            PORTS   NAMES
c41014d9cacf  registry.fedoraproject.org/fedora:latest  sleep 1000  5 minutes ago  Up 5 minutes ago          mypod-myctr
696d1aca49a5  k8s.gcr.io/pause:3.2
```

Snippet of the pod yaml file generated shows the image has the `:latest` tag.
```
spec:
  containers:
  - command:
    - sleep
    - "1000"
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: oci
    - name: DISTTAG
      value: f32container
    - name: FGC
      value: f32
    - name: HOSTNAME
      value: mypod
    image: registry.fedoraproject.org/fedora:latest
    name: myctr
```

@langdon is there a specific image you were using that for some reason was not being pulled? I will try out the podman version you stated in your description as well.
