### ISSUE TITLE
Podman with Kubernetes executor in Gitlab CI

### ISSUE THREAD

**Issue by tvvignesh** [containers/podman#7982]
Hi. I am trying to run Podman in Gitlab CI using the Kubernetes executor (GKE with containerd specifically) (https://docs.gitlab.com/runner/executors/kubernetes.html) and am struggling to build the image. Details below.

**My Sample Dockerfile:**
```Dockerfile
FROM node:10-alpine

RUN node -v
```

**My Sample CI:**
```yml
image: "quay.io/podman/stable"

buildah:
  tags:
    - tag1
    - tag2
  variables:
    STORAGE_DRIVER: "vfs"
    IMAGE_TAG: $CI_REGISTRY_IMAGE:edge
  script:
    - whoami
    - podman version
    - echo "Logging into $CI_REGISTRY"
    - podman login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - podman build --security-opt seccomp=unconfined --security-opt label=disabled --runtime-flag debug -t ${IMAGE_TAG} .
    - podman images
    - podman push ${IMAGE_TAG}
    - podman logout $CI_REGISTRY
```

While I wanted to go with the restricted PSP (https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml) I thought I should get it running first, so I have given all permissions to the PSP exactly using this PSP and have no securityContext in the POD as well: https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/privileged-psp.yaml

**Case 1: All permissions given, and replacing vfs with overlayfs driver**
<img width="458" alt="1" src="https://user-images.githubusercontent.com/1165845/95622624-7e463c80-0a91-11eb-9838-00b6ed2415b4.png">

When trying to use overlayfs I did add mount settings like this to gitlab runner but it didn't help:
```
[[runners.kubernetes.volumes.host_path]]
      name = "buildah"
      mount_path = "/var/lib/containers/"
      read_only = false
```

**Case 2: All permissions given, vfs driver**
<img width="426" alt="2" src="https://user-images.githubusercontent.com/1165845/95622785-d0875d80-0a91-11eb-9f2f-2bc49d046141.PNG">

I am stuck with this error. I did see in this blog: https://blog.42.be/2018/10/buildah-inside-centos-container.html that they are facing the same error and they fixed it by enabling user namespace.

So, I tried adding the `--userns` flag and set its value to both `host` and `container` and it did not work.

I saw a similar issue https://github.com/containers/podman/issues/3402 using Go and I am facing the same issue with Node running Podman as root.

Also saw somewhat similar issue here with arm (I am using amd64) but not sure if its related: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4246

**Case 3: Trying out security-opt**
I did add the security-opt flag as per this comment: https://github.com/containers/buildah/issues/2175#issuecomment-639382961 but that didn't work either and I get the same error as above.

Also tried adding `--security-opt seccomp=/usr/share/containers/seccomp.json` but that didn't seem to work either.

`podman build --security-opt seccomp=unconfined -t ${IMAGE_TAG} .`

<img width="423" alt="3" src="https://user-images.githubusercontent.com/1165845/95624220-23621480-0a94-11eb-8234-77f7f2de1340.PNG">

**Case 4: Trying to set the storage driver to fuse**
I did try changing storage driver to fuse by setting `STORAGE_DRIVER: "fuse"` but it didn't work since it said fuse is not supported. 

Tried both `fuse` and `/dev/fuse`

<img width="431" alt="4" src="https://user-images.githubusercontent.com/1165845/95624302-47255a80-0a94-11eb-96d3-ccf674d9acf0.PNG">

Is there any way or guide/recommendation to run Podman in Kubernetes executor providing minimum privilege as possible to build images? Currently I am stuck with Case 2 above. 

Since I don't have any docker here (everything is running within Containerd since it is using the Kubernetes executor), I don't think that is the problem? I am using the `quay.io/podman/stable` image as well. 

Also referred to https://medium.com/prgcont/using-buildah-in-gitlab-ci-9b529af19e42 but that didn't help due to the errors above.

Any help is appreciated. Thanks.
