### ISSUE TITLE
Add the --generate-timestamp option to podman generate systemd

### ISSUE THREAD

**Issue by idelsink** [containers/podman#8880]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Add an option like `--generate-timestamp false` when generating a podman systemd unit file using the `podman generate systemd` command as seen in https://github.com/containers/podman/blob/master/pkg/systemd/generate/pods.go#L208

The default could still be set to true, but it will allow me to change this behaviour.

**Describe the results you expected:**
When running a command like `podman generate systemd --generate-timestamp false --name foobar` I expect the output to be somewhat like:

```
# container-foobar.service
# Mon Jan  4 23:32:51 CET 2021

[Unit]
Description=Podman container-foobar.service
Documentation=man:podman-generate-systemd(1)
Wants=network.target
After=network-online.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
ExecStart=/usr/bin/podman start foobar
ExecStop=/usr/bin/podman stop -t 10 foobar
ExecStopPost=/usr/bin/podman stop -t 10 foobar
PIDFile=/run/user/1000/containers/overlay-containers/720610392d571145fdd4f992cfc3be0e15ea283621b7f1a46f4d17fc6ce62f1f/userdata/conmon.pid
KillMode=none
Type=forking

[Install]
WantedBy=multi-user.target default.target
```
**Additional information you deem important (e.g. issue happens only occasionally):**

This feature would be usefull when using ansible's file copy to determine that the contents of the systemd unit file has changed. The timestamp makes it more difficult to do this and it will always result in a changed file. I can filter out line 2 or look for a timestamp on line 2 and filter it out, but that seems like a inconvenient solution.

**Output of `podman version`:**

```
podman version 2.2.1
```

**Output of `podman info --debug`:**

```
not relevant
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
not relevant
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Not relevant

**Comment by idelsink** [comment]
My current 'hacky' solution in ansible is (for future reference):

```yml
- name: Generate systemd service unit
  command: >
    podman
    generate
    systemd
    --container-prefix ''
    --separator ''
    --restart-policy always
    --name
    {{ service.name }}
  changed_when: false
  register: podman_service_unit_file_with_timestamp
# Remove the third line with a timestamp
# See: https://github.com/containers/podman/issues/8880
- name: Remove timestamp from generated unit file
  command:
    # Disable warning about using sed instead of using replace, lineinfile or template module
    warn: false
    cmd: sed '3d'
    stdin: "{{ podman_service_unit_file_with_timestamp.stdout }}"
  changed_when: false
  register: podman_service_unit_file
```
