### ISSUE TITLE
podman generate kube doesn't export Entrypoint

### ISSUE THREAD

**Issue by fcrozat** [containers/podman#8898]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

when creating a container with a different entrypoint than in the pulled image, the generated kube yaml doesn't set the proper Command

**Steps to reproduce the issue:**

1. podman container create --name foobar --replace  --entrypoint=/bin/zsh registry.opensuse.org/opensuse/tumbleweed:latest

2. podman  generate kube foobar

**Describe the results you received:**

# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.2.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-06T14:40:53Z"
  labels:
    app: foobar
  name: foobar
spec:
  containers:
  - env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: HOSTNAME
    image: registry.opensuse.org/opensuse/tumbleweed:latest
    name: foobar
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}

**Describe the results you expected:**
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.2.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-06T14:40:53Z"
  labels:
    app: foobar
  name: foobar
spec:
  containers:
  - env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: HOSTNAME
    image: registry.opensuse.org/opensuse/tumbleweed:latest
    name: foobar
    command: ["/bin/zsh"]
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Version:      2.2.0
API Version:  2.1.0
Go Version:   go1.13.15
Built:        Wed Dec  2 01:00:00 2020
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**

host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: unknown'
  cpus: 2
  distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20210102"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.3-1-default
  linkmode: dynamic
  memFree: 469622784
  memTotal: 2055946240
  ociRuntime:
    name: runc
    package: runc-1.0.0~rc92-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2142531584
  swapTotal: 2148335616
  uptime: 3h 54m 49.91s (Approximately 0.12 days)
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Build Version: 'Btrfs v5.9 '
    Library Version: "102"
  imageStore:
    number: 40
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1606867200
  BuiltTime: Wed Dec  2 01:00:00 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.2.0

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-2.2.0-1.1.x86_64 (openSUSE Tumbleweed)

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zhangguanzhang** [comment]
use the latest code:
```
 ./bin/podman pod create --name t2
./bin/podman container create --pod t2 --entrypoint top $IMG
./bin/podman generate kube t2
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.0-dev
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-07T02:22:05Z"
  labels:
    app: t2
  name: t2
spec:
  containers:
  - command:
    - top  <------------------ see this
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: HOSTNAME
      value: t2
    image: docker.io/library/alpine:latest
    name: xenodochialishizaka
    resources: {}
    securityContext:

```
/close
