### ISSUE TITLE
"podman play kube" yaml multiple resources

### ISSUE THREAD

**Issue by ADIX7** [containers/podman#9129]
/kind feature

Add support for multiple resources in yaml used by `podman play kube` like kubernetes does have.

**Comment by baude** [comment]
interested in contributing?

**Comment by ADIX7** [comment]
Unfortunately I won't have time to do this in the near future.

**Comment by mheon** [comment]
Can you provide more details here? An example YAML file with the exact resources you want us to support identified, perhaps?

**Comment by ADIX7** [comment]
I mean to concate multiple yaml-s generated by `podman generate kube` separeted by `---` just like in a kubernetes yaml.
I would like to use this feature with https://github.com/containers/podman/issues/8996 to do something like `kustomize build my-overlay | podman play kub -`. The pipe features is WIP but kustomize create a yaml with multiple resources separeted by `---`.

As for this issue:
For example if I create 2 pod like this:

podman create --pod new:nginxpod1 --name nginx1 nginx1
podman create --pod new:nginxpod2 --name nginx1 nginx2

And generate kubernetes yamls

Pod1: `podman generate kube nginxpod1 > pod1.yaml`

*pod1.yaml*
```
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.2.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-27T20:08:05Z"
  labels:
    app: nginxpod1
  name: nginxpod1
spec:
  containers:
  - command:
    - nginx
    - -g
    - daemon off;
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NGINX_VERSION
      value: 1.19.6
    - name: NJS_VERSION
      value: 0.5.0
    - name: PKG_RELEASE
      value: 1~buster
    - name: HOSTNAME
      value: nginxpod1
    image: docker.io/library/nginx:latest
    name: nginx1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  restartPolicy: Never
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}

```

Pod2: `podman generate kube nginxpod2 > pod2.yaml`

*pod2.yaml*
```
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.2.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-27T20:08:56Z"
  labels:
    app: nginxpod2
  name: nginxpod2
spec:
  containers:
  - command:
    - nginx
    - -g
    - daemon off;
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NGINX_VERSION
      value: 1.19.6
    - name: NJS_VERSION
      value: 0.5.0
    - name: PKG_RELEASE
      value: 1~buster
    - name: HOSTNAME
      value: nginxpod2
    image: docker.io/library/nginx:latest
    name: nginx2
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  restartPolicy: Never
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}
```

I would like create a combined yaml like:

*combined.yaml*:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-27T20:08:05Z"
  labels:
    app: nginxpod1
  name: nginxpod1
spec:
  containers:
  - command:
    - nginx
    - -g
    - daemon off;
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NGINX_VERSION
      value: 1.19.6
    - name: NJS_VERSION
      value: 0.5.0
    - name: PKG_RELEASE
      value: 1~buster
    - name: HOSTNAME
      value: nginxpod1
    image: docker.io/library/nginx:latest
    name: nginx1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  restartPolicy: Never
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-27T20:08:56Z"
  labels:
    app: nginxpod2
  name: nginxpod2
spec:
  containers:
  - command:
    - nginx
    - -g
    - daemon off;
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NGINX_VERSION
      value: 1.19.6
    - name: NJS_VERSION
      value: 0.5.0
    - name: PKG_RELEASE
      value: 1~buster
    - name: HOSTNAME
      value: nginxpod2
    image: docker.io/library/nginx:latest
    name: nginx2
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  restartPolicy: Never
status: {}
```

and start it like `podman play kube combined.yaml` which create the 2 pods the same way as `podman play kube pod1.yaml` and `podman play kube pod2.yaml` would.
