### ISSUE TITLE
"podman play kube" fails to set proper DNAT

### ISSUE THREAD

**Issue by cjeanner** [containers/podman#9395]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
It seems ```podman play kube <file>``` doesn't properly set the DNAT when either hostIP or nodeIP is passed: it just redirects everything to it without any filtering.

**Steps to reproduce the issue:**

1. create a yaml file describing a container (type: pod), and make sure you set hostPort, containerPort, protocol, and either nodeIP or hostIP

2. run ```podman play kube your-file.yaml```

3. check the "nat" tables in iptables using ```iptables -vnL -t nat```

**Describe the results you received:**
We can see the generated DNAT rule doesn't take the hostIP nor the nodeIP:
```
Chain CNI-DN-b3a1523ce32d7c202a0ae (1 references)                                                                                                                                                                                             
 pkts bytes target     prot opt in     out     source               destination                                                                                                                                                               
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.255.255.16        0.0.0.0/0            tcp dpt:8006                                                                                                                              
    5   300 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:8006                       
    5   300 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8006 to:10.255.255.16:8006                                                                            
```
The DNAT rule at least should have the "destination" set to the actual nodeIP/hostIP in order to not expose the service everywhere.

**Describe the results you expected:**
We should get some filtering in place, at least the following should exist:
```
Chain CNI-DN-bb8b5624f5594978e3f4b (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.255.255.18        0.0.0.0/0            tcp dpt:8006
    5   300 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:8006
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            192.168.24.1         tcp dpt:8006 to:10.255.255.18:8006
```
See the DNAT line (last one).

**Additional information you deem important (e.g. issue happens only occasionally):**
Here's a part of the yaml file we're using:
```YAML
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ephemeral-heat
  name: ephemeral-heat
spec:
  containers:
  - command:
    - heat-api
    - --config-file
    - /etc/heat/heat.conf
    ports:
    - containerPort: 8006
      hostPort: 8006
      hostIP: 192.168.24.1
      protocol: TCP
```
It can probably be reproduced with any other container having a TCP service listening somewhere (like nginx, httpd, ...).

**Output of `podman version`:**

```
podman version 1.6.4
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.14.7
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.module_el8.3.0+479+69e2ae26.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 0198f57f29209da30f765318dda9328bac6a5e07'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 680919040
  MemTotal: 29216661504
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc10.module_el8.3.0+479+69e2ae26.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 12
  eventlogger: journald
  hostname: undercloud.mydomain.tld
  kernel: 4.18.0-240.10.1.el8_3.x86_64
  os: linux
  rootless: false
  uptime: 25h 52m 50.27s (Approximately 1.04 days)
registries:
  blocked: null
  insecure:
  - undercloud.ctlplane.mydomain.tld
  - 192.168.24.1
  - 192.168.24.3
  - undercloud.ctlplane
  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 62
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 21
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-23.module_el8.3.0+566+4759265c.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes (though "latest" points to the latest version available on centos-8)

**Comment by cjeanner** [comment]
Quick reproducer:
```YAML
apiVersion: v1                                                                  
kind: Pod                                                                       
metadata:                                                                       
  labels:                                                                       
    app: nginx                                                                  
  name: nginx                                                                   
spec:                                                                           
  containers:                                                                   
    - ports:                                                                    
        - containerPort: 80                                                     
          hostPort: 8081                                                        
          hostIP: 192.168.24.1                                                  
          protocol: TCP                                                         
      image: docker.io/library/nginx:latest                                     
      name: nginx-test                                                          
      resources: {}                                                             
status: {}
```

We can also see this when we inspect the pod:
```JSON
{
     "Config": {
          "id": "ef5b00d311d965eb27f73839e99b7da5ddb8611f3575c3949d948d4fa55d34fe",
          "name": "nginx",
          "hostname": "nginx",
          "labels": {
               
          },
          "cgroupParent": "machine.slice",
          "sharesCgroup": true,
          "sharesIpc": true,
          "sharesNet": true,
          "sharesUts": true,
          "infraConfig": {
               "makeInfraContainer": true,
               "infraPortBindings": [
                    {
                         "hostPort": 8081,
                         "containerPort": 80,
                         "protocol": "tcp",
                         "hostIP": ""
                    }
               ]
          },
          "created": "2021-02-16T10:54:04.760666742Z",
          "lockID": 63
     },
     "State": {
          "cgroupPath": "machine.slice/machine-libpod_pod_ef5b00d311d965eb27f73839e99b7da5ddb8611f3575c3949d948d4fa55d34fe.slice",
          "infraContainerID": "956c0209e76d90e8c767a13c022f67905404c3ce26a08995add8b64b557d8fe4"
     },
     "Containers": [
          {
               "id": "2656f82279349cfadea28d1f19282def46f7b14b2b7d39e724410a69a2469b33",
               "state": "running"
          },
          {
               "id": "956c0209e76d90e8c767a13c022f67905404c3ce26a08995add8b64b557d8fe4",
               "state": "running"
          }
     ]
}
```
The "hostIP" is empty..... Though the IP does exist on the host:
```
[CentOS-8.3 - root@undercloud ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
[...]
5: br-ctlplane: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 24:42:01:dd:24:b4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.24.1/24 brd 192.168.24.255 scope global br-ctlplane
       valid_lft forever preferred_lft forever
    inet 192.168.24.3/32 brd 192.168.24.3 scope global br-ctlplane                                                                                                                                                                            
       valid_lft forever preferred_lft forever                                                                                                                                                                                                
    inet 192.168.24.2/32 brd 192.168.24.2 scope global br-ctlplane                                                                                                                                                                            
       valid_lft forever preferred_lft forever                                                                                                                                                                                                
    inet6 fe80::2642:1ff:fedd:24b4/64 scope link                                                                                                                                                                                              
       valid_lft forever preferred_lft forever                                                                                                                                                                                                                                                  
8: cni-podman0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000                                                                                                                                     
    link/ether de:18:f9:67:5e:91 brd ff:ff:ff:ff:ff:ff                                                                                                                                                                                        
    inet 10.255.255.1/24 brd 10.255.255.255 scope global cni-podman0                                                                                                                                                                          
       valid_lft forever preferred_lft forever                                                                                                                                                                                                
    inet6 fe80::dc18:f9ff:fe67:5e91/64 scope link                                                                                                                                                                                             
       valid_lft forever preferred_lft forever                                                                                                                                                                                                

```
