### ISSUE TITLE
How to escape command in kube

### ISSUE THREAD

**Issue by DaniBet** [containers/podman#9655]
Hello,

I am using podman v3.0, this issue was not present in v1.6.

```
command: ['-f', '/opt/mongod.conf']
```

It seems that '-f' doesn't work anymore and it is considered a directory/file. My error:
```
container_linux.go:367: starting container process caused: exec: "-f": executable file not found in $PATH: OCI not found
```

**Comment by mheon** [comment]
Can you provide further details? What image are you using. are you setting entrypoint as well? Full Kube YAML that reproduces would be ideal.

**Comment by DaniBet** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flowmanager
  name: flowmanager_pod
spec:
  containers:
    - image: mongo:3.6
      name: mongodb
      ports:
        - name: mongoport
          hostPort: 27017
          containerPort: 27017
          protocol: tcp
      command: ['-f', '/opt/mongod.conf']
      env:
        - name: MONGO_INTERNAL_PORT
          value: "27017"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "rootpassword"
        - name: MONGO_APP_DATABASE
          value: "umcft"
        - name: MONGO_APP_USER
          value: "flowmanager_user"
        - name: MONGO_APP_PASS
          value: "flowmanager_pass"
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: scripts
        - mountPath: /opt
          name: config
        - mountPath: /data/db
          name: data
  volumes:
    - hostPath:
        path: ./files/mongo/scripts
        type: Directory
      name: scripts
    - hostPath:
        path: ./files/mongo/config
        type: Directory
      name: config
    - hostPath:
        path: ./mongodb_data_container
        type: Directory
      name: data
```
